Update testing chapter to use Starknet Foundry output
cairo-book/cairo-book pull request #1007
Opened 2024-10-12 22:25 UTC by ShantelPeters

updated the how-to-write-test markdown file with the new output , didnt modify any other folders except configuring the scarb.toml to use the [scripts]
test = "snforge test".  and snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry.git", tag = "v0.31.0" }.  

Please review and test. 

Close #997

2024-10-13 08:20 UTC, enitrat requested changes

2024-10-13 08:20 UTC, enitrat commented on listings/ch10-testing-cairo-programs/listing_10_01/output.txt
> -$ scarb cairo-test
If you remove the first line with the command to execute you break the entire mechanism of auto-generation of outputs.

I already made the same comment on the previous PR

You need to keep a command in the first line of the file.

Here this command would be `scarb test` and not `scarb cairo-test` because we're using Starknet foundry as the default test runner.

Once the file contains the command to run, running `cairo-listings output` will automatically re-generate all outputs.

2024-10-13 09:16 UTC, enitrat commented on src/ch10-01-how-to-write-tests.md
> +$ scarb test
you need to use the `include` macro to refer to output files, like done in other places:

https://github.com/cairo-book/cairo-book/blob/fe1f24f977945abbdcb8c080d86d10136b1f7378/src/ch02-03-functions.md#L31-L33

2024-10-13 09:16 UTC, enitrat commented on src/ch10-01-how-to-write-tests.md
> +Here, the gas usage of the `sum_n` function is `80690` (decimal representation of the hex number). The total amount consumed by the test is slightly higher at `140100`, due to some extra steps requir
```suggestion
Here, the gas usage of the `sum_n` function is `80690` (decimal representation of the hex number). The total amount consumed by the test is slightly higher at `140100`, due to some extra steps required to run the entire test function.
```

2024-10-13 09:18 UTC, enitrat requested changes
The changes should be as simple as:

- doing a find-all search for `scarb cairo-test` and replace with `scarb test`
- creating `output.txt` file with the `$ scarb test` command in the first line
- running `cairo-listings output`
- including these `output.txt` files in the corpus for new outputs in chapter 10

2024-10-13 11:01 UTC, ShantelPeters commented
> The changes should be as simple as:
> 
> * doing a find-all search for `scarb cairo-test` and replace with `scarb test`
> * creating `output.txt` file with the `$ scarb test` command in the first line
> * running `cairo-listings output`
> * including these `output.txt` files in the corpus for new outputs in chapter 10

Noted, i just updated the branch, please check

2024-10-13 12:36 UTC, enitrat requested changes
great, we're getting there!
there still are things that need to be worked on.

2024-10-13 12:36 UTC, enitrat commented on listings/ch10-testing-cairo-programs/listing_10_01/Scarb.toml
>  cairo_test = "2.7.0"
now that we're using snforge, you need to remove `cairo_test`

2024-10-13 12:36 UTC, enitrat commented on listings/ch10-testing-cairo-programs/listing_10_02/Scarb.toml
>  cairo_test = "2.7.0"
remove  cairo_test  dependency

2024-10-13 12:36 UTC, enitrat commented on listings/ch10-testing-cairo-programs/listing_10_03/Scarb.toml
>  cairo_test = "2.7.0"
remove cairo_test dependency

2024-10-13 12:36 UTC, enitrat commented on listings/ch10-testing-cairo-programs/listing_10_04/Scarb.toml
>  cairo_test = "2.7.0"
remove cairo_test dependency

2024-10-13 12:36 UTC, enitrat commented on listings/ch10-testing-cairo-programs/listing_10_05/Scarb.toml
>  cairo_test = "2.7.0"
remove cairo_test dependency

2024-10-13 12:36 UTC, enitrat commented on listings/ch10-testing-cairo-programs/listing_10_06/Scarb.toml
>  cairo_test = "2.7.0"
remove cairo_test dependency

2024-10-13 12:36 UTC, enitrat commented on listings/ch10-testing-cairo-programs/listing_10_06/output.txt
> +
looks like something broke here with the transition of test runner.

Can you modify `listings/ch10-testing-cairo-programs/listing_10_06/src/lib.cairo` to fix this issue? It's the `#[should_panic]` attribute argument must be string, short string, number or list of short strings or numbers in regular brackets ()

2024-10-13 12:36 UTC, enitrat commented on listings/ch10-testing-cairo-programs/listing_10_07/Scarb.toml
>  cairo_test = "2.7.0"
remove cairo_test dependency

2024-10-13 12:36 UTC, enitrat commented on listings/ch10-testing-cairo-programs/listing_10_08/Scarb.toml
>  cairo_test = "2.7.0"
remove cairo_test dependency

2024-10-13 12:36 UTC, enitrat commented on listings/ch10-testing-cairo-programs/no_listing_02_custom_messages/Scarb.toml
>  cairo_test = "2.7.0"
remove cairo_test dependency

2024-10-13 12:36 UTC, enitrat commented on listings/ch10-testing-cairo-programs/no_listing_04_new_bug/Scarb.toml
>  cairo_test = "2.7.0"
remove cairo_test dependency

2024-10-13 12:36 UTC, enitrat commented on listings/ch10-testing-cairo-programs/no_listing_05_ignore_tests/Scarb.toml
>  cairo_test = "2.7.0"
remove cairo_test dependency

2024-10-13 12:36 UTC, enitrat commented on listings/ch10-testing-cairo-programs/no_listing_06_test_gas/Scarb.toml
>  cairo_test = "2.7.0"
remove cairo_test dependency

2024-10-13 12:36 UTC, enitrat commented on listings/ch10-testing-cairo-programs/no_listing_09_integration_test/Scarb.toml
>  cairo_test = "2.7.0"
remove cairo_test dependency

2024-10-13 12:36 UTC, enitrat commented on listings/ch10-testing-cairo-programs/no_listing_10_assert_eq_ne_macro/Scarb.toml
>  cairo_test = "2.7.0"
remove cairo_test dependency

2024-10-13 12:36 UTC, enitrat commented on listings/ch10-testing-cairo-programs/no_listing_11_test_private_function/Scarb.toml
>  cairo_test = "2.7.0"
remove cairo_test dependency

2024-10-13 12:36 UTC, enitrat commented on listings/ch10-testing-cairo-programs/no_listing_12_submodules/Scarb.toml
>  cairo_test = "2.7.0"
remove cairo_test dependency

2024-10-13 12:36 UTC, enitrat commented on listings/ch10-testing-cairo-programs/no_listing_13_single_integration_crate/Scarb.toml
>  cairo_test = "2.7.0"
remove cairo_test dependency

2024-10-13 12:36 UTC, enitrat commented on listings/ch17-starknet-smart-contracts-security/listing_02_pizza_factory_snfoundry/output.txt
> +#[should_panic(expected: ("Only the owner can set ownership",))]
fix this issue with the `#[should_panic]` attribute arguments in the source code. The code should compile and the test should run successfully

2024-10-13 12:36 UTC, enitrat commented on listings/ch17-starknet-smart-contracts-security/listing_02_pizza_factory_snfoundry/output.txt
> +error: Inline macro `assert_eq` not found.
you need to add the `assert_eq` dependency in `Scarb.toml`, as said in the issue description.

2024-10-13 12:36 UTC, enitrat commented on src/ch10-01-how-to-write-tests.md
> +Now that you���ve seen what the test results look like in different scenarios, let’s look at some functions that are useful in tests.
```suggestion
Now that you've seen what the test results look like in different scenarios, let’s look at some functions that are useful in tests.
```

2024-10-13 12:36 UTC, enitrat commented on src/ch10-01-how-to-write-tests.md
> +Let’s create a new project called _adder_ using Scarb with the command `scarb new adder`:
```suggestion
Let's create a new project called _adder_ using Scarb with the command `scarb new adder`:
```

2024-10-13 12:36 UTC, enitrat commented on src/ch10-01-how-to-write-tests.md
> +{{#include ../listings/ch10-testing-cairo-programs/listing_10_04/output.txt}}
is this the right file? it's the same as the one above.

2024-10-13 18:56 UTC, ShantelPeters commented on listings/ch10-testing-cairo-programs/listing_10_01/Scarb.toml
>  cairo_test = "2.7.0"
Done

2024-10-13 18:56 UTC, ShantelPeters commented on listings/ch10-testing-cairo-programs/listing_10_02/Scarb.toml
>  cairo_test = "2.7.0"
Done

2024-10-13 18:58 UTC, ShantelPeters commented on listings/ch17-starknet-smart-contracts-security/listing_02_pizza_factory_snfoundry/output.txt
> +error: Inline macro `assert_eq` not found.
Done, added for required sections and they are compiling successfully

2024-10-13 19:17 UTC, ShantelPeters commented on listings/ch17-starknet-smart-contracts-security/listing_02_pizza_factory_snfoundry/output.txt
> +#[should_panic(expected: ("Only the owner can set ownership",))]
> fix this issue with the `#[should_panic]` attribute arguments in the source code. The code should compile and the test should run successfully

I have pushed the changes, i did exactly what you said here but i am still getting errors from here. this is the only one thats left. please check

2024-10-13 19:19 UTC, ShantelPeters commented
I have pushed the changes and corrected everything you asked, i also tried fixing this section but i am still getting errors, please check.  


fix this issue with the #[should_panic] attribute arguments in the source code. The code should compile and the test should run successfully.

2024-10-13 20:45 UTC, enitrat requested changes
great, looks good now :)

2024-10-13 20:45 UTC, enitrat commented on listings/ch10-testing-cairo-programs/output.txt
I think this file is a mistake, it doesn't look like it corresponds to any program?

2024-10-13 20:45 UTC, enitrat commented on listings/ch17-starknet-smart-contracts-security/listing_02_pizza_factory_snfoundry/Scarb.toml
> +# made necessary changes
```suggestion

```

2024-10-13 20:45 UTC, enitrat commented on src/ch10-01-how-to-write-tests.md
> +Here, the gas usage of the `sum_n` function is `80690` (decimal representation of the hex number). The total amount consumed by the test is slightly higher at `140100`, due to some extra steps requir
```suggestion
Here, the gas usage of the `sum_n` function is `80690` (decimal representation of the hex number). The total amount consumed by the test is slightly higher at `140100`, due to some extra steps required to run the entire test function.
```

2024-10-13 20:47 UTC, ShantelPeters commented on listings/ch10-testing-cairo-programs/output.txt
yes i feel so too, it dosent correspond

2024-10-13 20:48 UTC, ShantelPeters commented on src/ch10-01-how-to-write-tests.md
> +Here, the gas usage of the `sum_n` function is `80690` (decimal representation of the hex number). The total amount consumed by the test is slightly higher at `140100`, due to some extra steps requir
ok ill make this change

2024-10-13 20:51 UTC, ShantelPeters commented on listings/ch17-starknet-smart-contracts-security/listing_02_pizza_factory_snfoundry/Scarb.toml
> +# made necessary changes
Done

2024-10-13 20:51 UTC, ShantelPeters commented on src/ch10-01-how-to-write-tests.md
> +Here, the gas usage of the `sum_n` function is `80690` (decimal representation of the hex number). The total amount consumed by the test is slightly higher at `140100`, due to some extra steps requir
Done

2024-10-14 06:48 UTC, ShantelPeters commented
Hi @enitrat please kindly review the requested changes. Thank you.

2024-10-14 17:38 UTC, enitrat commented on listings/ch10-testing-cairo-programs/output.txt
what is this file?

2024-10-14 17:39 UTC, enitrat commented on listings/ch17-starknet-smart-contracts-security/listing_02_pizza_factory_snfoundry/output.txt
> +error[E0002]: Method `deploy` could not be called on type `snforge_std::cheatcodes::contract_class::DeclareResult`.
this is still failing.

2024-10-14 17:41 UTC, enitrat reviewed
Please be more conscientious about your work. I have been reviewing for the 5th time and I can still see obvious wrongdoings just by looking at the git diff 🙏 

example:
-  a file that was compiling before no longer compiles after bumping starknet foundry -> this should be fixed
- an output.txt file that's outside of any listing

2024-10-14 18:05 UTC, ShantelPeters commented
> Please be more conscientious about your work. I have been reviewing for the 5th time and I can still see obvious wrongdoings just by looking at the git diff 🙏
> 
> example:
> 
> * a file that was compiling before no longer compiles after bumping starknet foundry -> this should be fixed
> * an output.txt file that's outside of any listing

My apologies,I will go over it again. 🙏🏼

2024-10-14 19:31 UTC, ShantelPeters commented on listings/ch17-starknet-smart-contracts-security/listing_02_pizza_factory_snfoundry/output.txt
> +error[E0002]: Method `deploy` could not be called on type `snforge_std::cheatcodes::contract_class::DeclareResult`.
@enitrat i have tried alot of fixes to make the test pass but i noticed there are alot of incompatibility issues with the updated snforge_std  which is making it fail all the time, i have tried everything but the tests are just incompatible with the version. :(

2024-10-14 19:31 UTC, ShantelPeters commented
The Output outside the listings have been removed since its is not being used

2024-10-14 20:12 UTC, enitrat commented on listings/ch17-starknet-smart-contracts-security/listing_02_pizza_factory_snfoundry/output.txt
> +error[E0002]: Method `deploy` could not be called on type `snforge_std::cheatcodes::contract_class::DeclareResult`.
1. it looks like you're using an outdated version of the repository that is 2 months late on commits. This created a lot of conflicts, as you can see in the PR.

Everytime you make a PR on an old base you create a lot of conflicts and it's painful to resolve. It's like you were working on a version from 2 months ago, no wonder it had a lot of issues...

 I rebased the branch on the current main for you, so that you can start from a clean state.
 
 Now, on how to solve the error:
 
```
error[E0002]: Method `deploy` could not be called on type `snforge_std::cheatcodes::contract_class::DeclareResult`.
Candidate `ContractClassTrait::deploy` inference failed with: Type mismatch: `snforge_std::cheatcodes::contract_class::DeclareResult` and `@snforge_std::cheatcodes::contract_class::ContractClass`.
 --> /Users/msaug/workspace/cairo-book/listings/ch17-starknet-smart-contracts-security/listing_02_pizza_factory_snfoundry/src/tests/foundry_test.cairo:30:42
    let (contract_address, _) = contract.deploy(@constructor_calldata).unwrap();
```

you open the reference and use it properly https://foundry-rs.github.io/starknet-foundry/appendix/snforge-library/declare.html. Is an import of a trait perhaps missing? 

You can just check examples in the docs and do the same https://foundry-rs.github.io/starknet-foundry/testing/contracts.html#writing-tests

2024-10-14 20:16 UTC, ShantelPeters commented on listings/ch17-starknet-smart-contracts-security/listing_02_pizza_factory_snfoundry/output.txt
> +error[E0002]: Method `deploy` could not be called on type `snforge_std::cheatcodes::contract_class::DeclareResult`.
Ohh thank you very much

2024-10-14 21:39 UTC, enitrat commented on listings/ch17-starknet-smart-contracts-security/listing_02_pizza_factory_snfoundry/src/tests/foundry_test.cairo
> +fn deploy_pizza_factory() -> IPizzaFactoryDispatcher {
only the `deploy_pizza_factory` required changes. restore the file to is initial state

2024-10-14 21:41 UTC, ShantelPeters commented on listings/ch17-starknet-smart-contracts-security/listing_02_pizza_factory_snfoundry/src/tests/foundry_test.cairo
> +fn deploy_pizza_factory() -> IPizzaFactoryDispatcher {
can i just start afresh from the main branch and create a sub branch to make my changes, would that be ok?

2024-10-14 22:47 UTC, ShantelPeters commented
@enitrat i just made a commit, the test is passing now please check

2024-10-17 15:25 UTC, enitrat commented on listings/ch17-starknet-smart-contracts-security/listing_02_pizza_factory_snfoundry/src/tests/foundry_test.cairo
> +#[should_panic]
this is not ok, you can't just delete the assertion on the error string. if you do the entire test is useless.

2024-10-17 15:44 UTC, enitrat approved these changes

2024-10-18 11:01 UTC, enitrat approved these changes

2024-10-18 11:01 UTC, merged