Ci/dependency caching
cairo-book/cairo-book pull request #1044
Opened 2024-12-05 17:34 UTC by 0xdevcollins

Closes #1038

2024-12-05 18:31 UTC, 0xdevcollins commented
@enitrat Please review

2024-12-06 03:46 UTC, enitrat requested changes
A good start, but the real benefits of caching are not yet present because we re-run the "install mdbook" step each run. Because it was re-ran, the CI passed.

You can skip it if the cache-hit was true with:
`if: steps.<id>.outputs.cache-hit != 'true'`

2024-12-06 03:46 UTC, enitrat commented on .github/workflows/ci.yml
> +            mdbook-${{ runner.os }}-
This is just caching the rust dependencies, it's strictly equivalent to the step above, thus has no effect

The MDBook Cache Coverage is actually incomplete, as the current cache only covers Cargo registry and git, but misses several important artifacts:
- The downloaded mdbook binary
- The downloaded mdbook-last-changed binary
- The cloned mdbook-quiz-cairo repository
- The generated bindings from cargo make init-bindings


You should consider separating Binary and Build Caches:

- One for pre-built binaries (mdbook, mdbook-last-changed)
- Another for compiled dependencies (cargo installations), which will end up being covered by the `Cache Rust dependencies` step

something like:

```
- name: Cache mdbook binaries
  uses: actions/cache@v3
  with:
    path: |
      ./bin
      ~/.local/bin
      ~/.cargo/bin
    key: mdbook-bins-${{ runner.os }}-v1-${{ hashFiles('.tool-versions') }}

- name: Cache mdbook build artifacts
  uses: actions/cache@v3
  with:
    path: |
      ~/.cargo/registry
      ~/.cargo/git
      ./target
      ./mdbook-quiz-cairo
    key: mdbook-build-${{ runner.os }}-v1-${{ hashFiles('mdbook-cairo/Cargo.lock', 'mdbook-quiz-cairo/Cargo.lock') }}
```

2024-12-06 03:46 UTC, enitrat commented on .github/workflows/ci.yml
> +
I would actually recommend removing this manual rust cache altogether, remove the `setup-rust-cache` action, and replace these two steps by a simple:

```
    - name: Setup Rust cache
      uses: Swatinem/rust-cache@v2
```

2024-12-09 03:14 UTC, enitrat commented
I think you need to make sure the cargo binaries are in path, let me see

2024-12-10 03:49 UTC, enitrat commented
Looks like we're good here @0xdevcollins, let me know if you have any questions 💯

2024-12-10 03:49 UTC, enitrat commented on .github/workflows/ci.yml
> +      - ci/dependency-caching
```suggestion
```

2024-12-10 03:50 UTC, enitrat commented on .github/workflows/ci.yml
> +        shell: bash
```suggestion
```

2024-12-12 10:15 UTC, enitrat approved these changes

2024-12-12 10:15 UTC, merged