Update ch204-02-02-range-check.md
cairo-book/cairo-book pull request #1074
Opened 2024-12-25 19:33 UTC by ShantelPeters

2024-12-26 12:46 UTC, enitrat requested changes
lots of imprecisions that need to be addressed. lots of details missing, too. you're free to keep working on this but I will be opening to other contributors in parallel.

2024-12-26 12:46 UTC, enitrat commented on src/ch204-02-02-range-check.md
> +![range-check-validation-property](https://github.com/user-attachments/assets/aedb56c1-26ec-4d4d-a688-06bf160a2e7c)
images should be uploaded locally along with the `.json` export

2024-12-26 12:46 UTC, enitrat commented on src/ch204-02-02-range-check.md
> +A specialized tool for confirming that numerical values fall inside predetermined ranges is Cairo's built-in Range Check. It guarantees that a value falls inside a certain range, like [0, 2^128) or m
> A specialized tool

it's not a tool! it's a builtin of the VM.

2024-12-26 12:46 UTC, enitrat commented on src/ch204-02-02-range-check.md
> +A specialized tool for confirming that numerical values fall inside predetermined ranges is Cairo's built-in Range Check. It guarantees that a value falls inside a certain range, like [0, 2^128) or m
> and is also a valid field element (feeling)

feeling ?

2024-12-26 12:46 UTC, enitrat commented on src/ch204-02-02-range-check.md
> +A specialized tool for confirming that numerical values fall inside predetermined ranges is Cairo's built-in Range Check. It guarantees that a value falls inside a certain range, like [0, 2^128) or m
> It is a crucial part of Cairo programs' constraint enforcement.

what does this mean?

2024-12-26 12:46 UTC, enitrat commented on src/ch204-02-02-range-check.md
> +This entire operation takes place in the Range Check Segment, which acts similar to a specialized validation section of memory. Only valid numbers are used in your software because they pass through
> Only valid numbers are used in your software because they pass through this part automatically.

2024-12-26 12:46 UTC, enitrat commented on src/ch204-02-02-range-check.md
> +A specialized tool for confirming that numerical values fall inside predetermined ranges is Cairo's built-in Range Check. It guarantees that a value falls inside a certain range, like [0, 2^128) or m
> It guarantees that a value falls inside a certain range, like [0, 2^128) or more stringent constraints, such [0, 2^96]

what makes this possible? is there verification done in the same place? are there actually _two_ builtins?

2024-12-26 12:46 UTC, enitrat commented on src/ch204-02-02-range-check.md
> +A specialized tool for confirming that numerical values fall inside predetermined ranges is Cairo's built-in Range Check. It guarantees that a value falls inside a certain range, like [0, 2^128) or m
> By delegating range validations to this builtin, Cairo allows for efficient proof creation while also ensuring calculation accuracy without introducing overhead to the application logic.

how much computation overhead does this save? how many instructions would we need if we were using only pure Cairo code?

2024-12-26 12:46 UTC, enitrat commented on src/ch204-02-02-range-check.md
> +assert!(is_valid, 'Value out of range');
this does not demonstrate the use of the range check builtin. if you wanted to illustrate with code, it should probably be with CASM intstructions or Cairo Zero code directly - but you don't have to

2024-12-26 12:46 UTC, enitrat commented on src/ch204-02-02-range-check.md
> +This entire operation takes place in the Range Check Segment, which acts similar to a specialized validation section of memory. Only valid numbers are used in your software because they pass through
not sure what this means

2024-12-26 12:46 UTC, enitrat commented on src/ch204-02-02-range-check.md
> + In the Cairo VM, the Range Check Segment itself seeks for numerical values as depicted in or the flowchart diagram above.  There are three values depicted: 0x000000000000  (valid, zero), 0xFFFFFFFFF
> the Range Check Segment itself seeks for numerical values

the range check segment does not seek for anything. you can just write values to it

2024-12-26 14:31 UTC, ShantelPeters commented on src/ch204-02-02-range-check.md
> +![range-check-validation-property](https://github.com/user-attachments/assets/aedb56c1-26ec-4d4d-a688-06bf160a2e7c)
wow, thank you, i will fix this right away

2024-12-30 15:07 UTC, enitrat requested changes
### Feedback

1. **Technical Inaccuracies**
- Correctly suggests that there's a single builtins for different ranges, but does not clearly mention which ones are actually in production

2. **Missing Core Components**
- No explanation of the memory segment structure, and expected types
- Missing discussion of the validation rules: this builtin is strictly for validation, and produces no output (simply returns the memory address of the range check segment)
- No implementation references (links welcomed)

3. **Structure Problems**
- Missing illustrative diagrams showing memory layout
- Informal writing style, no structure
- Text is too condensed and not properly structured. No inner titles.

### Specific Recommendations

1. **Add Technical Implementation Section**
- Show validation rule implementation
- Try to give an illustrated example of how this is used during a program run. I write a value in the range check segment; what happens next?

2. **Add Memory Layout Section**
- Describe single cell per instance structure

3. **Add Implementation References**
- Link to various implementations (TS, Rust, Python)
- Document validation rules

4. **Correct Technical Information**
- Two active builtins handling range [0, 2^128) and [0, 2^96) in production
- Instruction cost analysis could benefit from a clearer example with latex formulas


### Style and Organization Issues
- Replace informal queue analogy with technical explanation
- Add proper code examples
- Include diagrams showing:
  - Memory layout and validation flow
- Structure similar to Pedersen chapter

2024-12-31 06:50 UTC, enitrat commented on src/ch204-02-02-range-check.md
> +- [Rust Range Check Builtin](https://docs.rs/range_check/latest/range_check/)
CairoVM references...

2024-12-31 06:55 UTC, enitrat commented on src/ch204-02-02-range-check.md
> +![Valid Range Check Segment Diagram_](https://github.com/user-attachments/assets/5960b8e5-740d-415b-98b9-5d3e70c45b77)
upload in the PR along with the.json file

2024-12-31 06:55 UTC, enitrat commented on src/ch204-02-02-range-check.md
> +![INValid Range Check Segment Diagram 234](https://github.com/user-attachments/assets/c2585808-3985-488e-bde2-c75e0973880e)
same

2025-01-08 13:35 UTC, ShantelPeters commented
Hi @enitrat please kindly review the requested changes

2025-01-19 18:02 UTC, enitrat commented
#1096

2025-01-19 18:02 UTC, closed without merging