fix: several typos in the docs
cairo-book/cairo-book pull request #439
Opened 2023-11-16 12:00 UTC by tudorpintea999

Hello
I fixed some typos in the docs,
Hope it helps.
Br,
Tudor.

2023-11-16 14:41 UTC, enitrat requested changes

2023-11-16 14:41 UTC, enitrat commented on src/ch07-02-defining-modules-to-control-scope.md
> +_front of house_ and others as _back of house_. The front of the house is where
please revert these two

2023-11-16 15:07 UTC, tudorpintea999 commented
Hello @enitrat check now

2023-11-17 11:09 UTC, enitrat approved these changes

2023-11-19 06:13 UTC, merged