Rewrite Ch04 - What is Ownership
cairo-book/cairo-book pull request #449
Opened 2023-11-23 08:00 UTC by wraitii

Addresses #382 

Clarify what the linear type system is for.
Clarify what moving and destroying means.
Clarify the semantics of `Copy`, and specifically introduce a distinction between 'variables' and 'values'.
Clarify the cost of the Copy and desnap operators.
Reorganise a few elements.

2023-11-23 08:04 UTC, wraitii commented on src/ch04-01-what-is-ownership.md
> +Consider the following code, where we try to remove the front of the array twice:
Seemed more obvious to me but YMMY

2023-11-23 08:05 UTC, wraitii commented on src/ch04-01-what-is-ownership.md
> -the ownership rules prevent you from doing so.
I removed this 'caused it seemed pretty un-necessary, but can be kept

2023-11-23 08:05 UTC, wraitii commented on src/ch04-01-what-is-ownership.md
> +Returning values is equivalent to _moving_ them. Listing 4-4 shows an example of a
I didn't mention ownership in my initial draft but since I kept the lines in the end the OG formulation is maybe cleaner

2023-11-23 08:27 UTC, enitrat reviewed
Great improvement - it's very clear. 
Just a few comments.

However, I think we should keep talking about ownership. It's a good way of representing which values belongs to what and talking about ownership when talking about moving variables to different "owners" would make sense

2023-11-23 08:27 UTC, enitrat commented on src/ch02-01-variables-and-mutability.md
> +will be changing this variable.
idk about this - variables are still aliases to values, so i'd keep something like 
```suggestion
will be changing the value associated to this variable.
```

2023-11-23 08:27 UTC, enitrat commented on src/ch02-01-variables-and-mutability.md
> +is essentially equivalent to redeclaring it to point to another value in another memory cell,
```suggestion
is essentially equivalent to redeclaring it to refer to to another value in another memory cell,
```

I'd be careful with the word `point` as it's often associated with pointers - which is not really the case

2023-11-23 08:27 UTC, enitrat commented on src/ch02-01-variables-and-mutability.md
> +Upon examining the low-level Cairo Assembly code, it becomes clear that
maybe we should add an illustration? 
I can do it later if you want - just add a TODO line & create an issue

2023-11-23 08:27 UTC, enitrat commented on src/ch02-01-variables-and-mutability.md
> +This makes code easier to reason about.
While I agree with this I think the previous paragraph still had value in this context. Even if Cairo has an immutable memory, the Cairo language totally abstracts this concept. Perhaps you can place the previous paragraph it after the paragraph on mutability? wdyt

2023-11-23 08:27 UTC, enitrat commented on src/ch04-01-what-is-ownership.md
> +Cairo uses a linear type system for two main reasons:
You need to succinctly introduce what a linear type system is. Perhaps add some reasoning about programming paradigms?

2023-11-23 08:27 UTC, enitrat commented on src/ch04-01-what-is-ownership.md
> +In Cairo, ownership applies to _variables_ and not to _values_. A value can safely be pointed to by many different variables (even if they are mutable variables), as the value itself is always immuta
```suggestion
In Cairo, ownership applies to _variables_ and not to _values_. A value can safely be referred to by many different variables (even if they are mutable variables), as the value itself is always immutable.
```

2023-11-23 08:27 UTC, enitrat commented on src/ch04-01-what-is-ownership.md
> +//// CHANGEME
still needs to be changed?

2023-11-23 08:27 UTC, enitrat commented on src/ch04-01-what-is-ownership.md
> +Consider the following code, where we try to remove the front of the array twice:
I think this would need some more details about the inner construction of the array type. If you know that it's a tuple of pointers, then as discussed yesterday you can easily figure out that arrays referred to in two variables are not synced if arrays can be 'copy'

2023-11-23 08:27 UTC, enitrat commented on src/ch04-01-what-is-ownership.md
> +In this case, we try to pass the same value (the array in `arr`) to both function calls. This means our code tries to remove the first element twice, which would try to write to the same memory cell
```suggestion
In this case, we try to pass the same value (the array in the `arr` variable) to both function calls. This means our code tries to remove the first element twice, which would try to write to the same memory cell twice - which is forbidden by the Cairo VM, leading to a runtime error.
```

2023-11-23 08:27 UTC, enitrat commented on src/ch04-01-what-is-ownership.md
> +Thankfully, this code does not actually compile. Once we have passed the array, the variable is no longer usable. We get this compile-time error, telling us that we would need Array to implement the
```suggestion
Thankfully, this code does not actually compile. Once we have passed the array to the `foo` function, the `arr` variable is no longer usable. We get this compile-time error, telling us that we would need Array to implement the Copy Trait:
```

2023-11-23 08:27 UTC, enitrat commented on src/ch04-01-what-is-ownership.md
> +In this example, we can pass `p1` twice to the foo function because the `Point` type implements the `Copy` trait. This means that when we pass `p1` to `foo`, we are actually passing a copy of `p1`, s
should we really remove all mentions of ownership here?

2023-11-23 08:27 UTC, enitrat commented on src/ch04-01-what-is-ownership.md
> +In Cairo, one type that has such behaviour is felt252Dict. For provability, dicts must be 'squashed' when they are destructed.
```suggestion
In Cairo, one type that has such behaviour is `Felt252Dict`. For provability, dicts must be 'squashed' when they are destructed.
```

2023-11-23 08:27 UTC, enitrat commented on src/ch04-01-what-is-ownership.md
> +When a value is destroyed, the compiler calls the `destruct` method on that type. This method is provided by the `Destruct` trait. This is actually how `Drop` is implemented at the moment, by providi
> This is actually how `Drop` is implemented at the moment, by providing a `Destruct` impl that does nothing.

really?

2023-11-23 08:27 UTC, enitrat commented on src/ch04-01-what-is-ownership.md
> +As said earlier, dictionaries in Cairo are types that must be "squashed" when destructed, so that the sequence of access can be proven. This is easy for developers to forget, so instead dictionaries
```suggestion
As said earlier, dictionaries in Cairo are types that must be "squashed" when destructed, so that the sequence of access can be proven. This is easy for developers to forget, so instead dictionaries implement the `Destruct` trait to ensure that all dictionaries are _squashed_ when going out of scope.
```

2023-11-23 08:27 UTC, enitrat commented on src/ch04-01-what-is-ownership.md
> +You may notice that these two traits are somewhat incompatible. With a `Copy` type, we could have two variables pointing to the same value, which would lead to a double-destruction when both variable
I didn't follow on this

2023-11-23 08:27 UTC, enitrat commented on src/ch04-02-references-and-snapshots.md
> +The old memory cell still exists, and snapshots are variables that point to that "old" value.
```suggestion
The old memory cell still exists, and snapshots are variables that refer to that "old" value.
```

2023-11-23 10:05 UTC, wraitii commented on src/ch04-01-what-is-ownership.md
> +When a value is destroyed, the compiler calls the `destruct` method on that type. This method is provided by the `Destruct` trait. This is actually how `Drop` is implemented at the moment, by providi
yup, though there's a TODO to remove that. Check https://github.com/starkware-libs/cairo/blob/main/corelib/src/traits.cairo#L138

My understanding is that this might be changed in the future, but IMO it's clearer to always talk about destroying the value, with drop as a special no-op case

2023-11-23 11:07 UTC, enitrat commented on src/ch04-01-what-is-ownership.md
> +When a value is destroyed, the compiler calls the `destruct` method on that type. This method is provided by the `Destruct` trait. This is actually how `Drop` is implemented at the moment, by providi
I think this is only an impl that allows you to derive `Destruct` on a type that has Drop. But it doesn't inform us about what the compiler is actually doing. 

I think the compiler first tries to drop, then if it's not droppable tries to destruct.

see https://github.com/starkware-libs/cairo/blob/13f4c6aa249143e5cca51450b0744f2a646a5bf0/crates/cairo-lang-lowering/src/destructs.rs#L54-L94

2023-11-24 08:56 UTC, wraitii commented on src/ch04-01-what-is-ownership.md
> +When a value is destroyed, the compiler calls the `destruct` method on that type. This method is provided by the `Destruct` trait. This is actually how `Drop` is implemented at the moment, by providi
Mh, then the TODO is probably redundant at this point.

But it doesn't change much - the fact is that conceptually drop and destroy are the same operation, it's just "destroying" the value. This can have side-effects of not.

2023-11-24 09:01 UTC, enitrat commented on src/ch04-01-what-is-ownership.md
> +When a value is destroyed, the compiler calls the `destruct` method on that type. This method is provided by the `Destruct` trait. This is actually how `Drop` is implemented at the moment, by providi
I don't agree - Destruct is just a drop with extra steps. You squash a dict, you move the dict to the squash funciton, you receive a SquashedDict, which is droppable and goes out of scope seamlessly

2023-11-24 09:09 UTC, wraitii commented on src/ch04-01-what-is-ownership.md
> +When a value is destroyed, the compiler calls the `destruct` method on that type. This method is provided by the `Destruct` trait. This is actually how `Drop` is implemented at the moment, by providi
hm, sure, but that's not the cairo semantics. Would have been neat though.

2023-11-24 09:15 UTC, wraitii commented on src/ch04-01-what-is-ownership.md
> +Consider the following code, where we try to remove the front of the array twice:
I think the previous version had the same problem though, maybe reversed?
I'm not sure which is most obviously broken

2023-11-24 09:17 UTC, wraitii commented on src/ch04-01-what-is-ownership.md
> +You may notice that these two traits are somewhat incompatible. With a `Copy` type, we could have two variables pointing to the same value, which would lead to a double-destruction when both variable
`Destruct` is at the variable scope, not the value-scope. So if you have a `Copy` type, there can be two variables, and thus two `Destruct` runs for the same 'value'.
This is pretty weird and IMO a massive code smell, but not technically broken so I guess I'll change the wording.

2023-11-24 09:22 UTC, enitrat commented on src/ch04-01-what-is-ownership.md
> +When a value is destroyed, the compiler calls the `destruct` method on that type. This method is provided by the `Destruct` trait. This is actually how `Drop` is implemented at the moment, by providi
yes, I think we can just remove this sentence. 

Or you can add precision: The compiler calls `drop` on that type. If the type doesn't implement the `Drop` trait, it calls the `Destruct` trait

2023-11-24 09:23 UTC, enitrat commented on src/ch04-01-what-is-ownership.md
> +You may notice that these two traits are somewhat incompatible. With a `Copy` type, we could have two variables pointing to the same value, which would lead to a double-destruction when both variable
ah ok, yes the wording makes it hard to understand

2023-11-24 09:23 UTC, enitrat commented on src/ch04-01-what-is-ownership.md
> +You may notice that these two traits are somewhat incompatible. With a `Copy` type, we could have two variables pointing to the same value, which would lead to a double-destruction when both variable
also the title `Copy vs Destruct` is not so much adapted

2023-12-08 09:36 UTC, wraitii commented on src/ch02-01-variables-and-mutability.md
> +This makes code easier to reason about.
Added the early part back, so now it just emphasizes a little more.

2023-12-08 09:39 UTC, wraitii commented on src/ch02-01-variables-and-mutability.md
> +Upon examining the low-level Cairo Assembly code, it becomes clear that
There's my graph on excalidraw, but I'll do the TODO thing for now

2023-12-08 09:41 UTC, wraitii commented on src/ch04-01-what-is-ownership.md
> +Cairo uses a linear type system for two main reasons:
Reworked a little as I had an explanation after this

2023-12-08 09:44 UTC, wraitii commented on src/ch04-01-what-is-ownership.md
> +In this example, we can pass `p1` twice to the foo function because the `Point` type implements the `Copy` trait. This means that when we pass `p1` to `foo`, we are actually passing a copy of `p1`, s
Added back

2023-12-09 14:52 UTC, enitrat requested changes
> Reviewed 1 of 4 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cairo-book/cairo-book/449)* status: all files reviewed, 6 unresolved discussions (waiting on @wraitii)

___
*[`src/ch04-01-what-is-ownership.md` line 167 at r2](https://reviewable.io/reviews/cairo-book/cairo-book/449#-NlE2Rrl8jDnJuSIlKvN:-NlE2Rrl8jDnJuSIlKvO:b4rr478) ([raw file](https://github.com/cairo-book/cairo-book/blob/7c6a72a462bd1125aaa0c46bb73cd65817c23612/src/ch04-01-what-is-ownership.md#L167)):*
> ```Markdown
> ```
> When you see a call to `clone`, you know that some arbitrary code is being executed and that code may be expensive. It’s a visual indicator that something different is going on.
> In this case, both the _variable_ and the _value_ are being copied, resulting in new memory cells being used.
> ```

cloned instead of copied?



_Suggestion:_
```Markdown
In this case, both the _variable_ and the _value_ are being cloned, resulting in new memory cells being used.
```


<!-- Sent from Reviewable.io -->

2023-12-09 14:55 UTC, enitrat approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/cairo-book/cairo-book/449#-:-NlE3t_Y4XSeNorpoorS:bnfp4nl)* status: 3 of 4 files reviewed, 6 unresolved discussions (waiting on @wraitii)



<!-- Sent from Reviewable.io -->

2023-12-09 14:55 UTC, merged