feat: While loops
cairo-book/cairo-book pull request #524
Opened 2024-01-23 07:10 UTC by julio4

#523 While loops

Scarb 2.4.0 -> Scarb 2.5.0 (For cairo 2.5.0)
Modified ch02/05-control-flow/Loops to introduce `while` loops construct.
Moved most of the loops explanation of `loop` to `while` to introduce `while` loops first.

2024-01-23 08:14 UTC, enitrat requested changes
Can you modify the order in which things are presented (and how they're presented) to match the rust book? 
https://doc.rust-lang.org/book/ch03-05-control-flow.html

2024-01-23 08:33 UTC, julio4 commented
> Can you modify the order in which things are presented (and how they're presented) to match the rust book? https://doc.rust-lang.org/book/ch03-05-control-flow.html

Didn't noticed it was from rust book. I'll update PR

2024-01-23 08:39 UTC, enitrat commented
yeah, it was a convenient, proof-tested and fast way of starting the cairo book given the similarities between the two languages

2024-01-23 13:08 UTC, julio4 commented
> yeah, it was a convenient, proof-tested and fast way of starting the cairo book given the similarities between the two languages

I reverted most of my changes and keep the same order of sections from the rustbook. It's indeed more simple and straightforward!

2024-01-27 11:14 UTC, enitrat reviewed
lgtm overall

2024-01-27 11:14 UTC, enitrat commented on src/ch02-05-control-flow.md
> -It’s often useful to execute a block of code more than once. For this task, Cairo provides a simple loop syntax, which will run through the code inside the loop body to the end and then start immedia
> To experiment with loops, let’s create a new project called *loops*.

Bring this back

2024-01-27 11:14 UTC, enitrat commented on src/ch02-05-control-flow.md
> -As an example, change the _src/lib.cairo_ file in your _loops_ directory to look
>As an example, change the _src/lib.cairo_ file in your _loops_ directory to look
like this:
<span class="filename">Filename: src/lib.cairo</span>

bring this back

2024-01-27 11:14 UTC, enitrat commented on src/ch02-05-control-flow.md
> +{{#include ../listings/ch02-common-programming-concepts/no_listing_27_infinite_loop/src/lib.cairo}}
The code snippet is:
```rust
fn main() {
    let mut i: usize = 0;
    loop {
        if i > 10 {
            break;
        }
        println!("i = {}", i);
    }
}
```

Can we change it to 

```rust
fn main() {
    loop {
        println!("again!");
    }
}
``` 

Without an explicit condition, as an infinite loop should have?

2024-01-27 11:14 UTC, enitrat commented on src/ch02-05-control-flow.md
>  When we run this program, we’ll see `i = 0` printed over and over continuously
and thus adapt the sentence below to

> When we run this program, we’ll see `again!` printed over and over continuously until either the program runs out of gas we stop the program manually. Most terminals support the keyboard shortcut ctrl-c to interrupt a program that is stuck in a continual loop. Give it a try:

- adapt code snippet here - 

Then, before introducing the concept of gas, add this line.

> Now, try running the same program again, but this time with the `--available-gas` flag set to `100000000000000000`

2024-01-27 22:42 UTC, enitrat approved these changes

2024-01-27 22:47 UTC, merged