feat: add item visibility infos in ch07
cairo-book/cairo-book pull request #577
Opened 2024-02-06 14:28 UTC by TAdev0

Resolves #564 

Still in progress : 
- pub and pub(crate)
- external packages section

i manually renamed all listings and everything, now its contiguous, in the right order, and consistent in the different subchapters

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cairo-book/cairo-book/577)

2024-02-06 14:35 UTC, TAdev0 commented on src/ch07-04-bringing-paths-into-scope-with-the-use-keyword.md
> +the new scope can be exported as if it had been defined in that code’s scope.
mmh , i think we should keep imported maybe, actually the sentence could be right either with exported or imported, depend on interpretation

2024-02-07 08:19 UTC, enitrat requested changes
> Reviewed 43 of 50 files at r1, 3 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cairo-book/cairo-book/577)* status: 46 of 51 files reviewed, 6 unresolved discussions (waiting on @TAdev0)

___
*[`src/ch07-01-packages-and-crates.md` line 5 at r3](https://reviewable.io/reviews/cairo-book/cairo-book/577#-Nq1__ZVB7NbiOqqGIHj:-Nq1__ZVB7NbiOqqGIHk:undefined) ([raw file](https://github.com/cairo-book/cairo-book/blob/ad249ace13d018d15a82bafeb13e0b98a2f27017/src/ch07-01-packages-and-crates.md#L5)):*
> ```Markdown
> ## What is a crate?
> 
> A crate is the smallest amount of code that the Cairo compiler considers at a time. Even if you run `cairo-compile` (CLI tool to compile Cairo code, provided by Scarb) rather than `scarb build` and pass a single source code file, the compiler considers that file to be a crate. Crates can contain modules, and the modules may be defined in other files that get compiled with the crate, as will be discussed in the subsequent sections.
> ```





_Suggestion:_
```Markdown
A compiler binary that can be used to compile cairo files, that scarb extends with additional functionalities
```
___
*[`src/ch07-01-packages-and-crates.md` line 13 at r3](https://reviewable.io/reviews/cairo-book/cairo-book/577#-Nq1c0XpCoGtwfeJHgwH:-Nq1c0Xq6qdkExDTPyrt:b4q6q3d) ([raw file](https://github.com/cairo-book/cairo-book/blob/ad249ace13d018d15a82bafeb13e0b98a2f27017/src/ch07-01-packages-and-crates.md#L13)):*
> ```Markdown
> ## What is a package?
> 
> A cairo package is a bundle of one or more crates, each crate containing a _Scarb.toml_ file that describes how to build it. If the package includes more than one crate, it will contain its own _Scarb.toml_, organizing all included crates as dependencies. This enables the splitting of code into smaller, reusable parts and facilitates more structured dependency management.
> ```

The distinction between crates and packages is a bit blurry, let's double check the scarb docs and ask in the chat



_Code quote:_
```Markdown
A cairo package is a bundle of one or more crates, each crate containing a _Scarb.toml_ file that describes how to build it. If the package includes more than one crate, it will contain its own _Scarb.toml_, organizing all included crates as dependencies. This enables the splitting of code into smaller, reusable parts and facilitates more structured dependency management.
```
___
*[`src/ch07-02-defining-modules-to-control-scope.md` line 104 at r3](https://reviewable.io/reviews/cairo-book/cairo-book/577#-Nq1d4gw9ITZZ1xuo7N5:-Nq1d4gw9ITZZ1xuo7N6:bxiam18) ([raw file](https://github.com/cairo-book/cairo-book/blob/ad249ace13d018d15a82bafeb13e0b98a2f27017/src/ch07-02-defining-modules-to-control-scope.md#L104)):*
> ```Markdown
> Now let’s get into the details of these rules and demonstrate them in action!
> 
> ### Grouping Related Code in Modules
> ```

This needs to be updated with new pub / private visibility attributes and explanations
___
*[`src/ch07-02-defining-modules-to-control-scope.md` line 144 at r3](https://reviewable.io/reviews/cairo-book/cairo-book/577#-Nq1dN0I2CfW3tv9nb-P:-Nq1dN0I2CfW3tv9nb-Q:b-t1fh60) ([raw file](https://github.com/cairo-book/cairo-book/blob/ad249ace13d018d15a82bafeb13e0b98a2f27017/src/ch07-02-defining-modules-to-control-scope.md#L144)):*
> ```Markdown
> to this code would know where to place the code to keep the program organized.
> 
> We can now integrate the _back of house_ module in our _src/lib.cairo_ file:
> ```

I don't think it's time to introduce this here yet
___
*[`src/ch07-02-defining-modules-to-control-scope.md` line 166 at r3](https://reviewable.io/reviews/cairo-book/cairo-book/577#-Nq1dP3V8npyTOaGVDOG:-Nq1dP3V8npyTOaGVDOH:bb7od0r) ([raw file](https://github.com/cairo-book/cairo-book/blob/ad249ace13d018d15a82bafeb13e0b98a2f27017/src/ch07-02-defining-modules-to-control-scope.md#L166)):*
> ```Markdown
>   │      ├── serve_order
>   │      └── take_payment
>   └── back_of_house
> ```

same


<!-- Sent from Reviewable.io -->

2024-02-07 14:52 UTC, TAdev0 reviewed
> *[Reviewable](https://reviewable.io/reviews/cairo-book/cairo-book/577)* status: 36 of 52 files reviewed, 6 unresolved discussions (waiting on @enitrat)

___
*[`src/ch07-01-packages-and-crates.md` line 5 at r3](https://reviewable.io/reviews/cairo-book/cairo-book/577#-Nq1__ZVB7NbiOqqGIHj:-Nq2WpT0C5X8OOFLcYJ3:b-c09g2b) ([raw file](https://github.com/cairo-book/cairo-book/blob/ad249ace13d018d15a82bafeb13e0b98a2f27017/src/ch07-01-packages-and-crates.md#L5)):*
> ```Markdown
> ## What is a crate?
> 
> A crate is the smallest amount of code that the Cairo compiler considers at a time. Even if you run `cairo-compile` (CLI tool to compile Cairo code, provided by Scarb) rather than `scarb build` and pass a single source code file, the compiler considers that file to be a crate. Crates can contain modules, and the modules may be defined in other files that get compiled with the crate, as will be discussed in the subsequent sections.
> ```

Thanks, its better.

mmh we use ''Cairo'' everywhere, with ''C'', for all purposes , it think we should use ''Cairo files''
Same for Scarb
___
*[`src/ch07-01-packages-and-crates.md` line 13 at r3](https://reviewable.io/reviews/cairo-book/cairo-book/577#-Nq1c0XpCoGtwfeJHgwH:-Nq32_fs7cMDlrDYak7N:b-hkzku2) ([raw file](https://github.com/cairo-book/cairo-book/blob/ad249ace13d018d15a82bafeb13e0b98a2f27017/src/ch07-01-packages-and-crates.md#L13)):*
<details><summary><i>Previously, enitrat (Mathieu) wrote…</i></summary><blockquote>

The distinction between crates and packages is a bit blurry, let's double check the scarb docs and ask in the chat
</blockquote></details>

i'm checking now
___
*[`src/ch07-02-defining-modules-to-control-scope.md` line 104 at r3](https://reviewable.io/reviews/cairo-book/cairo-book/577#-Nq1d4gw9ITZZ1xuo7N5:-Nq2XZgkCYyHC6Sylhmt:bb7s9zz) ([raw file](https://github.com/cairo-book/cairo-book/blob/ad249ace13d018d15a82bafeb13e0b98a2f27017/src/ch07-02-defining-modules-to-control-scope.md#L104)):*
<details><summary><i>Previously, enitrat (Mathieu) wrote…</i></summary><blockquote>

This needs to be updated with new pub / private visibility attributes and explanations
</blockquote></details>

yes!
___
*[`src/ch07-02-defining-modules-to-control-scope.md` line 144 at r3](https://reviewable.io/reviews/cairo-book/cairo-book/577#-Nq1dN0I2CfW3tv9nb-P:-Nq2XcSP4ufdjS-tDjKS:b-hfpv0l) ([raw file](https://github.com/cairo-book/cairo-book/blob/ad249ace13d018d15a82bafeb13e0b98a2f27017/src/ch07-02-defining-modules-to-control-scope.md#L144)):*
<details><summary><i>Previously, enitrat (Mathieu) wrote…</i></summary><blockquote>

I don't think it's time to introduce this here yet
</blockquote></details>

removed
___
*[`src/ch07-02-defining-modules-to-control-scope.md` line 166 at r3](https://reviewable.io/reviews/cairo-book/cairo-book/577#-Nq1dP3V8npyTOaGVDOG:-Nq2bOyq7eom4PTKzbO0:b-hfpv0l) ([raw file](https://github.com/cairo-book/cairo-book/blob/ad249ace13d018d15a82bafeb13e0b98a2f27017/src/ch07-02-defining-modules-to-control-scope.md#L166)):*
<details><summary><i>Previously, enitrat (Mathieu) wrote…</i></summary><blockquote>

same
</blockquote></details>

removed


<!-- Sent from Reviewable.io -->

2024-02-07 15:25 UTC, TAdev0 reviewed
> *[Reviewable](https://reviewable.io/reviews/cairo-book/cairo-book/577)* status: 36 of 52 files reviewed, 5 unresolved discussions (waiting on @enitrat and @TAdev0)

___
*[`src/ch07-01-packages-and-crates.md` line 13 at r3](https://reviewable.io/reviews/cairo-book/cairo-book/577#-Nq1c0XpCoGtwfeJHgwH:-Nq38WMQ8Flxt_uLJl6U:bqeh0kh) ([raw file](https://github.com/cairo-book/cairo-book/blob/ad249ace13d018d15a82bafeb13e0b98a2f27017/src/ch07-01-packages-and-crates.md#L13)):*
<details><summary><i>Previously, TAdev0 (Tristan) wrote…</i></summary><blockquote>

i'm checking now
</blockquote></details>

Can't find info in Scarb docs. But i checked the rust book and my modification seems to be correct. A package has a config file and is itself a crate, as all the code it contains in its lib file  is compiled . And that package can contain other packages, which are crates as well

Package defines some ''physical'' (even though virtual..) construct (a folder, with this and this file /folder) , while a crate defines a ''compile unit'' (so all the package's code if we compile from lib.cairo of the package/crate, only a file with cairo-compile..)


<!-- Sent from Reviewable.io -->

2024-02-08 08:39 UTC, enitrat requested changes
The first code example should be modified to 
```
pub mod garden;
use garden::vegetables::Asparagus;

fn main() { 
    let plant = Asparagus {};
     println!("I'm growing {:?}!", plant);
 }
```

Now that we have the derivable debug and the ability to print the struct type 

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cairo-book/cairo-book/577#-:-Nq6p3jJAd_x-n9LJI-s:b7m2y6f)* status: 36 of 52 files reviewed, 7 unresolved discussions (waiting on @TAdev0)

___
*[`listings/ch07-managing-cairo-projects-with-packages-crates-and-modules/listing_07_01/src/lib.cairo` line 3 at r6](https://reviewable.io/reviews/cairo-book/cairo-book/577#-Nq6oR_l6pfVm-v_ziTA:-Nq6oR_l6pfVm-v_ziTB:b3lvfmp) ([raw file](https://github.com/cairo-book/cairo-book/blob/f9bfcf7f34945e7956878087ceb2d9d43bd9fe44/listings/ch07-managing-cairo-projects-with-packages-crates-and-modules/listing_07_01/src/lib.cairo#L3)):*
> ```Cairo
> // ANCHOR: front_of_house
> mod front_of_house {
>     pub mod hosting {
> ```

should not be public for the first listing imo, which is only about organization in modules and not visibility
___
*[`src/ch07-02-defining-modules-to-control-scope.md` line 86 at r6](https://reviewable.io/reviews/cairo-book/cairo-book/577#-Nq6pSQ_4NgdmmU_seKz:-Nq6pSQ_4NgdmmU_seL-:b-tbhi2r) ([raw file](https://github.com/cairo-book/cairo-book/blob/f9bfcf7f34945e7956878087ceb2d9d43bd9fe44/src/ch07-02-defining-modules-to-control-scope.md#L86)):*
> ```Markdown
> ```
> 
> The `pub mod garden;` line imports the module named _garden_. Using `pub` (or `pub(crate)`) is optional here, as the `main` function resides in the same module as `pub mod garden;` declaration. This line tells the compiler to include the code it finds in _src/garden.cairo_, which is:
> ```

This is not really the case: It's optional if you want to run the main function from this crate (or should I only say package?)

But not declaring `garden` pub will make it not accessible from any other package.



_Code quote:_
```Markdown
Using `pub` (or `pub(crate)`) is optional here, as the `main` function resides in the same module as `pub mod garden;` declaration.
```
___
*[`src/ch07-02-defining-modules-to-control-scope.md` line 94 at r6](https://reviewable.io/reviews/cairo-book/cairo-book/577#-Nq6qFQT5Y1c3PEiyGrg:-Nq6qFQT5Y1c3PEiyGrh:bgfxnxm) ([raw file](https://github.com/cairo-book/cairo-book/blob/f9bfcf7f34945e7956878087ceb2d9d43bd9fe44/src/ch07-02-defining-modules-to-control-scope.md#L94)):*
> ```Markdown
> ```
> 
> Here, we use `pub mod vegetables;` but we could have used `pub(crate) mod vegetables;` as well. This line means the code in _src/garden/vegetables.cairo_ is included too. That code is:
> ```

same as above

replace with the simple
`Here, `pub mod vegetables;` means the code in _src/garden/vegetables.rs_ is included too. That code is:`



_Code quote:_
```Markdown
but we could have used `pub(crate) mod vegetables;` as well.
```
___
*[`src/ch07-02-defining-modules-to-control-scope.md` line 105 at r6](https://reviewable.io/reviews/cairo-book/cairo-book/577#-Nq6qqYt3175zQiDb2WR:-Nq6qqYt3175zQiDb2WS:b-r2kskd) ([raw file](https://github.com/cairo-book/cairo-book/blob/f9bfcf7f34945e7956878087ceb2d9d43bd9fe44/src/ch07-02-defining-modules-to-control-scope.md#L105)):*
> ```Markdown
> Now let’s get into the details of these rules and demonstrate them in action!
> 
> ### Grouping Related Code in Modules
> ```

This entire section should be rework to only make public-facing items public. A customer should not be able to access functions ruling how the restaurant works internally.

 The restaurant only wants to expose one single public function, that calls private functions from the restaurant in the correct order, to ensure that no one does things the wrong way. Thus, the functions in the code example here should not be made public.

You can take inspiration about items privacy and its importance from the same paragraph in the rust book



_Code quote:_
```Markdown
### Grouping Related Code in Modules
```


<!-- Sent from Reviewable.io -->

2024-02-08 12:12 UTC, TAdev0 reviewed
on imprime " I'm growing Asparagus { }! " ? ^^

> *[Reviewable](https://reviewable.io/reviews/cairo-book/cairo-book/577#-:-Nq78KoVEvGJWi036_aD:bbdylag)* status: 36 of 52 files reviewed, 9 unresolved discussions (waiting on @enitrat)

___
*[`listings/ch07-managing-cairo-projects-with-packages-crates-and-modules/listing_07_01/src/lib.cairo` line 3 at r6](https://reviewable.io/reviews/cairo-book/cairo-book/577#-Nq6oR_l6pfVm-v_ziTA:-Nq76e-81tIhUwjciWV3:bb7lyle) ([raw file](https://github.com/cairo-book/cairo-book/blob/f9bfcf7f34945e7956878087ceb2d9d43bd9fe44/listings/ch07-managing-cairo-projects-with-packages-crates-and-modules/listing_07_01/src/lib.cairo#L3)):*
<details><summary><i>Previously, enitrat (Mathieu) wrote…</i></summary><blockquote>

should not be public for the first listing imo, which is only about organization in modules and not visibility
</blockquote></details>

ok !
___
*[`src/ch07-02-defining-modules-to-control-scope.md` line 86 at r6](https://reviewable.io/reviews/cairo-book/cairo-book/577#-Nq6pSQ_4NgdmmU_seKz:-Nq79HTV47LXBoiFo-Jx:bxc5ns4) ([raw file](https://github.com/cairo-book/cairo-book/blob/f9bfcf7f34945e7956878087ceb2d9d43bd9fe44/src/ch07-02-defining-modules-to-control-scope.md#L86)):*
<details><summary><i>Previously, enitrat (Mathieu) wrote…</i></summary><blockquote>

This is not really the case: It's optional if you want to run the main function from this crate (or should I only say package?)

But not declaring `garden` pub will make it not accessible from any other package.
</blockquote></details>

yes ! but our example here is about to run a main function with one single package, so ''is optional here / in our example" is correct?
I rewrite it 
___
*[`src/ch07-02-defining-modules-to-control-scope.md` line 94 at r6](https://reviewable.io/reviews/cairo-book/cairo-book/577#-Nq6qFQT5Y1c3PEiyGrg:-Nq7Loat-DXLrmBGFku9:bb7f2mf) ([raw file](https://github.com/cairo-book/cairo-book/blob/f9bfcf7f34945e7956878087ceb2d9d43bd9fe44/src/ch07-02-defining-modules-to-control-scope.md#L94)):*
<details><summary><i>Previously, enitrat (Mathieu) wrote…</i></summary><blockquote>

same as above

replace with the simple
`Here, `pub mod vegetables;` means the code in _src/garden/vegetables.rs_ is included too. That code is:`
</blockquote></details>

done
___
*[`src/ch07-02-defining-modules-to-control-scope.md` line 105 at r6](https://reviewable.io/reviews/cairo-book/cairo-book/577#-Nq6qqYt3175zQiDb2WR:-Nq7QHfBDhmW75y8Wl3o:b5mci7l) ([raw file](https://github.com/cairo-book/cairo-book/blob/f9bfcf7f34945e7956878087ceb2d9d43bd9fe44/src/ch07-02-defining-modules-to-control-scope.md#L105)):*
<details><summary><i>Previously, enitrat (Mathieu) wrote…</i></summary><blockquote>

This entire section should be rework to only make public-facing items public. A customer should not be able to access functions ruling how the restaurant works internally.

 The restaurant only wants to expose one single public function, that calls private functions from the restaurant in the correct order, to ensure that no one does things the wrong way. Thus, the functions in the code example here should not be made public.

You can take inspiration about items privacy and its importance from the same paragraph in the rust book
</blockquote></details>

I definitely didn't check enough rust book for this part and didn't understand correctly the concept
___
*[`src/ch07-03-paths-for-referring-to-an-item-in-the-module-tree.md` line 34 at r6](https://reviewable.io/reviews/cairo-book/cairo-book/577#-Nq76yz10NH5NvyGY-UD:-Nq7Y_PU5xSs02DSDvoK:b2nign6) ([raw file](https://github.com/cairo-book/cairo-book/blob/f9bfcf7f34945e7956878087ceb2d9d43bd9fe44/src/ch07-03-paths-for-referring-to-an-item-in-the-module-tree.md#L34)):*
<details><summary><i>Previously, enitrat (Mathieu) wrote…</i></summary><blockquote>

same remark: the content of the back of house should not be directly accessible to the external user.
</blockquote></details>

yes
___
*[`src/ch07-04-bringing-paths-into-scope-with-the-use-keyword.md` line 77 at r6](https://reviewable.io/reviews/cairo-book/cairo-book/577#-Nq78Htl8pu7Xn49Bhak:-Nq7IBIh0eEX2nMhddl6:b-hnn2lr) ([raw file](https://github.com/cairo-book/cairo-book/blob/f9bfcf7f34945e7956878087ceb2d9d43bd9fe44/src/ch07-04-bringing-paths-into-scope-with-the-use-keyword.md#L77)):*
<details><summary><i>Previously, enitrat (Mathieu) wrote…</i></summary><blockquote>

Quite confusing to use array then - let's use something else that is not exposed automatically, like core::integer::u8_wide_mul
</blockquote></details>

modified with your suggestion : BitSize
___
*[`src/ch07-04-bringing-paths-into-scope-with-the-use-keyword.md` line 126 at r6](https://reviewable.io/reviews/cairo-book/cairo-book/577#-Nq78Twn3n2RqtK9S3Ez:-Nq7CTXO3AlaF4BZGTHN:b-yigp24) ([raw file](https://github.com/cairo-book/cairo-book/blob/f9bfcf7f34945e7956878087ceb2d9d43bd9fe44/src/ch07-04-bringing-paths-into-scope-with-the-use-keyword.md#L126)):*
<details><summary><i>Previously, enitrat (Mathieu) wrote…</i></summary><blockquote>

why pub? the fact that the use is pub just makes it publically accessible from the module it's imported to, but is not related to the description after
</blockquote></details>

corrected


<!-- Sent from Reviewable.io -->

2024-02-08 20:18 UTC, enitrat requested changes
> Reviewed 3 of 16 files at r4, 1 of 3 files at r5, 13 of 14 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cairo-book/cairo-book/577)* status: 52 of 55 files reviewed, 17 unresolved discussions (waiting on @TAdev0)

___
*[`listings/ch07-managing-cairo-projects-with-packages-crates-and-modules/no_listing_02_garden/src/lib.cairo` line 2 at r7](https://reviewable.io/reviews/cairo-book/cairo-book/577#-Nq9MkSvA-S2g4VMHXFX:-Nq9MkSvA-S2g4VMHXFY:b-1eqnk4) ([raw file](https://github.com/cairo-book/cairo-book/blob/c9a3e7a1c32b43b130758c93874bc00885e328fb/listings/ch07-managing-cairo-projects-with-packages-crates-and-modules/no_listing_02_garden/src/lib.cairo#L2)):*
> ```Cairo
> #[derive(Drop, Debug)]
> pub struct Asparagus {} // pub(crate) is also valid
> ```

let's remove this



_Code quote:_
```Cairo
pub(crate) is also valid
```
___
*[`src/ch07-03-paths-for-referring-to-an-item-in-the-module-tree.md` line 12 at r7](https://reviewable.io/reviews/cairo-book/cairo-book/577#-Nq9JgA7BK3LKVrVtZkA:-Nq9JgA7BK3LKVrVtZkB:bejufnt) ([raw file](https://github.com/cairo-book/cairo-book/blob/c9a3e7a1c32b43b130758c93874bc00885e328fb/src/ch07-03-paths-for-referring-to-an-item-in-the-module-tree.md#L12)):*
> ```Markdown
> Both absolute and relative paths are followed by one or more identifiers separated by double colons (`::`).
> 
> To illustrate this notion let's take back our example Listing 7-1 for the restaurant we used in the last chapter. We have a crate named _restaurant_ in which we have a module named _front_of_house_ that contains a module named _hosting_. The _hosting_ module contains a function named `add_to_waitlist`. We want to call the `add_to_waitlist` function from the `eat_at_restaurant` function. We need to tell Cairo the path to the `add_to_waitlist` function so it can find it.
> ```

code items between backticks



_Suggestion:_
```Markdown
`front_of_house`
```
___
*[`src/ch07-03-paths-for-referring-to-an-item-in-the-module-tree.md` line 12 at r7](https://reviewable.io/reviews/cairo-book/cairo-book/577#-Nq9JjO75_Qa1R8d9pUy:-Nq9JjO75_Qa1R8d9pUz:bxvh5zt) ([raw file](https://github.com/cairo-book/cairo-book/blob/c9a3e7a1c32b43b130758c93874bc00885e328fb/src/ch07-03-paths-for-referring-to-an-item-in-the-module-tree.md#L12)):*
> ```Markdown
> Both absolute and relative paths are followed by one or more identifiers separated by double colons (`::`).
> 
> To illustrate this notion let's take back our example Listing 7-1 for the restaurant we used in the last chapter. We have a crate named _restaurant_ in which we have a module named _front_of_house_ that contains a module named _hosting_. The _hosting_ module contains a function named `add_to_waitlist`. We want to call the `add_to_waitlist` function from the `eat_at_restaurant` function. We need to tell Cairo the path to the `add_to_waitlist` function so it can find it.
> ```

same (check whole file)



_Code quote:_
```Markdown
_restaurant_
```
___
*[`src/ch07-03-paths-for-referring-to-an-item-in-the-module-tree.md` line 13 at r7](https://reviewable.io/reviews/cairo-book/cairo-book/577#-Nq9J_7O3a_lK-R8cUZp:-Nq9J_7O3a_lK-R8cUZq:b-erpryo) ([raw file](https://github.com/cairo-book/cairo-book/blob/c9a3e7a1c32b43b130758c93874bc00885e328fb/src/ch07-03-paths-for-referring-to-an-item-in-the-module-tree.md#L13)):*
> ```Markdown
> 
> To illustrate this notion let's take back our example Listing 7-1 for the restaurant we used in the last chapter. We have a crate named _restaurant_ in which we have a module named _front_of_house_ that contains a module named _hosting_. The _hosting_ module contains a function named `add_to_waitlist`. We want to call the `add_to_waitlist` function from the `eat_at_restaurant` function. We need to tell Cairo the path to the `add_to_waitlist` function so it can find it.
> ```

Add details about the pub keyword used for `eat_at_restaurant`

The `eat_at_restaurant` function is part of our library's public API, so we mark it with the `pub` keyword. In the [“Exposing Paths with the `pub` Keyword”] (link) section, we’ll go into more detail about `pub`.
___
*[`src/ch07-03-paths-for-referring-to-an-item-in-the-module-tree.md` line 54 at r7](https://reviewable.io/reviews/cairo-book/cairo-book/577#-Nq9JEaV8V2bbbvrucOL:-Nq9JEaV8V2bbbvrucOM:b2qnl9t) ([raw file](https://github.com/cairo-book/cairo-book/blob/c9a3e7a1c32b43b130758c93874bc00885e328fb/src/ch07-03-paths-for-referring-to-an-item-in-the-module-tree.md#L54)):*
> ```Markdown
> ```
> 
> The error messages say that module _hosting_ and the `add_to_waitlist` function are not visible. In other words, we have the correct paths for the hosting module and the add_to_waitlist function, but Cairo won’t let us use them because it doesn’t have access to them. In Cairo, all items (functions, methods, structs, enums, modules, and constants) are private to parent modules by default. If you want to make an item like a function or struct private, you put it in a module.
> ```

code items should be between backticks, not in italic



_Suggestion:_
```Markdown
`hosting`
```
___
*[`src/ch07-03-paths-for-referring-to-an-item-in-the-module-tree.md` line 54 at r7](https://reviewable.io/reviews/cairo-book/cairo-book/577#-Nq9K3gyB_9MwAZiQwFB:-Nq9K3gyB_9MwAZiQwFC:b-qplaro) ([raw file](https://github.com/cairo-book/cairo-book/blob/c9a3e7a1c32b43b130758c93874bc00885e328fb/src/ch07-03-paths-for-referring-to-an-item-in-the-module-tree.md#L54)):*
> ```Markdown
> ```
> 
> The error messages say that module _hosting_ and the `add_to_waitlist` function are not visible. In other words, we have the correct paths for the hosting module and the add_to_waitlist function, but Cairo won’t let us use them because it doesn’t have access to them. In Cairo, all items (functions, methods, structs, enums, modules, and constants) are private to parent modules by default. If you want to make an item like a function or struct private, you put it in a module.
> ```

format



_Code quote:_
```Markdown
add_to_waitlist
```
___
*[`src/ch07-03-paths-for-referring-to-an-item-in-the-module-tree.md` line 58 at r7](https://reviewable.io/reviews/cairo-book/cairo-book/577#-Nq9KGcZ27PjX34_j0PC:-Nq9KGcZ27PjX34_j0PD:b3kqk) ([raw file](https://github.com/cairo-book/cairo-book/blob/c9a3e7a1c32b43b130758c93874bc00885e328fb/src/ch07-03-paths-for-referring-to-an-item-in-the-module-tree.md#L58)):*
> ```Markdown
> Items in a parent module can’t use the private items inside child modules, but items in child modules can use the items in their ancestor modules. This is because child modules wrap and hide their implementation details, but the child modules can see the context in which they’re defined. To continue with our metaphor, think of the privacy rules as being like the back office of a restaurant: what goes on in there is private to restaurant customers, but office managers can see and do everything in the restaurant they operate.
> 
> Cairo chose to have the module system function this way so that hiding inner implementation details is the default. That way, you know which parts of the inner code you can change without breaking outer code. However, Rust does give you the option to expose inner parts of child modules’ code to outer ancestor modules by using the pub keyword to make an item public.
> ```

!



_Code quote:_
```Markdown
Rust
```
___
*[`src/ch07-03-paths-for-referring-to-an-item-in-the-module-tree.md` line 62 at r7](https://reviewable.io/reviews/cairo-book/cairo-book/577#-Nq9KQXz2rqf2cONquEx:-Nq9KQXz2rqf2cONquEy:b2ni2qw) ([raw file](https://github.com/cairo-book/cairo-book/blob/c9a3e7a1c32b43b130758c93874bc00885e328fb/src/ch07-03-paths-for-referring-to-an-item-in-the-module-tree.md#L62)):*
> ```Markdown
> ### Exposing Paths with the `pub` keyword
> 
> Let’s return to the previous error that told us the _hosting_ module and the `add_to_waitlist` function are not visible. We want the `eat_at_restaurant` function in the parent module to have access to the `add_to_wai [...]

2024-02-08 20:20 UTC, enitrat requested changes
> *[Reviewable](https://reviewable.io/reviews/cairo-book/cairo-book/577)* status: 52 of 55 files reviewed, 15 unresolved discussions (waiting on @TAdev0)

___
*[`src/ch07-02-defining-modules-to-control-scope.md` line 86 at r6](https://reviewable.io/reviews/cairo-book/cairo-book/577#-Nq6pSQ_4NgdmmU_seKz:-Nq9MygvAZhTQ1gK09Jm:bwgvhoo) ([raw file](https://github.com/cairo-book/cairo-book/blob/f9bfcf7f34945e7956878087ceb2d9d43bd9fe44/src/ch07-02-defining-modules-to-control-scope.md#L86)):*
<details><summary><i>Previously, TAdev0 (Tristan) wrote…</i></summary><blockquote>

yes ! but our example here is about to run a main function with one single package, so ''is optional here / in our example" is correct?
I rewrite it
</blockquote></details>

I think if you want to make something public the default should be pub, only if you really want to make it available for your crate only should it be pub(crate). 


<!-- Sent from Reviewable.io -->

2024-02-09 16:16 UTC, enitrat approved these changes
yes!

> Reviewed 8 of 8 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cairo-book/cairo-book/577#-:-NqDe3IN2IUIANzzbMUv:bb7s9zz)* status: all files reviewed, 2 unresolved discussions (waiting on @TAdev0)

___
*[`src/ch07-01-packages-and-crates.md` line 5 at r8](https://reviewable.io/reviews/cairo-book/cairo-book/577#-NqDdb2D21J99lZDxqR-:-NqDdb2D21J99lZDxqR0:b6mstg9) ([raw file](https://github.com/cairo-book/cairo-book/blob/b83bd1bab89e5199e7c278ce9553cd22e31eff9b/src/ch07-01-packages-and-crates.md#L5)):*
> ```Markdown
> ## What is a crate?
> 
> A crate is a subset of a package that is used in the actual Cairo compilation. This includes:
> ```

very nice, I like this definition



_Code quote:_
```Markdown
A crate is a subset of a package that is used in the actual Cairo compilation. This includes:
```
___
*[`src/ch07-02-defining-modules-to-control-scope.md` line 86 at r6](https://reviewable.io/reviews/cairo-book/cairo-book/577#-Nq6pSQ_4NgdmmU_seKz:-NqDdlEm1IcAiViNwdiY:b-7pvwig) ([raw file](https://github.com/cairo-book/cairo-book/blob/f9bfcf7f34945e7956878087ceb2d9d43bd9fe44/src/ch07-02-defining-modules-to-control-scope.md#L86)):*
<details><summary><i>Previously, TAdev0 (Tristan) wrote…</i></summary><blockquote>

ok i modified , tell me if this is ok.
</blockquote></details>

great


<!-- Sent from Reviewable.io -->

2024-02-09 16:17 UTC, merged