feat: selector! macro
cairo-book/cairo-book pull request #653
Opened 2024-03-02 21:29 UTC by JimmyFate

Closes #643

2024-03-05 21:31 UTC, enitrat reviewed
Hi, thanks for the PR! Can you also add info to the macros.md page?

2024-03-05 23:14 UTC, JimmyFate commented
@enitrat Done :)
[mention selector! in macros.md](https://github.com/cairo-book/cairo-book/pull/653/commits/42e6e794c6865e320ada3fd69322b20c61b6c854)

2024-03-05 23:35 UTC, TAdev0 commented
@JimmyFate  i made a few comments. Can you modify what needs to be modified ?

2024-03-05 23:43 UTC, JimmyFate commented
> @JimmyFate i made a few comments. Can you modify what needs to be modified ?

@TAdev0 do you mean comments on Reviewable? I don't see any

2024-03-06 07:53 UTC, TAdev0 requested changes

2024-03-06 08:07 UTC, TAdev0 commented
@JimmyFate  now it should be good. Sorry, i forgot to publish the review.

2024-03-07 06:10 UTC, JimmyFate commented on src/ch14-02-contract-dispatchers-library-dispatchers-and-system-calls.md
> +To use this syscall, we passed in the contract address, the function we want to call, and the call arguments.
Indeed, but it seemed logical not to mention the specifics of how the function is passed, but rather say vaguely that it takes in the function to call, before the entry point selector is explained below.
Can add it back if you prefer though

2024-03-07 06:10 UTC, JimmyFate commented on src/ch14-02-contract-dispatchers-library-dispatchers-and-system-calls.md
> +Note that in `starknet::call_contract_syscall` we didn't specify the function name as a string (ByteArray), but rather used the `selector!` macro, which produces the selector by computing a `sn_kecca
[reword sentence](https://github.com/cairo-book/cairo-book/pull/653/commits/a2ade67cf5d19ca61287f32f3540b18ca750f24d)

2024-03-07 06:10 UTC, JimmyFate commented on src/ch14-02-contract-dispatchers-library-dispatchers-and-system-calls.md
> +In Starknet contract context, a **selector** is an identifier through which a function is callable in transactions or in other classes.
[remove unnecessary](https://github.com/cairo-book/cairo-book/pull/653/commits/6cda7b399164033e5ddb5f3eaeea0a28a774f9d2)

2024-03-07 09:48 UTC, TAdev0 commented on src/ch14-02-contract-dispatchers-library-dispatchers-and-system-calls.md
> +To use this syscall, we passed in the contract address, the function we want to call, and the call arguments.
@enitrat what do you think?

2024-03-08 13:54 UTC, TAdev0 commented on src/ch14-02-contract-dispatchers-library-dispatchers-and-system-calls.md
> +To use this syscall, we passed in the contract address, the function we want to call, and the call arguments.
@JimmyFate  i think its better to add it back.  Moreover, the selector is introduced a few lines after that. You can add a small references to the entrypoint selector section if you want, or just add "(see next section)" or something like that.

2024-03-08 16:41 UTC, TAdev0 requested changes
@JimmyFate i think its better to add it back. Moreover, the selector is introduced a few lines after that. You can add a small reference to the entrypoint selector section if you want, or just add "(see next section)" or something like that.

2024-03-08 17:34 UTC, enitrat commented on src/ch14-02-contract-dispatchers-library-dispatchers-and-system-calls.md
> +In Starknet contract context, a **selector** is an identifier through which a function is callable.
```suggestion
In the context of a smart contract, a selector is a unique identifier for a specific entrypoint of a contract. When a transaction is sent to a contract, it includes the selector in the calldata to specify which function should be executed.

On Starknet, the selector is computed by applying the `sn_keccak` hash function to the string representation of the function name. If the function name is `transfer`, the selector can be computed with `selector!("transfer")`
```

2024-03-08 20:49 UTC, enitrat approved these changes
Great 📈

2024-03-08 21:04 UTC, TAdev0 approved these changes

2024-03-08 21:04 UTC, merged