Various small fixes
cairo-book/cairo-book pull request #670
Opened 2024-03-06 10:24 UTC by TAdev0

2024-03-06 12:57 UTC, enitrat commented on src/ch01-01-installation.md
> +<br>
line break? if yes just skip one extra line in the md

2024-03-06 12:57 UTC, enitrat commented on src/ch02-02-data-types.md
> +<br>
skip extra line instead

2024-03-06 12:57 UTC, enitrat commented on src/ch02-02-data-types.md
> +<br>
same

2024-03-06 12:57 UTC, enitrat commented on src/ch12-02-anatomy-of-a-simple-contract.md
> +You can think of it as a single slot in a database that you can query and modify by calling functions of the code that manage the database.
manages

2024-03-09 20:40 UTC, enitrat requested changes
> Reviewed 42 of 43 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cairo-book/cairo-book/670)* status: all files reviewed, 1 unresolved discussion (waiting on @TAdev0)

___
*[`listings/ch09-error-handling/no_listing_01_panic/src/lib.cairo` line 3 at r2](https://reviewable.io/reviews/cairo-book/cairo-book/670#-NsZw3_pC4j4VnInfk-a:-NsZw3_pC4j4VnInfk-b:bxbp84d) ([raw file](https://github.com/cairo-book/cairo-book/blob/da756fc461ace0a0c409b32562153369f3d5d70e/listings/ch09-error-handling/no_listing_01_panic/src/lib.cairo#L3)):*
> ```Cairo
> fn main() {
>     let mut data = array![];
>     data.append(2);
> ```

can be merged in one line



_Code quote:_
```Cairo
    let mut data = array![];
    data.append(2);
```


<!-- Sent from Reviewable.io -->

2024-03-09 22:33 UTC, TAdev0 reviewed
> *[Reviewable](https://reviewable.io/reviews/cairo-book/cairo-book/670)* status: all files reviewed, 1 unresolved discussion (waiting on @enitrat)

___
*[`listings/ch09-error-handling/no_listing_01_panic/src/lib.cairo` line 3 at r2](https://reviewable.io/reviews/cairo-book/cairo-book/670#-NsZw3_pC4j4VnInfk-a:-Ns_LEBh1mXs96xIiVlx:b-7rl0jq) ([raw file](https://github.com/cairo-book/cairo-book/blob/da756fc461ace0a0c409b32562153369f3d5d70e/listings/ch09-error-handling/no_listing_01_panic/src/lib.cairo#L3)):*
<details><summary><i>Previously, enitrat (Mathieu) wrote…</i></summary><blockquote>

can be merged in one line
</blockquote></details>

done!


<!-- Sent from Reviewable.io -->

2024-03-10 18:22 UTC, enitrat approved these changes
> Reviewed 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cairo-book/cairo-book/670)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @TAdev0)



<!-- Sent from Reviewable.io -->

2024-03-10 18:22 UTC, merged