feat: Rework Chapter 13
cairo-book/cairo-book pull request #672
Opened 2024-03-06 15:49 UTC by TAdev0

2024-03-09 21:13 UTC, enitrat requested changes
> Reviewed 6 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cairo-book/cairo-book/672)* status: 6 of 7 files reviewed, 23 unresolved discussions (waiting on @TAdev0)

___
*[`src/ch12-00-introduction-to-starknet-smart-contracts.md` line 15 at r1](https://reviewable.io/reviews/cairo-book/cairo-book/672#-NsZwxocEza21jOY_IfC:-NsZwxocEza21jOY_IfD:b-3qnc53) ([raw file](https://github.com/cairo-book/cairo-book/blob/6709403827c10ababa2fe02dbaa55e88fac0a1b8/src/ch12-00-introduction-to-starknet-smart-contracts.md#L15)):*
> ```Markdown
> Scarb facilitates smart contract development for Starknet. To enable this feature, you'll need to make some configurations in your _Scarb.toml_ file (see [Installation](./ch01-01-installation.md) for how to install Scarb).
> 
> First, add the `starknet` dependency to your _Scarb.toml_ file. Next, specify the compiler output by adding a `[[target.starknet-contract]]` section to enable the creation of the SIERRA contract class. If you omit to specify the target, compilation will work but Scarb will generate a SIERRA file that is not deployable on the Starknet network.
> ```

suggestion



_Suggestion:_
```Markdown
Next, enable the Starknet contract compilation of the package by adding a `[[target.starknet-contract]]` section. By default, specifying this target will build a Sierra Contract Class file, which can be deployed on Starknet. If you omit to specify the target, your package will compile but will not produce an output that you can use with Starknet.
```
___
*[`src/ch12-00-introduction-to-starknet-smart-contracts.md` line 30 at r1](https://reviewable.io/reviews/cairo-book/cairo-book/672#-NsZy4aD81DD0GOLmZpv:-NsZy4aD81DD0GOLmZpw:bmduzt8) ([raw file](https://github.com/cairo-book/cairo-book/blob/6709403827c10ababa2fe02dbaa55e88fac0a1b8/src/ch12-00-introduction-to-starknet-smart-contracts.md#L30)):*
> ```Markdown
> ```
> 
> If you need to import external dependencies in your project, you can consult the [dedicated section](ch07-04-bringing-paths-into-scope-with-the-use-keyword.md#using-external-packages-in-cairo-with-scarb). For additional configuration, please refer to the [Scarb documentation](https://docs.swmansion.com/scarb/docs/extensions/starknet/contract-target.html#compiling-external-contracts).
> ```

Yes and no - here I would only focus on compiling contracts included in dependencies, not mentioning how to access elements in other packages.



_Code quote:_
```Markdown
If you need to import external dependencies in your project, you can consult the [dedicated section](ch07-04-bringing-paths-into-scope-with-the-use-keyword.md#using-external-packages-in-cairo-with-scarb).
```
___
*[`src/ch12-00-introduction-to-starknet-smart-contracts.md` line 30 at r1](https://reviewable.io/reviews/cairo-book/cairo-book/672#-NsZyJSL0M2VbHtyQh2t:-NsZyJSL0M2VbHtyQh2u:undefined) ([raw file](https://github.com/cairo-book/cairo-book/blob/6709403827c10ababa2fe02dbaa55e88fac0a1b8/src/ch12-00-introduction-to-starknet-smart-contracts.md#L30)):*
> ```Markdown
> ```
> 
> If you need to import external dependencies in your project, you can consult the [dedicated section](ch07-04-bringing-paths-into-scope-with-the-use-keyword.md#using-external-packages-in-cairo-with-scarb). For additional configuration, please refer to the [Scarb documentation](https://docs.swmansion.com/scarb/docs/extensions/starknet/contract-target.html#compiling-external-contracts).
> ```





_Suggestion:_
```Markdown
To compile contracts defined in your package's dependencies, please refer to the [Scarb documentation](https://docs.swmansion.com/scarb/docs/extensions/starknet/contract-target.html#compiling-external-contracts).
```
___
*[`src/ch12-01-general-introduction-to-smart-contracts.md` line 71 at r1](https://reviewable.io/reviews/cairo-book/cairo-book/672#-NsZyaDI9CrqbCRIygDI:-NsZyaDI9CrqbCRIygDJ:b-im3s9q) ([raw file](https://github.com/cairo-book/cairo-book/blob/6709403827c10ababa2fe02dbaa55e88fac0a1b8/src/ch12-01-general-introduction-to-smart-contracts.md#L71)):*
> ```Markdown
> ```
> 
> Contracts deployed on the Starknet network are essentially programs that can run on the Starknet OS, and as such, have access to Starknet's state. Contracts do not have a `main` function but one or multiple functions that can serve as entry points.
> ```

Apparently the Starknet OS is only used in the prover and while this is technically correct it's not super accurate to say so.

Contracts deployed on the Starknet network are essentially programs that are run by the sequencer, and as such, 



_Suggestion:_
```Markdown
Contracts deployed on the Starknet network are essentially programs that are run by the sequencer, and as such, 
```
___
*[`src/ch12-02-anatomy-of-a-simple-contract.md` line 16 at r1](https://reviewable.io/reviews/cairo-book/cairo-book/672#-NsZzE3r6DyPdXp34aLu:-NsZzE3r6DyPdXp34aLv:bo09m4m) ([raw file](https://github.com/cairo-book/cairo-book/blob/6709403827c10ababa2fe02dbaa55e88fac0a1b8/src/ch12-02-anatomy-of-a-simple-contract.md#L16)):*
> ```Markdown
> ## What is this contract?
> 
> Contracts are a combintation of state and logic inside a module annotated with the `#[starknet::contract]` attribute.
> ```

it missed some "link" words between the two parts of the sentence



_Suggestion:_
```Markdown
Contracts are defined by encapsulating state and logic within a module annotated with the #[starknet::contract] attribute.
```
___
*[`src/ch12-02-anatomy-of-a-simple-contract.md` line 33 at r1](https://reviewable.io/reviews/cairo-book/cairo-book/672#-NsZztHuAWeN-_xHt6zu:-NsZztHuAWeN-_xHt6zv:b-855ulq) ([raw file](https://github.com/cairo-book/cairo-book/blob/6709403827c10ababa2fe02dbaa55e88fac0a1b8/src/ch12-02-anatomy-of-a-simple-contract.md#L33)):*
> ```Markdown
> Interfaces represent the blueprint of the contract. They define the functions that the contract exposes to the outside world. In Cairo, they're defined by annotating a trait with the `#[starknet::interface]` attribute. All functions of the trait are considered public functions of any contract that implements this trait, and are callable from the outside world.
> 
> All contract interfaces use a generic type for the `self` parameter, representing the contract state. This parameter is required for any Starknet contract function, whether publicly accessible or not. It is a convention to name this generic parameter `TContractState` in interfaces, but this is not enforced and any name can be chosen.
> ```

It's not going to be in the interface if not publicly accessible



_Code quote:_
```Markdown
This parameter is required for any Starknet contract function, whether publicly accessible or not.
```
___
*[`src/ch12-02-anatomy-of-a-simple-contract.md` line 33 at r1](https://reviewable.io/reviews/cairo-book/cairo-book/672#-NsZzxgN-tdivJJnOItD:-NsZzxgN-tdivJJnOItE:b-jc3jsk) ([raw file](https://github.com/cairo-book/cairo-book/blob/6709403827c10ababa2fe02dbaa55e88fac0a1b8/src/ch12-02-anatomy-of-a-simple-contract.md#L33)):*
> ```Markdown
> Interfaces represent the blueprint of the contract. They define the functions that the contract exposes to the outside world. In Cairo, they're defined by annotating a trait with the `#[starknet::interface]` attribute. All functions of the trait are considered public functions of any contract that implements this trait, and are callable from the outside world.
> 
> All contract interfaces use a generic type for the `self` parameter, representing the contract state. This parameter is required for any Starknet contract function, whether publicly accessible or not. It is a convention to name this generic parameter `TContractState` in interfaces, but this is not enforced and any name can be chosen.
> ```

Not really a convention. I'm actually wondering if we shouldn't just name it T. Perhaps having `State` makes it easier to understand what the generic is about, though. :thinking: 



_Suggestion:_
```Markdown
We chose to name this generic parameter `TC [...]

2024-03-09 21:14 UTC, enitrat reviewed
Some suggestions

> *[Reviewable](https://reviewable.io/reviews/cairo-book/cairo-book/672#-:-Ns_3DQ61PHrXoVBhEKX:by8cv6w)* status: 6 of 7 files reviewed, 23 unresolved discussions (waiting on @TAdev0)



<!-- Sent from Reviewable.io -->

2024-03-09 23:46 UTC, TAdev0 reviewed
After these 2 PR i'll do a PR to reorganize listings and integrate labels for listings everywhere , because for now some chapters dont have any explicit listings while other do. 

> *[Reviewable](https://reviewable.io/reviews/cairo-book/cairo-book/672#-:-Ns_az8E5VM4u0F4SUM8:b-ndsm0c)* status: 6 of 7 files reviewed, 23 unresolved discussions (waiting on @enitrat)

___
*[`src/ch12-00-introduction-to-starknet-smart-contracts.md` line 15 at r1](https://reviewable.io/reviews/cairo-book/cairo-book/672#-NsZwxocEza21jOY_IfC:-Ns_O8M4647RnlueUAtU:bvyb82h) ([raw file](https://github.com/cairo-book/cairo-book/blob/6709403827c10ababa2fe02dbaa55e88fac0a1b8/src/ch12-00-introduction-to-starknet-smart-contracts.md#L15)):*
<details><summary><i>Previously, enitrat (Mathieu) wrote…</i></summary><blockquote>

suggestion
</blockquote></details>

better.
___
*[`src/ch12-00-introduction-to-starknet-smart-contracts.md` line 30 at r1](https://reviewable.io/reviews/cairo-book/cairo-book/672#-NsZy4aD81DD0GOLmZpv:-Ns_Pviy9gWqdyphpBt_:b-535fi8) ([raw file](https://github.com/cairo-book/cairo-book/blob/6709403827c10ababa2fe02dbaa55e88fac0a1b8/src/ch12-00-introduction-to-starknet-smart-contracts.md#L30)):*
<details><summary><i>Previously, enitrat (Mathieu) wrote…</i></summary><blockquote>

Yes and no - here I would only focus on compiling contracts included in dependencies, not mentioning how to access elements in other packages.
</blockquote></details>

makes sense indeed. I changed for your suggestion.
___
*[`src/ch12-00-introduction-to-starknet-smart-contracts.md` line 30 at r1](https://reviewable.io/reviews/cairo-book/cairo-book/672#-NsZyJSL0M2VbHtyQh2t:-Ns_Q4-v-2nwe6WQkxkq:b-896fix) ([raw file](https://github.com/cairo-book/cairo-book/blob/6709403827c10ababa2fe02dbaa55e88fac0a1b8/src/ch12-00-introduction-to-starknet-smart-contracts.md#L30)):*
> ```Markdown
> ```
> 
> If you need to import external dependencies in your project, you can consult the [dedicated section](ch07-04-bringing-paths-into-scope-with-the-use-keyword.md#using-external-packages-in-cairo-with-scarb). For additional configuration, please refer to the [Scarb documentation](https://docs.swmansion.com/scarb/docs/extensions/starknet/contract-target.html#compiling-external-contracts).
> ```

Done.
___
*[`src/ch12-01-general-introduction-to-smart-contracts.md` line 71 at r1](https://reviewable.io/reviews/cairo-book/cairo-book/672#-NsZyaDI9CrqbCRIygDI:-Ns_QRJGAfYoUipq-C8W:b-t36aku) ([raw file](https://github.com/cairo-book/cairo-book/blob/6709403827c10ababa2fe02dbaa55e88fac0a1b8/src/ch12-01-general-introduction-to-smart-contracts.md#L71)):*
<details><summary><i>Previously, enitrat (Mathieu) wrote…</i></summary><blockquote>

Apparently the Starknet OS is only used in the prover and while this is technically correct it's not super accurate to say so.

Contracts deployed on the Starknet network are essentially programs that are run by the sequencer, and as such,
</blockquote></details>

yes, true. The starknet OS is a cairo program run by SHARP :

https://hackmd.io/@pragma/ByP-iux1T
___
*[`src/ch12-02-anatomy-of-a-simple-contract.md` line 16 at r1](https://reviewable.io/reviews/cairo-book/cairo-book/672#-NsZzE3r6DyPdXp34aLu:-Ns_ROxb5vZYGGA5AH6t:b-1kwxqa) ([raw file](https://github.com/cairo-book/cairo-book/blob/6709403827c10ababa2fe02dbaa55e88fac0a1b8/src/ch12-02-anatomy-of-a-simple-contract.md#L16)):*
<details><summary><i>Previously, enitrat (Mathieu) wrote…</i></summary><blockquote>

it missed some "link" words between the two parts of the sentence
</blockquote></details>

ok.
I didn't change ''combintation" because i changed it in my other PR. 
But your sentence is way better, just used yours. There will be a little conflict i'll resolve it between the 2 merges
___
*[`src/ch12-02-anatomy-of-a-simple-contract.md` line 33 at r1](https://reviewable.io/reviews/cairo-book/cairo-book/672#-NsZzxgN-tdivJJnOItD:-Ns_T2ioDcTII-OYkisS:b-xnpbpy) ([raw file](https://github.com/cairo-book/cairo-book/blob/6709403827c10ababa2fe02dbaa55e88fac0a1b8/src/ch12-02-anatomy-of-a-simple-contract.md#L33)):*
<details><summary><i>Previously, enitrat (Mathieu) wrote…</i></summary><blockquote>

Not really a convention. I'm actually wondering if we shouldn't just name it T. Perhaps having `State` makes it easier to understand what the generic is about, though. :thinking:
</blockquote></details>

got it ! I like TState or TContractState better than T personally :p
___
*[`src/ch12-02-anatomy-of-a-simple-contract.md` line 36 at r1](https://reviewable.io/reviews/cairo-book/cairo-book/672#-NsZzhFM89Y8yeXoZO_B:-Ns_TQxl0XDgItYlCNpk:bb7pcsz) ([raw file](https://github.com/cairo-book/cairo-book/blob/6709403827c10ababa2fe02dbaa55e88fac0a1b8/src/ch12-02-anatomy-of-a-simple-contract.md#L36)):*
<details><summary><i>Previously, enitrat (Mathieu) wrote…</i></summary><blockquote>

before the enumeration we said that these were functions, we can avoid repeating ourselves
</blockquote></details>

true
___
*[`src/ch12-02-anatomy-of-a-simple-contract.md` line 37 at r1](https://reviewable.io/reviews/cairo-book/cairo-book/672#-NsZzopW0Xuf7i6wejJn:-Ns_TSG3BznhcsU_vZiR:b-896fix) ([raw file](https://github.com/cairo-book/cairo-book/blob/6709403827c10ababa2fe02dbaa55e88fac0a1b8/src/ch12-02-anatomy-of-a-simple-contract.md#L37)):*
<details><summary><i>Previously, enitrat (Mathieu) wrote…</i></summary><blockquote>

same
</blockquote></details>

Done.
___
*[`src/ch12-02-anatomy-of-a-simple-contract.md` line 38 at r1](https://reviewable.io/reviews/cairo-book/cairo-book/672#-Ns_-XNZApvKzH0K9paO:-Ns_Ubbi4Eo4flfDraBp:b-m9vc1m) ([raw file](https://github.com/cairo-book/cairo-book/blob/1a6fda11d197e20d318531ce861d6c943951b842/src/ch12-02-anatomy-of-a-simple-contract.md#L38)):*
<details><summary><i>Previously, enitrat (Mathieu) wrote…</i></summary><blockquote>

I would keep this
</blockquote></details>

I kept with a slight modification
___
*[`src/ch12-02-anatomy-of-a-simple-contract.md` line 39 at r1](https://reviewable.io/reviews/cairo-book/cairo-book/672#-Ns_-LV99Xi7aFRrpNRr:-Ns_To7E2OZh-H8MjP1o:b-896fix) ([raw file](https://github.com/cairo-book/cairo-book/blob/6709403827c10ababa2fe02dbaa55e88fac0a1b8/src/ch12-02-anatomy-of-a-simple-contract.md#L39)):*
> ```Markdown
> - `get` function that receives a snapshot of `self`, allowing only contract state access. Modifying the storage of a contract is not possible when `self` is of type `@TContractState`, and you will get an error when compiling if you try to do so.
> 
> By leveraging the [traits & impls](./ch08-02-traits-in-cairo.md) mechanism from Cairo, we can make sure that the actual implementation of the contract matches its interface. In fact, you will get a compilation error if your contract doesn’t conform with the declared interface. For example, Listing {{#ref wrong-interface}} shows a wrong implementation of `ISimpleStorage` trait of the interface, containing a slightly different `set` function that doesn't take any input, except `self`.
> ```

Done.
___
*[`src/ch12-02-anatomy-of-a-simple-contract.md` line 39 at r1](https://reviewable.io/reviews/cairo-book/cairo-book/672#-Ns_-PcU0LLpg2ImHMXO:-Ns_Tyd05xrFrvzoG6U7:b-896fix) ([raw file](https://github.com/cairo-book/cairo-book/blob/6709403827c10ababa2fe02dbaa55e88fac0a1b8/src/ch12-02-anatomy-of-a-simple-contract.md#L39)):*
> ```Markdown
> - `get` function that receives a snapshot of `self`, allowing only contract state access. Modifying the storage of a contract is not possible when `self` is of type `@TContractState`, and you will get an error when compiling if you try to do so.
> 
> By leveraging the [traits & impls](./ch08-02-traits-in-cairo.md) mechanism from Cairo, we can make sure that the actual implementation of the contract matches its interface. In fact, you will get a compilation error if your contract doesn’t conform with the declared interface. For example, Listing {{#ref wrong-interface}} shows a wrong implementation of `ISimpleStorage` trait of the interface, co [...]

2024-03-09 23:49 UTC, TAdev0 commented on listings/ch99-starknet-smart-contracts/no_listing_standalone/Scarb.toml
i have left edition of october because of the issue with store attribute visibility

2024-03-10 09:43 UTC, enitrat requested changes
Not everything needs to be explicit. As a rule of thumb I would say that only if a Listing is being referred to in multiple places or illustrates an important concept (and not a variation?) we can caption and numerotate it

> Reviewed 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cairo-book/cairo-book/672#-:-NsbhsaS13u4FEXgMjVJ:b-zdluhw)* status: all files reviewed, 4 unresolved discussions (waiting on @TAdev0)

___
*[`listings/ch99-starknet-smart-contracts/no_listing_standalone/src/lib.cairo` line 0 at r2](https://reviewable.io/reviews/cairo-book/cairo-book/672#-NsbjjKlCtnogsGVCGp1:-NsbjjKlCtnogsGVCGp2:b1jf3ex) ([raw file](https://github.com/cairo-book/cairo-book/blob/e44e9f1bd0c8ee9cbb1dadb58f6eb815902d34aa/listings/ch99-starknet-smart-contracts/no_listing_standalone/src/lib.cairo#L0)):*
what happened to this file? Is it still necessary?
___
*[`src/ch12-02-anatomy-of-a-simple-contract.md` line 72 at r2](https://reviewable.io/reviews/cairo-book/cairo-book/672#-Nsbijjt60sUzf8wWruz:-Nsbijjt60sUzf8wWrv-:b-j5e43t) ([raw file](https://github.com/cairo-book/cairo-book/blob/e44e9f1bd0c8ee9cbb1dadb58f6eb815902d34aa/src/ch12-02-anatomy-of-a-simple-contract.md#L72)):*
> ```Markdown
> - What we call an _external_ function is a public function that can be directly invoked through a Starknet transaction and that can mutate the state of the contract. `set` is an external function.
> 
> - A _view_ function is a read-only function that cannot mutate the state of the contract. `get` is a view function.
> ```

I think keeping "public" is important here to emphasize the fact that both _view_. and _external_. are public

Also: regarding the state mutability, if you use storage syscalls in a view functino that is called with an INVOKE transaction, you can modify the storage. Let's keep it this way for now, but we will need to mention this somewhere in the book (security, maybe? I think it was a Node Guardians challenge)


<!-- Sent from Reviewable.io -->

2024-03-10 10:01 UTC, TAdev0 commented
Yes I know about this detail about state mutability. I think you're right , the security section is a good place to explain it. 

About the file you mentioned , I use it to show the standalone public functions in contract functions section in ch14. 

I can reduce the whole contract to show only the interface and the standalone function, but anyway the listing only shows these 2 elements in the book

2024-03-10 18:15 UTC, enitrat reviewed
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cairo-book/cairo-book/672)* status: all files reviewed, 2 unresolved discussions (waiting on @TAdev0)



<!-- Sent from Reviewable.io -->

2024-03-10 21:04 UTC, enitrat requested changes
> *[Reviewable](https://reviewable.io/reviews/cairo-book/cairo-book/672)* status: all files reviewed, 8 unresolved discussions (waiting on @TAdev0)

___
*[`src/ch12-02-anatomy-of-a-simple-contract.md` line 16 at r3](https://reviewable.io/reviews/cairo-book/cairo-book/672#-Nse7kYa8zNAx90f4HlY:-Nse7kYa8zNAx90f4HlZ:undefined) ([raw file](https://github.com/cairo-book/cairo-book/blob/1850a2c97af33b0a859501949df528a8a3f09b05/src/ch12-02-anatomy-of-a-simple-contract.md#L16)):*
> ```Markdown
> ## What is this contract?
> 
> Contracts are defined by encapsulating state and logic within a module annotated with the #[starknet::contract] attribute.
> ```





_Suggestion:_
```Markdown
`#[starknet::contract]`
```
___
*[`src/ch12-02-anatomy-of-a-simple-contract.md` line 68 at r3](https://reviewable.io/reviews/cairo-book/cairo-book/672#-Nse8M6U-s0byVg8JjvG:-Nse8M6U-s0byVg8JjvH:b7ihl0h) ([raw file](https://github.com/cairo-book/cairo-book/blob/1850a2c97af33b0a859501949df528a8a3f09b05/src/ch12-02-anatomy-of-a-simple-contract.md#L68)):*
> ```Markdown
> Before we explore things further down, let's define some terminology.
> 
> - In the context of Starknet, a _public function_ is a function that is exposed to the outside world. In the example above, `set` and `get` are public functions. A public function can be called by anyone, either from outside the contract or from within the contract itself. In the example above, `set` and `get` are public functions.
> ```

repetition to remove 



_Code quote:_
```Markdown
In the example above, `set` and `get` are public functions.
```
___
*[`src/ch12-02-anatomy-of-a-simple-contract.md` line 89 at r3](https://reviewable.io/reviews/cairo-book/cairo-book/672#-Nse8eG25Ng0y3qrcVkz:-Nse8eG25Ng0y3qrcVl-:undefined) ([raw file](https://github.com/cairo-book/cairo-book/blob/1850a2c97af33b0a859501949df528a8a3f09b05/src/ch12-02-anatomy-of-a-simple-contract.md#L89)):*
> ```Markdown
> When writing the implementation of an interface, the `self` parameter in the trait methods must be of type `ContractState`. The `ContractState` type is generated by the compiler, and gives access to the storage variables defined in the `Storage` struct.
> Additionally, `ContractState` gives us the ability to emit events. The name `ContractState` is not surprising, as it’s a representation of the contract’s state, which is what we think of `self` in the contract interface trait.
> When `self` is a snapshot of `ContractState`, only read access is allowed, and emitting event is not possible.
> ```





_Suggestion:_
```Markdown
events
```
___
*[`src/ch12-02-anatomy-of-a-simple-contract.md` line 94 at r3](https://reviewable.io/reviews/cairo-book/cairo-book/672#-Nse8rnsAJNVxwOrpKD0:-Nse8rnsAJNVxwOrpKD1:b-h0132f) ([raw file](https://github.com/cairo-book/cairo-book/blob/1850a2c97af33b0a859501949df528a8a3f09b05/src/ch12-02-anatomy-of-a-simple-contract.md#L94)):*
> ```Markdown
> 
> Two methods are commonly used to access or modify the state of a contract:
> - `read`, allowing to read the value of a storage variable. This method takes only one argument, which is the name of the variable being read. 
> ```

In this paragraph, I think it's not super clear because we call storage_var.read() and storage_var.write(x), so in the first case we give zero parameters and in the second case we give one.

similar suggestion for write



_Suggestion:_
```Markdown
Two methods are commonly used to access or modify the state of a contract through storage variables:
- `read`, which returns the value of a storage variable. This method is called on the variable itself and does not take any argument.
```
___
*[`src/ch12-02-anatomy-of-a-simple-contract.md` line 108 at r3](https://reviewable.io/reviews/cairo-book/cairo-book/672#-Nse9eWY3U_Q_uWwBuNK:-Nse9eWY3U_Q_uWwBuNL:b-ik03c2) ([raw file](https://github.com/cairo-book/cairo-book/blob/1850a2c97af33b0a859501949df528a8a3f09b05/src/ch12-02-anatomy-of-a-simple-contract.md#L108)):*
> ```Markdown
> > Reminder: if the contract state is passed as a snapshot with `@` instead of passed by reference with `ref`, attempting to modify the contract state will result in a compilation error.
> 
> This contract does not do much yet apart from allowing anyone to store a single number that is accessible by anyone in the world. Anyone could call `set` again with a different value and overwrite the current number. Nevertheless, each value stored in the storage of the contract will still be stored in the history of the blockchain. Later in this book, you will see how you can impose access restrictions so that only you can alter the number.
> ```

no intention of extending it
___
*[`src/ch13-02-contract-functions.md` line 47 at r3](https://reviewable.io/reviews/cairo-book/cairo-book/672#-NseAS3T9f_OtKnDTD5l:-NseAS3T9f_OtKnDTD5m:bnq2q0k) ([raw file](https://github.com/cairo-book/cairo-book/blob/1850a2c97af33b0a859501949df528a8a3f09b05/src/ch13-02-contract-functions.md#L47)):*
> ```Markdown
> > **Note:** It's important to note that both external and view functions are public. To create an internal function in a contract, you will need to define it outside of the implementation block annotated with the `#[abi(embed_v0)]` attribute.
> 
> ### Standalone public functions
> ```

How could this section blend-in with the existing contract? 

Perhaps the "free functions" section can be adapted. One of the two free function can be annotated with the external attribute, so that people can copy-paste the example and play with it without doing any modifications.


<!-- Sent from Reviewable.io -->

2024-03-11 13:17 UTC, TAdev0 commented
@enitrat  still a bit unsatisfied with the `get_owner_storage_address` free function which is never used in the contract. In a way, its nice to keep it as it shows the usage of `address()` to get the StorageBaseAddress, but it is incompatible with a public function and i cannot think of a way to integrate it.

2024-03-15 13:40 UTC, enitrat requested changes
> Reviewed 2 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cairo-book/cairo-book/672)* status: 5 of 9 files reviewed, 8 unresolved discussions (waiting on @TAdev0)

___
*[`listings/ch99-starknet-smart-contracts/listing_99_03/src/lib.cairo` line 130 at r5](https://reviewable.io/reviews/cairo-book/cairo-book/672#-Nt1Kfby8porRO527IMm:-Nt1Kfby8porRO527IMn:b-377nu3) ([raw file](https://github.com/cairo-book/cairo-book/blob/7b573ba6a793d601f54f7a55f33d12de6c850793/listings/ch99-starknet-smart-contracts/listing_99_03/src/lib.cairo#L130)):*
> ```Cairo
>     //ANCHOR_END: standalone
> 
>     // Free function
> ```

Even if it's not used, I think we can keep it like this
___
*[`src/ch12-02-anatomy-of-a-simple-contract.md` line 74 at r5](https://reviewable.io/reviews/cairo-book/cairo-book/672#-Nt1FwSq45L1CQ0iZCoH:-Nt1FwSq45L1CQ0iZCoI:b8b81bg) ([raw file](https://github.com/cairo-book/cairo-book/blob/7b573ba6a793d601f54f7a55f33d12de6c850793/src/ch12-02-anatomy-of-a-simple-contract.md#L74)):*
> ```Markdown
> - What we call an _external_ function is a public function that can be directly invoked through a Starknet transaction and that can mutate the state of the contract. `set` is an external function.
> 
> - A _view_ function is a public read-only function that cannot mutate the state of the contract. `get` is a view function.
> ```

I gave this a second thought: if you send an INVOKE transaction to a _view_ entrypoint, you can still bypass the compiler limitations and modify the state of the contract (it was one of NG challenges, I believe.)

Thus, I think we shouldn't mention this: wdyt of this;

A _view_ function is a public function that is typically read-only and cannot mutate the state of the contract. However, this limitation is only enforced by the compiler, and not by Starknet itself. We will discuss the implications of this in a later section. `get` is a view function.



_Code quote:_
```Markdown
that cannot mutate the state of the contract
```
___
*[`src/ch12-02-anatomy-of-a-simple-contract.md` line 89 at r5](https://reviewable.io/reviews/cairo-book/cairo-book/672#-Nt1JummAJ5hAdlMtuxr:-Nt1JummAJ5hAdlMtuxs:buabhwz) ([raw file](https://github.com/cairo-book/cairo-book/blob/7b573ba6a793d601f54f7a55f33d12de6c850793/src/ch12-02-anatomy-of-a-simple-contract.md#L89)):*
> ```Markdown
> Because the `SimpleStorage` contract is defined as a module, we need to access the interface defined in the parent module. We can either bring it to the current scope with the `use` keyword, or refer to it directly using `super`.
> 
> When writing the implementation of an interface, the `self` parameter in the trait methods must be of type `ContractState`. The `ContractState` type is generated by the compiler, and gives access to the storage variables defined in the `Storage` struct.
> ```

I propose to mark it in bold :D



_Suggestion:_
```Markdown
methods **must** be of type `ContractState`
```
___
*[`src/ch13-02-contract-functions.md` line 54 at r5](https://reviewable.io/reviews/cairo-book/cairo-book/672#-Nt1KUfc5WJd6QnQ6xUU:-Nt1KUfc5WJd6QnQ6xUV:bevi6jt) ([raw file](https://github.com/cairo-book/cairo-book/blob/7b573ba6a793d601f54f7a55f33d12de6c850793/src/ch13-02-contract-functions.md#L54)):*
> ```Markdown
> 
> ```rust,noplayground
> {{#include ../listings/ch99-starknet-smart-contracts/listing_99_03/src/lib.cairo:standalone}}
> ```

I would move the standalone free function before the internalTrait and private free function so that everything is defined in order


<!-- Sent from Reviewable.io -->

2024-03-15 14:23 UTC, TAdev0 reviewed
> *[Reviewable](https://reviewable.io/reviews/cairo-book/cairo-book/672)* status: 5 of 9 files reviewed, 6 unresolved discussions (waiting on @enitrat)

___
*[`listings/ch99-starknet-smart-contracts/listing_99_03/src/lib.cairo` line 130 at r5](https://reviewable.io/reviews/cairo-book/cairo-book/672#-Nt1Kfby8porRO527IMm:-Nt1Rvbr55EWYPiBp370:b2ni9b4) ([raw file](https://github.com/cairo-book/cairo-book/blob/7b573ba6a793d601f54f7a55f33d12de6c850793/listings/ch99-starknet-smart-contracts/listing_99_03/src/lib.cairo#L130)):*
<details><summary><i>Previously, enitrat (Mathieu) wrote…</i></summary><blockquote>

Even if it's not used, I think we can keep it like this
</blockquote></details>

ok!
___
*[`src/ch12-02-anatomy-of-a-simple-contract.md` line 74 at r5](https://reviewable.io/reviews/cairo-book/cairo-book/672#-Nt1FwSq45L1CQ0iZCoH:-Nt1SBHH5d05jUCF4_za:b-a3sndy) ([raw file](https://github.com/cairo-book/cairo-book/blob/7b573ba6a793d601f54f7a55f33d12de6c850793/src/ch12-02-anatomy-of-a-simple-contract.md#L74)):*
<details><summary><i>Previously, enitrat (Mathieu) wrote…</i></summary><blockquote>

I gave this a second thought: if you send an INVOKE transaction to a _view_ entrypoint, you can still bypass the compiler limitations and modify the state of the contract (it was one of NG challenges, I believe.)

Thus, I think we shouldn't mention this: wdyt of this;

A _view_ function is a public function that is typically read-only and cannot mutate the state of the contract. However, this limitation is only enforced by the compiler, and not by Starknet itself. We will discuss the implications of this in a later section. `get` is a view function.
</blockquote></details>

nice!

yeah if you think of stealing souls quest, we were supposed to directly call _validate_ function of a smart contract wallet through an invoke tx, to mutate the state and be able to successfully call _execute_ after that
___
*[`src/ch12-02-anatomy-of-a-simple-contract.md` line 89 at r5](https://reviewable.io/reviews/cairo-book/cairo-book/672#-Nt1JummAJ5hAdlMtuxr:-Nt1SP7D06-J3AQrmMbk:b-7rl0jq) ([raw file](https://github.com/cairo-book/cairo-book/blob/7b573ba6a793d601f54f7a55f33d12de6c850793/src/ch12-02-anatomy-of-a-simple-contract.md#L89)):*
<details><summary><i>Previously, enitrat (Mathieu) wrote…</i></summary><blockquote>

I propose to mark it in bold :D
</blockquote></details>

done!
___
*[`src/ch13-02-contract-functions.md` line 54 at r5](https://reviewable.io/reviews/cairo-book/cairo-book/672#-Nt1KUfc5WJd6QnQ6xUU:-Nt1UcjiEkNrxNIz6-pH:b-pqov82) ([raw file](https://github.com/cairo-book/cairo-book/blob/7b573ba6a793d601f54f7a55f33d12de6c850793/src/ch13-02-contract-functions.md#L54)):*
<details><summary><i>Previously, enitrat (Mathieu) wrote…</i></summary><blockquote>

I would move the standalone free function before the internalTrait and private free function so that everything is defined in order
</blockquote></details>

makes sense


<!-- Sent from Reviewable.io -->

2024-03-15 14:53 UTC, enitrat approved these changes
> Reviewed 2 of 6 files at r4, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cairo-book/cairo-book/672)* status: all files reviewed, 1 unresolved discussion (waiting on @TAdev0)



<!-- Sent from Reviewable.io -->

2024-03-15 14:54 UTC, merged