Listing reorg
cairo-book/cairo-book pull request #685
Opened 2024-03-19 16:47 UTC by TAdev0

2024-03-19 17:41 UTC, TAdev0 commented
@enitrat  ready for review

this concerns chapter 1 to 7.

Will do others in another PR.

2024-03-19 17:48 UTC, TAdev0 commented
Also updated `find_value_iterative` function in Enum chapter to use while let now it is available

2024-03-19 19:02 UTC, enitrat commented
> 
Also updated find_value_iterative function in Enum chapter to use while let now it is available

2024-03-19 19:18 UTC, TAdev0 commented
No

2024-03-20 12:17 UTC, enitrat approved these changes
I don't think this should have been done for every single one, it doesn't really matter if there's an off-by-one count in the name of the listing file being referred in the book. The only important thing was that they lived in the correct chapters

2024-03-20 12:27 UTC, enitrat requested changes

2024-03-20 12:27 UTC, enitrat commented on src/ch02-03-functions.md
> -{{#label fn-main}}
restore this listing

2024-03-20 12:55 UTC, TAdev0 commented on src/ch02-03-functions.md
> -{{#label fn-main}}
done

2024-03-20 12:57 UTC, merged