cairo-documentation-style-guide issue # 717
cairo-book/cairo-book pull request #720
Opened 2024-04-05 21:02 UTC by stevencartavia

Style guide for contributions. 
The style guide was adapted from https://github.com/esp-rs/book/blob/main/rust-doc-style-guide.md

2024-04-07 11:18 UTC, TAdev0 requested changes
Hi @stevencartavia  thanks for the PR. It needs to be reworked as it currently feels like a pure copy paste of the rust documentation, with many references to rust still present. Adapt it to the reality of the cairo book as it is currently :)

2024-04-07 11:18 UTC, TAdev0 commented on cairo-documentation-style-guide.md
> +### Adding Links
for links, we don't do that i think you can remove it.

we only do formatting with  [link] (path)  (without space)

2024-04-07 11:18 UTC, TAdev0 commented on cairo-documentation-style-guide.md
> +[The Rust Programming Language](https://github.com/rust-lang-ja/book-ja/blob/master-ja/style-guide.md) book also suggests:
remove this line

2024-04-07 11:18 UTC, TAdev0 commented on cairo-documentation-style-guide.md
> +  > `scarb` might have a section in a book and a github repo. In this case, see the [`espup`](https://book.cairo-lang.org/ch01-01-installation.html) section and [`scarb` repo](https://github.com/soft
installation section, not espup for the cairo book

2024-04-07 11:18 UTC, TAdev0 commented on cairo-documentation-style-guide.md
> +- **Numbered list** -- use it if the order of items is important, such as when describing a process
i dont think we ever used numbered list in the book

2024-04-07 11:18 UTC, TAdev0 commented on cairo-documentation-style-guide.md
> +- Finish an introductory sentence with a colon.
mmh we very often end each sentence with a point, not a colon.

2024-04-07 11:18 UTC, TAdev0 commented on cairo-documentation-style-guide.md
> +  > Using C or C++ inside of a Rust project consists of two major parts:
this has nothing to do with the cairo book

2024-04-07 11:18 UTC, TAdev0 commented on cairo-documentation-style-guide.md
> +  - For PowerShell-specific examples, use `>` instead of `$`
we dont have any powerhsell specific example

2024-04-07 11:18 UTC, TAdev0 commented on cairo-documentation-style-guide.md
> +- Images and containers: `idf-rust`
we dont use that in the book

2024-04-07 11:18 UTC, TAdev0 commented on cairo-documentation-style-guide.md
> +  > [`String`](https://doc.rust-lang.org/std/string/struct.String.html) is a string type provided by ...
rust link, should be a cairo book link

2024-04-07 11:18 UTC, TAdev0 commented on cairo-documentation-style-guide.md
> +  > [`String`](https://doc.rust-lang.org/std/string/struct.String.html) is a string type provided by ...
actually we use monospace for important information, notes, and stuff like that, not headings nor links i think

2024-04-07 11:18 UTC, TAdev0 commented on cairo-documentation-style-guide.md
> +## Appendix A Existing Style Guides
no appendix to add in this ''chapter''

2024-04-07 15:29 UTC, enitrat commented on cairo-documentation-style-guide.md
> +### Adding Links
I think we should do that tbh

2024-04-08 09:17 UTC, TAdev0 commented on cairo-documentation-style-guide.md
> +### Adding Links
ok! it would be better, for sure. @stevencartavia  if you want to open another issue to do this for all links in the book (or only start with a few chapter), feel free :)

2024-04-08 09:17 UTC, TAdev0 commented on cairo-documentation-style-guide.md
> +- **Numbered list** -- use it if the order of items is important, such as when describing a process
@stevencartavia  actually we do for the new Randomness chapter, you can leave it !

2024-04-08 13:07 UTC, enitrat commented on cairo-documentation-style-guide.md
> +  -  For an example using monospace font, see the [Panicking](https://docs.rust-embedded.org/book/start/panicking.html#panicking) section in The Embedded Rust Book.
```suggestion
  -  For an example using monospace font, see the [Appendix A](https://book.cairo-lang.org/appendix-01-keywords.html#strict-keywords) section in The Cairo Book.
```

2024-04-08 13:07 UTC, enitrat commented on cairo-documentation-style-guide.md
> +  [The Rust Programming Language](https://github.com/rust-lang-ja/book-ja/blob/master-ja/style-guide.md) book also suggests:
```suggestion
  - Start the terminal commands with $
  - Output of previous commands should not start with $
```

2024-04-08 13:07 UTC, enitrat commented on cairo-documentation-style-guide.md
> +
missing

Names of crates, traits, libraries,

Command line tools, plugins, packages

2024-04-08 13:07 UTC, enitrat commented on cairo-documentation-style-guide.md
> +  > **Serializing with `Serde`**
repetition

2024-04-08 13:42 UTC, enitrat commented on cairo-documentation-style-guide.md
> +### Adding Links
@TAdev0 I think this can be made gradually, no need to change everything all at once. Just keep things cleaner than you found them every time a page is modified

2024-04-09 17:35 UTC, enitrat approved these changes

2024-04-10 14:05 UTC, merged