feat: pragma randomness
cairo-book/cairo-book pull request #721
Opened 2024-04-06 06:41 UTC by okhaimie-dev

https://github.com/cairo-book/cairo-book/issues/554

2024-04-06 12:21 UTC, TAdev0 commented
@okhaimie-dev  great thanks! will review later today

2024-04-07 09:40 UTC, TAdev0 requested changes

2024-04-07 09:40 UTC, TAdev0 commented on src/ch16-05-02-randomness.md
> +```rust,noplayground
place the code after the text below

2024-04-07 09:40 UTC, TAdev0 commented on listings/ch16-building-advanced-starknet-smart-contracts/listing_06_pragma_randomness/src/lib.cairo
> +            return last_random;
instead of `return last_random;`, you can skip a line and simple use the expression `last_random` with semicolon

2024-04-07 09:40 UTC, TAdev0 commented on listings/ch16-building-advanced-starknet-smart-contracts/listing_06_pragma_randomness/src/lib.cairo
> +    use starknet::info::{get_block_number, get_caller_address, get_contract_address};
this doesn't compile with edition 2023_11 because of visibility issue

The right path is :

    `use starknet::{get_block_number, get_caller_address, get_contract_address};`

2024-04-07 09:40 UTC, TAdev0 commented on listings/ch16-building-advanced-starknet-smart-contracts/listing_06_pragma_randomness/src/lib.cairo
> +                contract_address: 0x049d36570d4e46f48e99674bd3fcc84644ddd6b96f7c741b1562b82f9e004dc7 // ETH Contract Address
you can use : 

```
starknet::contract_address_const::<0x049d36570d4e46f48e99674bd3fcc84644ddd6b96f7c741b1562b82f9e004dc7>()
```

2024-04-07 09:40 UTC, TAdev0 commented on listings/ch16-building-advanced-starknet-smart-contracts/listing_06_pragma_randomness/src/lib.cairo
> +                    (callback_fee_limit + callback_fee_limit / 5).into()
does this  come from Pragma?

2024-04-07 09:40 UTC, TAdev0 commented on listings/ch16-building-advanced-starknet-smart-contracts/listing_06_pragma_randomness/src/lib.cairo
> +            return ();
remove this line, it is not necessary to explicitly return the unit type, it is returned by default when there is no return value

2024-04-07 09:40 UTC, TAdev0 commented on src/ch16-05-02-randomness.md
> +2. `callback_address`: The contract address where the receive_random_words function will be called to deliver the generated randomness. It is typically the address of your deployed contract implement
`receive_random_words` with `

2024-04-07 09:40 UTC, TAdev0 commented on src/ch16-05-02-randomness.md
> +3. `callback_fee_limit`: The maximum amount of gas you're willing to spend on executing the receive_random_words callback function.
same

2024-04-07 09:40 UTC, TAdev0 commented on src/ch16-05-02-randomness.md
> +5. `num_words`: The number of random values (each represented as a felt252) you want to receive in a single callback.
same for felt252, use `

2024-04-07 09:40 UTC, TAdev0 commented on src/ch16-05-02-randomness.md
> +6. `calldata`: Additional data you want to pass to the receive_random_words callback function. This could be used for context or to customize the behavior of that function.
same

2024-04-07 09:40 UTC, TAdev0 commented on src/ch16-05-02-randomness.md
> +
Explain shortly other functions of the interface before sending the whole contract

2024-04-07 09:40 UTC, TAdev0 commented on src/ch16-05-02-randomness.md
> +Listing {{#ref pragma_vrf_contract}} shows a basic implementation of a randomness contract using Pragma VRF:
of a randomness contract implementing the previous interface, and remove ''using pragma vrf''

2024-04-07 09:40 UTC, TAdev0 commented on src/ch16-05-02-randomness.md
> +Once contract is deployed, you need to send enough ETH to the deployed contract address required to cover gas cost of callback function and cost of generating randomness.
Suggestion:

Once your contract is deployed, it needs to hold enough ETH in order to use Pragma VRF system. Indeed,  requesting random values implies to pay the cost forthe random generation process and the callback function. 

I think my suggestion is not perfect but this is just an idea

2024-04-07 09:40 UTC, TAdev0 commented on src/ch16-05-02-randomness.md
> +For more information, refer to the [Pragma](https://docs.pragma.build/Resources/Cairo%201/randomness/randomness) docs.
please refer*

2024-04-07 12:43 UTC, okhaimie-dev commented on src/ch16-05-02-randomness.md
> +6. `calldata`: Additional data you want to pass to the receive_random_words callback function. This could be used for context or to customize the behavior of that function.
what do you mean by same here?

2024-04-07 12:44 UTC, okhaimie-dev commented on src/ch16-05-02-randomness.md
> +
alright, I'll do this

2024-04-07 12:45 UTC, okhaimie-dev commented on src/ch16-05-02-randomness.md
> +Once contract is deployed, you need to send enough ETH to the deployed contract address required to cover gas cost of callback function and cost of generating randomness.
alright. i'll edit and improve on it

2024-04-07 20:10 UTC, okhaimie-dev commented on src/ch16-05-02-randomness.md
> +If we need to generate randomness on the blockchain, it has to be done in a secure manner to ensure that the result cannot be predicted or manipulated. A common way to achieve this is to use verifiab
Reading now. I'll make an update in a bit

2024-04-08 00:28 UTC, okhaimie-dev commented on src/ch16-05-02-randomness.md
> +
So I didn't explain the
`get_last_random` function because it is just a getter function to read the `last_random` generated.
`withdraw_funds` function because it is an optional function used by contract admin to withdraw the funds sent to be used by the `receive_random_words` callback function

if you still want it in the book, i will go ahead and add these two functions

2024-04-08 01:47 UTC, okhaimie-dev commented on listings/ch16-building-advanced-starknet-smart-contracts/listing_06_pragma_randomness/src/lib.cairo
> +                    (callback_fee_limit + callback_fee_limit / 5).into()
this is a clearer version of the expression `(callback_fee_limit + (callback_fee_limit / 5)).into()`

and yes, i found out that this is a safe value that works. just the `callback_fee_limit` alone returns an error

2024-04-08 09:12 UTC, TAdev0 requested changes

2024-04-08 09:12 UTC, TAdev0 commented on listings/ch16-building-advanced-starknet-smart-contracts/listing_06_pragma_randomness/src/lib.cairo
> +
here just remove empty line 19 and its good

2024-04-08 09:12 UTC, TAdev0 commented on listings/ch16-building-advanced-starknet-smart-contracts/listing_06_pragma_randomness/src/lib.cairo
> +                contract_address: 0x049d36570d4e46f48e99674bd3fcc84644ddd6b96f7c741b1562b82f9e004dc7 // ETH Contract Address
@okhaimie-dev  instead of doing try_into and unwrap to convert a felt252 in a contractAddress type, use `contract_address_const` from corelib, i guess it saves steps

2024-04-08 09:12 UTC, TAdev0 commented on listings/ch16-building-advanced-starknet-smart-contracts/listing_06_pragma_randomness/src/lib.cairo
> +                    (callback_fee_limit + (callback_fee_limit / 5)).into()
you dont need the parenthesis as the division will be executed before the addition anyway

2024-04-08 09:12 UTC, TAdev0 commented on listings/ch16-building-advanced-starknet-smart-contracts/listing_06_pragma_randomness/src/lib.cairo
> +            // Your code using randomness!
you can remove this line i think

2024-04-08 09:12 UTC, TAdev0 commented on listings/ch16-building-advanced-starknet-smart-contracts/listing_06_pragma_randomness/src/lib.cairo
> +                contract_address: 0x049d36570d4e46f48e99674bd3fcc84644ddd6b96f7c741b1562b82f9e004dc7 // ETH Contract Address
same, use `contract_address_const`

2024-04-08 09:12 UTC, TAdev0 commented on listings/ch16-building-advanced-starknet-smart-contracts/listing_06_pragma_randomness/src/lib.cairo
> +
remove empty line 189 so that there is no extra empty line in the global file

2024-04-08 09:12 UTC, TAdev0 commented on src/ch16-05-02-randomness.md
> +Since most well-know blockchains are fundamentally deterministic and public ledgers, generating truly unpredictatable randomness on-chain presents a challenge. This randomness is crucial for fair out
well-known

2024-04-08 09:12 UTC, TAdev0 commented on src/ch16-05-02-randomness.md
> +Since most well-know blockchains are fundamentally deterministic and public ledgers, generating truly unpredictatable randomness on-chain presents a challenge. This randomness is crucial for fair out
offer*

2024-04-08 09:12 UTC, TAdev0 commented on src/ch16-05-02-randomness.md
> +Verifiable output: VRFs produce not only the random number but also a proof that anyone can use to independently verify that the result was generated correctly according to the function's parameters.
nice

2024-04-08 09:12 UTC, TAdev0 commented on src/ch16-05-02-randomness.md
> +[Pragma](https://www.pragma.build/), an oracle on Starknet provides a solution for generating random numbers using VRFs.
colon after ''Starknet''

2024-04-08 09:12 UTC, TAdev0 commented on src/ch16-05-02-randomness.md
> +<span class="caption">Listing {{#ref pragma_vrf_interface}}: Simple Randomness Contract Interface</span>
add a point after ''Interface''

2024-04-08 09:12 UTC, TAdev0 commented on src/ch16-05-02-randomness.md
> +1. Randomness Generation: The Oracle generates random values and a corresponding proof.
the oracle without capital letter

2024-04-08 09:12 UTC, TAdev0 commented on src/ch16-05-02-randomness.md
> +2. On-chain Submission: The Oracle submits the generated randomness and proof back to the blockchain via the `receive_random_words` callback function.
same

2024-04-08 09:12 UTC, TAdev0 commented on src/ch16-05-02-randomness.md
> +
remove empty line in excess

2024-04-08 09:12 UTC, TAdev0 commented on src/ch16-05-02-randomness.md
> +<span class="caption">Listing {{#ref request_my_randomness}}: `request_my_randomness` function</span>
point after ''function''

2024-04-08 09:12 UTC, TAdev0 commented on src/ch16-05-02-randomness.md
> +<span class="caption">Listing {{#ref receive_random_words}}: `receive_random_word` function</span>
same, point after ''function''

2024-04-08 09:12 UTC, TAdev0 commented on src/ch16-05-02-randomness.md
> +
@enitrat  what do you think?

2024-04-08 09:12 UTC, TAdev0 commented on src/ch16-05-02-randomness.md
> +After deploying your contract, ensure it holds sufficient ETH to use the Pragma VRF system. Requesting random values incurs costs associated with both the generation process and the execution of your
nice

2024-04-08 12:07 UTC, okhaimie-dev commented on src/ch16-05-02-randomness.md
> +Since most well-know blockchains are fundamentally deterministic and public ledgers, generating truly unpredictatable randomness on-chain presents a challenge. This randomness is crucial for fair out
i took out the "well-know". 

> Since most blockchains

still conveys the message

2024-04-08 12:42 UTC, TAdev0 commented on src/ch16-05-02-randomness.md
> +Since most well-know blockchains are fundamentally deterministic and public ledgers, generating truly unpredictatable randomness on-chain presents a challenge. This randomness is crucial for fair out
Actually all blockchain systems or any computer is deterministic , and most of them are public ledgers

2024-04-08 13:12 UTC, okhaimie-dev commented on listings/ch16-building-advanced-starknet-smart-contracts/listing_06_pragma_randomness/src/lib.cairo
> +
done

2024-04-09 14:26 UTC, TAdev0 requested changes

2024-04-09 14:26 UTC, TAdev0 commented on listings/ch16-building-advanced-starknet-smart-contracts/listing_06_pragma_randomness/src/lib.cairo
> +            let _request_id = randomness_dispatcher
Unused local variable ?

2024-04-09 14:26 UTC, TAdev0 commented on listings/ch16-building-advanced-starknet-smart-contracts/listing_06_pragma_randomness/src/lib.cairo
> +            let _compute_fees = randomness_dispatcher.compute_premium_fee(caller);
Remove underscore before compute

2024-04-09 15:55 UTC, enitrat requested changes
I would like to see a more specific usage of randomness in an application rather than a contract that doesn't have a real purpose. 

How about implementing a simple ERC20-faucet dice game where the user can call an entrypoint with a number between 1 and 6, we store the user's input and request randomness, and when we receive a response in the randomness callback, we distribute 1 token to each user that guessed the right number ?

That would be a better guide on how to integrate randomness with a raffle game. 

> Reviewed 1 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cairo-book/cairo-book/721#-:-Nv2XQNzCQk7aHzWEokH:b-cs5ev5)* status: 1 of 5 files reviewed, 45 unresolved discussions (waiting on @okhaimie-dev and @TAdev0)

___
*[`listings/ch16-building-advanced-starknet-smart-contracts/listing_06_pragma_randomness/src/lib.cairo` line 94 at r1](https://reviewable.io/reviews/cairo-book/cairo-book/721#gh-1554854721:-Nv2VEhv-Kq7Pya5-xkX:bsluw1g) ([raw file](https://github.com/cairo-book/cairo-book/blob/b583a4a4adaba81e7ca38e1597e0f168f4f6f6dd/listings/ch16-building-advanced-starknet-smart-contracts/listing_06_pragma_randomness/src/lib.cairo#L94)):*
<details><summary><i>Previously, TAdev0 (Tristan) wrote…</i></summary><blockquote>

instead of `return last_random;`, you can skip a line and simple use the expression `last_random` with semicolon
</blockquote></details>

simply `self.last_random_storage.read()` 
___
*[`listings/ch16-building-advanced-starknet-smart-contracts/listing_06_pragma_randomness/src/lib.cairo` line 124 at r1](https://reviewable.io/reviews/cairo-book/cairo-book/721#gh-1554856626:-Nv2ViPKA0qcpDV1Y4fz:bkf895d) ([raw file](https://github.com/cairo-book/cairo-book/blob/b583a4a4adaba81e7ca38e1597e0f168f4f6f6dd/listings/ch16-building-advanced-starknet-smart-contracts/listing_06_pragma_randomness/src/lib.cairo#L124)):*
<details><summary><i>Previously, okhaimie-dev (okhai.stark ( Tony Stark )) wrote…</i></summary><blockquote>

this is a clearer version of the expression `(callback_fee_limit + (callback_fee_limit / 5)).into()`

and yes, i found out that this in one of their example code. i also found it to be a safe value for approval
</blockquote></details>

it comes a bit out of nowhere, it's hard to follow along
___
*[`listings/ch16-building-advanced-starknet-smart-contracts/listing_06_pragma_randomness/src/lib.cairo` line 34 at r6](https://reviewable.io/reviews/cairo-book/cairo-book/721#-Nv2VufKEWqpX00BI-TS:-Nv2VufLCxDI78KElvyn:bibj1nw) ([raw file](https://github.com/cairo-book/cairo-book/blob/27051648a2042bba33b46d002774d4c177be560e/listings/ch16-building-advanced-starknet-smart-contracts/listing_06_pragma_randomness/src/lib.cairo#L34)):*
> ```Cairo
> }
> //ANCHOR_END: randomness_interface
> ```

Where is the interface of the Pragma contract? Is it the same as the IRandomness contract you're implementing? it's not very clear what we're requesting random numbers for
___
*[`listings/ch16-building-advanced-starknet-smart-contracts/listing_06_pragma_randomness/src/lib.cairo` line 37 at r6](https://reviewable.io/reviews/cairo-book/cairo-book/721#-Nv2Uygv68tzhXph7Mr8:-Nv2Uygv68tzhXph7Mr9:bdkfmct) ([raw file](https://github.com/cairo-book/cairo-book/blob/27051648a2042bba33b46d002774d4c177be560e/listings/ch16-building-advanced-starknet-smart-contracts/listing_06_pragma_randomness/src/lib.cairo#L37)):*
> ```Cairo
> //ANCHOR: randomness_contract
> #[starknet::contract]
> mod Randomness {
> ```

It is not clear what this contract actually does from the name. I see it's called `Randomness`-  but it somehow interacts with tokens, so it must have an applicative value? The reader should know what the contract does by reading its name and the functions in the interface.
___
*[`listings/ch16-building-advanced-starknet-smart-contracts/listing_06_pragma_randomness/src/lib.cairo` line 61 at r6](https://reviewable.io/reviews/cairo-book/cairo-book/721#-Nv2UmUP09-Web0fOikZ:-Nv2UmUP09-Web0fOik_:brmfcya) ([raw file](https://github.com/cairo-book/cairo-book/blob/27051648a2042bba33b46d002774d4c177be560e/listings/ch16-building-advanced-starknet-smart-contracts/listing_06_pragma_randomness/src/lib.cairo#L61)):*
> ```Cairo
>     // SRC5
>     #[abi(embed_v0)]
>     impl SRC5Impl = SRC5Component::SRC5Impl<ContractState>;
> ```

What is this for? I don't think it is needed
___
*[`listings/ch16-building-advanced-starknet-smart-contracts/listing_06_pragma_randomness/src/lib.cairo` line 113 at r6](https://reviewable.io/reviews/cairo-book/cairo-book/721#-Nv2VJRT9UTBRVYJXa2w:-Nv2VJRT9UTBRVYJXa2x:b-sf7yq8) ([raw file](https://github.com/cairo-book/cairo-book/blob/27051648a2042bba33b46d002774d4c177be560e/listings/ch16-building-advanced-starknet-smart-contracts/listing_06_pragma_randomness/src/lib.cairo#L113)):*
> ```Cairo
>             calldata: Array<felt252>
>         ) {
>             let randomness_contract_address = self.randomness_contract_address.read();
> ```

is this Pragma VRF? It should be named as such. It's confusing, I don't know what this refers to when I read this contract. Your contract is also named randomness
___
*[`listings/ch16-building-advanced-starknet-smart-contracts/listing_06_pragma_randomness/src/lib.cairo` line 114 at r6](https://reviewable.io/reviews/cairo-book/cairo-book/721#-Nv2VQhEC2cJtmsCI1Vz:-Nv2VQhEC2cJtmsCI1W-:bgnt9im) ([raw file](https://github.com/cairo-book/cairo-book/blob/27051648a2042bba33b46d002774d4c177be560e/listings/ch16-building-advanced-starknet-smart-contracts/listing_06_pragma_randomness/src/lib.cairo#L114)):*
> ```Cairo
>         ) {
>             let randomness_contract_address = self.randomness_contract_address.read();
>             let randomness_dispatcher = IRandomnessDispatcher {
> ```

can be merged with the line above
___
*[`src/ch16-05-02-randomness.md` line 14 at r5](https://reviewable.io/reviews/cairo-book/cairo-book/721#gh-1556423958:-Nv2WMGP6jebHrw01qsd:b-mftzmj) ([raw file](https://github.com/cairo-book/cairo-book/blob/c43ab96c1cab85cf3579af5423a59238336fe049/src/ch16-05-02-randomness.md#L14)):*
<details><summary><i>Previously, TAdev0 (Tristan) wrote…</i></summary><blockquote>

I think we should modify the flow for titles, maybe something like this? :
```
## Overview on VRFs

## Example of a Randomness Contract (maybe not ideal though)
precise here that our example will use Pragma, the most used oracle on starknet
and then 

### Add Pragma as a Dependency

### Interface 

### Description of Entrypoints and their inputs

### Contract Example -  (full implementation)

Because currently, the flow is:
## Overview on VRFs
## Add Pragma as a Dependency
### `request_my_randomness` Inputs
### `receive_randomn_words` Inputs
## Example Randomness Contract
### NB: After Contract is Deployed

and its not logic 

```
</blockquote></details>

there is an issue with the current flow of the chapter: it should be implemented as a follow-along implementation of writing a contract that uses Pragma VRF, but in the current state it's hard to actually understand what's going on.

@TAdev0 even your proposal remains purely descriptive and not informative enough. 

When you write a contract, you
- Describe your use case and application
- Think about what will be exposed to the outside world, and how (view / external)

Then you start writing the code
- Create your project with the right dependencies and file structure
- Write the interface of your contract
- Implement your interface, feature by feature

Step by step, gradually.


<!-- Sent from Reviewable.io -->

2024-04-09 17:06 UTC, okhaimie-dev commented
> is this Pragma VRF? It should be named as such. It's confusing, I don't know what this refers to when I read this contract. Your contract is also named randomness

it is the pragma randomness contract address. I will make the variable names more descriptive in my next commit using the new example you suggested

2024-04-17 13:54 UTC, enitrat commented
Hey @okhaimie-dev are you going to revise this? Do you need any help?

2024-04-22 05:03 UTC, okhaimie-dev commented
@enitrat 

I'll complete it this week. I'll reach out if I need further assistance MAX by Wednesday

2024-04-30 03:41 UTC, okhaimie-dev commented
I am still working on the Dice game example.
https://github.com/okhaimie-dev/dice-game

I will used this to replace the initial example I've got in a bit

2024-05-05 17:33 UTC, enitrat commented
Closing this, you can reopen a new one when you're ready

2024-05-05 17:33 UTC, closed without merging