feat: add examples of smart contract testing
cairo-book/cairo-book pull request #754
Opened 2024-05-02 00:46 UTC by FriendlyLifeguard

Closes #416 

Hello, I have pushed an initial draft of cairo contract testing section written in both native test runner and starknet foundry. 

Please let me know whether it needs more detailed contract testing as well as the flow of the overall documentation.

2024-05-02 09:05 UTC, enitrat requested changes
Thank you for the PR!

I will give a more in-depth review once the first comments are addressed, mostly about form rather than content for now.

1. Make sure to not have any cairo code directly inside the markdown file: it must come from a cairo file, and included in the cairo file using `{{#include path/to/file}}`, with an optional `:anchor` if you want to isolate a specific snipper

2. As you're demonstrating the use of two different test runners that are not compatible, you might need to create two packages, one for cairo-test, and one for snfoundry. Don't forget to give specific instructions, the user must be able to follow along (e.g. create  `pizzeria_cairo_test` and `pizzeria_snfoundry_test` directories, etc.)

> Reviewed 2 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cairo-book/cairo-book/754#-:-NwsXX4W-cKUMfLjHIYJ:b-1w2zio)* status: 2 of 5 files reviewed, 8 unresolved discussions (waiting on @FriendlyLifeguard)

___
*[`listings/ch17-starknet-smart-contracts-security/listing_02_pizza_factory/Scarb.toml` line 9 at r1](https://reviewable.io/reviews/cairo-book/cairo-book/754#-NwsUjwW9mNSWKYMuluF:-NwsUjwW9mNSWKYMuluG:b-j7jmmd) ([raw file](https://github.com/cairo-book/cairo-book/blob/93367079e5b85b301bdd5b58f2342a1cedebaa10/listings/ch17-starknet-smart-contracts-security/listing_02_pizza_factory/Scarb.toml#L9)):*
>=2.6.3
___
*[`listings/ch17-starknet-smart-contracts-security/listing_02_pizza_factory/src/lib.cairo` line 19 at r1](https://reviewable.io/reviews/cairo-book/cairo-book/754#-NwsUoc587Yy-iDxb8qX:-NwsUoc587Yy-iDxb8qY:b6hiadv) ([raw file](https://github.com/cairo-book/cairo-book/blob/93367079e5b85b301bdd5b58f2342a1cedebaa10/listings/ch17-starknet-smart-contracts-security/listing_02_pizza_factory/src/lib.cairo#L19)):*
> ```Cairo
>     #[storage]
>     struct Storage {
>         pepperoni: felt252,
> ```

should use integers instead. what would the max amount of pepperoni be? probably something <=255. Overall, remove all uses of `felt252` and use appropriate integer sizes.



_Suggestion:_
```Cairo
u8
```
___
*[`listings/ch17-starknet-smart-contracts-security/listing_02_pizza_factory/src/lib.cairo` line 20 at r1](https://reviewable.io/reviews/cairo-book/cairo-book/754#-NwsUwA31rW2IvhCE1Om:-NwsUwA31rW2IvhCE1On:bb7od0r) ([raw file](https://github.com/cairo-book/cairo-book/blob/93367079e5b85b301bdd5b58f2342a1cedebaa10/listings/ch17-starknet-smart-contracts-security/listing_02_pizza_factory/src/lib.cairo#L20)):*
> ```Cairo
>     struct Storage {
>         pepperoni: felt252,
>         pineapple: felt252,
> ```

same
___
*[`listings/ch17-starknet-smart-contracts-security/listing_02_pizza_factory/src/lib.cairo` line 26 at r1](https://reviewable.io/reviews/cairo-book/cairo-book/754#-NwsUx5m3Ll3r7Rz6RkK:-NwsUx5m3Ll3r7Rz6RkL:b45gzwk) ([raw file](https://github.com/cairo-book/cairo-book/blob/93367079e5b85b301bdd5b58f2342a1cedebaa10/listings/ch17-starknet-smart-contracts-security/listing_02_pizza_factory/src/lib.cairo#L26)):*
> ```Cairo
>     #[constructor]
>     fn constructor(ref self: ContractState, owner: ContractAddress) {
>         self.pepperoni.write(0);
> ```

This is useless as the base state is zero
___
*[`src/ch17-02-testing-smart-contracts.md` line 10 at r1](https://reviewable.io/reviews/cairo-book/cairo-book/754#-NwsVBgp6IE9dKEi_PgE:-NwsVBgp6IE9dKEi_PgF:bqoj8c3) ([raw file](https://github.com/cairo-book/cairo-book/blob/93367079e5b85b301bdd5b58f2342a1cedebaa10/src/ch17-02-testing-smart-contracts.md#L10)):*
> ```Markdown
> 
> ```rust
> use starknet::ContractAddress;
> ```

All code examples must be references to `.cairo` files, included in the markdown with the {{#include path/to/file}} attribute
___
*[`src/ch17-02-testing-smart-contracts.md` line 13 at r1](https://reviewable.io/reviews/cairo-book/cairo-book/754#-NwsVT5Y5wxXoPVIS6Tt:-NwsVT5Y5wxXoPVIS6Tu:bn61izz) ([raw file](https://github.com/cairo-book/cairo-book/blob/93367079e5b85b301bdd5b58f2342a1cedebaa10/src/ch17-02-testing-smart-contracts.md#L13)):*
> ```Markdown
> 
> #[starknet::interface]
> pub trait IPizzaFactory<TContractState> {
> ```

this doesn't match the content of the .cairo file. Which one is the correct one?
___
*[`src/ch17-02-testing-smart-contracts.md` line 108 at r1](https://reviewable.io/reviews/cairo-book/cairo-book/754#-NwsVZrF9PXY25TBXd6X:-NwsVZrF9PXY25TBXd6Y:b-9wkxa4) ([raw file](https://github.com/cairo-book/cairo-book/blob/93367079e5b85b301bdd5b58f2342a1cedebaa10/src/ch17-02-testing-smart-contracts.md#L108)):*
> ```Markdown
> ```
> 
> We will first start with Native Test Runner.
> ```

First, there should be an introduction on how to choose a testing framework appropriately, with an exhaustive list of the features.
___
*[`src/ch17-02-testing-smart-contracts.md` line 125 at r1](https://reviewable.io/reviews/cairo-book/cairo-book/754#-NwsVl-c9mMEyvvjPY7_:-NwsVl-c9mMEyvvjPY7a:b-6ur8lb) ([raw file](https://github.com/cairo-book/cairo-book/blob/93367079e5b85b301bdd5b58f2342a1cedebaa10/src/ch17-02-testing-smart-contracts.md#L125)):*
> ```Markdown
> 
> ```rust
> #[test]
> ```

the tests can also be inside .cairo files. You can structure the cairo project as you would in any other place, and then just refer to individual files, and specific lines inside these files, using the include and anchor mechanism (see prev comment, and other parts of the book)


<!-- Sent from Reviewable.io -->

2024-05-06 10:42 UTC, MaksymilianDemitraszek commented on src/ch17-02-testing-smart-contracts.md
> +fn test_selector() -> felt252
Warning here, those are not stable at the moment, and we probably won't be able to update this every time we change something. Maybe it would be better to refer to starknet foundry docs instead?

2024-05-06 10:49 UTC, piotmag769 commented on src/ch17-02-testing-smart-contracts.md
> +Starknet Foundry is a new testing library that allows you to test your Cairo smart contracts with more advanced features.
This is inaccurate, we Starknet Foundry is a toolkit for developing starknet contracts - part of which is snforge which is a testing tool for starknet contracts

2024-05-06 11:14 UTC, TAdev0 requested changes

2024-05-06 11:16 UTC, TAdev0 commented on listings/ch17-starknet-smart-contracts-security/listing_02_pizza_factory/src/pizza.cairo
> +    pub impl InternalImpl of InternalTrait {
same for `PizzaFactoryimpl`

2024-05-06 11:17 UTC, TAdev0 commented on listings/ch17-starknet-smart-contracts-security/listing_02_pizza_factory/src/pizza.cairo
> +    pub impl InternalImpl of InternalTrait {
Also, most of the `pub` items should actually be `pub(crate)` . Probably all of them but the interface

2024-05-06 12:15 UTC, TAdev0 requested changes
Looks good overall! 
I made a bunch of comments, precisions in text and english flow can be improved in many places

2024-05-06 12:20 UTC, TAdev0 commented
@FriendlyLifeguard  i think there is a lack in description of SN Foundry cheatcodes overall. Tests make use of `start_prank` and `spy_events` , but thats all. I agree its hard to condensate everything. Moreover this is not a SN Foundry documentation. 
But it would be nice to add a short description of most used cheatcodes, i.e, warp, spoof, mainly

2024-05-06 13:16 UTC, piotmag769 commented
@TAdev0 imo providing a hyperlink to our docs is the best. Better to generally describe things that can be done with `snforge` (especially those that are not possible with the `cairo-test`, since this is the interesting part for users) + describe the used cheatcodes

2024-05-06 13:18 UTC, TAdev0 commented
totally agree!

2024-05-06 18:53 UTC, enitrat requested changes
> Reviewed 9 of 16 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cairo-book/cairo-book/754)* status: 10 of 18 files reviewed, 47 unresolved discussions (waiting on @FriendlyLifeguard, @MaksymilianDemitraszek, @piotmag769, and @TAdev0)

___
*[`listings/ch17-starknet-smart-contracts-security/listing_02_pizza_factory_native/src/tests/native_test.cairo` line 1 at r2](https://reviewable.io/reviews/cairo-book/cairo-book/754#-NxECxusEQbCEDPssEvh:-NxECxusEQbCEDPssEvi:b-t5wb5y) ([raw file](https://github.com/cairo-book/cairo-book/blob/fb1823b76875e4bd9b547311a5fe682c27230898/listings/ch17-starknet-smart-contracts-security/listing_02_pizza_factory_native/src/tests/native_test.cairo#L1)):*
> ```Cairo
> #[test]
> ```

I think you meant `#[cfg(test)]`
___
*[`listings/ch17-starknet-smart-contracts-security/listing_02_pizza_factory_native/src/tests/native_test.cairo` line 46 at r2](https://reviewable.io/reviews/cairo-book/cairo-book/754#-NxED9zhENMuB2q6ucAU:-NxED9zhENMuB2q6ucAV:boipsr7) ([raw file](https://github.com/cairo-book/cairo-book/blob/fb1823b76875e4bd9b547311a5fe682c27230898/listings/ch17-starknet-smart-contracts-security/listing_02_pizza_factory_native/src/tests/native_test.cairo#L46)):*
> ```Cairo
>         let new_owner = contract_address_const::<2>();
>         let contract = deploy(owner);
>         assert(contract.get_owner() == owner, 'incorrect owner');
> ```

In tests, you can write this. This allows you to get dynamic values for `contract.get_owner` and `owner`, so that if the test fails, you know what the actual values were.

(you can do this in the entire test file)



_Suggestion:_
```Cairo
assert_eq!(contract.get_owner(), owner);
```
___
*[`listings/ch17-starknet-smart-contracts-security/listing_02_pizza_factory_native/src/tests/native_test.cairo` line 56 at r2](https://reviewable.io/reviews/cairo-book/cairo-book/754#-NxEDbFGEb9AqInmAIkg:-NxEDbFGEb9AqInmAIkh:byql7ev) ([raw file](https://github.com/cairo-book/cairo-book/blob/fb1823b76875e4bd9b547311a5fe682c27230898/listings/ch17-starknet-smart-contracts-security/listing_02_pizza_factory_native/src/tests/native_test.cairo#L56)):*
> ```Cairo
>     #[test]
>     #[available_gas(20000000)]
>     fn test_pizza_creation() {
> ```

ideally, test names reflect what is being tested in the test: here, something like



_Suggestion:_
```Cairo
fn test_make_pizza_should_increase_pizza_count() {
```
___
*[`listings/ch17-starknet-smart-contracts-security/listing_02_pizza_factory_native/src/tests/native_test.cairo` line 68 at r2](https://reviewable.io/reviews/cairo-book/cairo-book/754#-NxEDkgO0MDKRJyKcwcu:-NxEDkgO0MDKRJyKcwcv:b2dvaez) ([raw file](https://github.com/cairo-book/cairo-book/blob/fb1823b76875e4bd9b547311a5fe682c27230898/listings/ch17-starknet-smart-contracts-security/listing_02_pizza_factory_native/src/tests/native_test.cairo#L68)):*
> ```Cairo
>     //ANCHOR: test_3
>     #[test]
>     #[should_panic]
> ```

you can catch the expected error message in the `#[should_panic]` attribute. When you test a _contract_, all of the error messages are displayed, so I think it would be something like `    #[should_panic(expected: ('ENTRYPOINT FAILED', ' YOUR ERROR HERE',))]` (verify the exact syntax)
___
*[`listings/ch17-starknet-smart-contracts-security/listing_02_pizza_factory_native/src/tests/native_test.cairo` line 70 at r2](https://reviewable.io/reviews/cairo-book/cairo-book/754#-NxEDgSDDDMBjZlr9tYq:-NxEDgSDDDMBjZlr9tYr:bt1pcvp) ([raw file](https://github.com/cairo-book/cairo-book/blob/fb1823b76875e4bd9b547311a5fe682c27230898/listings/ch17-starknet-smart-contracts-security/listing_02_pizza_factory_native/src/tests/native_test.cairo#L70)):*
> ```Cairo
>     #[should_panic]
>     #[available_gas(20000000)]
>     fn test_set_not_owner() {
> ```

and here, that would be



_Suggestion:_
```Cairo
fn test_make_pizza_should_fail_when_not_owner()
```
___
*[`listings/ch17-starknet-smart-contracts-security/listing_02_pizza_factory_snfoundry/src/tests/foundry_test.cairo` line 33 at r2](https://reviewable.io/reviews/cairo-book/cairo-book/754#-NxEELKW0TPHgLlthUCr:-NxEELKW0TPHgLlthUCs:b-2i1r9b) ([raw file](https://github.com/cairo-book/cairo-book/blob/fb1823b76875e4bd9b547311a5fe682c27230898/listings/ch17-starknet-smart-contracts-security/listing_02_pizza_factory_snfoundry/src/tests/foundry_test.cairo#L33)):*
> ```Cairo
>     }
> 
>     ANCHOR: test_1
> ```

missing commented lines?
___
*[`src/ch17-02-testing-smart-contracts.md` line 28 at r2](https://reviewable.io/reviews/cairo-book/cairo-book/754#gh-1590924940:-NxEEqre7npTTA2k_upm:b-mw3a7c) ([raw file](https://github.com/cairo-book/cairo-book/blob/fb1823b76875e4bd9b547311a5fe682c27230898/src/ch17-02-testing-smart-contracts.md#L28)):*
<details><summary><i>Previously, TAdev0 (Tristan) wrote…</i></summary><blockquote>

Can you add more precisions , like : 

Here is a list of test functions available in the Cairo corelib:
</blockquote></details>

Let's remove the list of functions entirely - the book is not a documentation of the core library.
___
*[`src/ch17-02-testing-smart-contracts.md` line 141 at r2](https://reviewable.io/reviews/cairo-book/cairo-book/754#-NxEF5SF6BZP9hlNcD-L:-NxEF5SF6BZP9hlNcD-M:bv9u4fz) ([raw file](https://github.com/cairo-book/cairo-book/blob/fb1823b76875e4bd9b547311a5fe682c27230898/src/ch17-02-testing-smart-contracts.md#L141)):*
> ```Markdown
> ```
> 
> List of test functions: 
> ```

Same, remove the list of functions - the aim of the book is not to provide documentation for packages


<!-- Sent from Reviewable.io -->

2024-05-07 01:06 UTC, FriendlyLifeguard commented on listings/ch17-starknet-smart-contracts-security/listing_02_pizza_factory/src/pizza.cairo
> +    pub impl InternalImpl of InternalTrait {
It seems like `pub` us required for `InternalImpl` in `test_set_as_new_owner_direct()` since it needs the following import: 

`use pizza::PizzaFactory::{InternalTrait};`

2024-05-07 02:05 UTC, FriendlyLifeguard commented on listings/ch17-starknet-smart-contracts-security/listing_02_pizza_factory_native/src/tests/native_test_overview.cairo
> +#[test]
I tried this but I'm still seeing the contract with anchor tags included. To double check, you mean to just import the cairo file without any paths like this? 

```
{{#include ../listings/ch17-starknet-smart-contracts-security/listing_02_pizza_factory_native/src/tests/native_test.cairo}}
```

2024-05-07 02:09 UTC, FriendlyLifeguard commented on src/ch17-02-testing-smart-contracts.md
> +
I have removed it since the test does not test is not intended for gas optimizations on user end.

2024-05-07 02:52 UTC, FriendlyLifeguard commented on listings/ch17-starknet-smart-contracts-security/listing_02_pizza_factory_snfoundry/src/tests/foundry_test_overview.cairo
> +    #[test]
I have included one in `test_deploy()` to call the `make_pizza` function after `stop_prank` with 

```
#[should_panic(expected: ('Only the owner can make pizza', ))]
```

2024-05-07 02:58 UTC, FriendlyLifeguard commented on src/ch17-02-testing-smart-contracts.md
> +In this section, we will give a brief overview of how to test Cairo smart contracts using Native Test Runner and Starknet Foundry.
I think it is fine as it is.

2024-05-10 05:26 UTC, FriendlyLifeguard commented
Hello, I made revisions in the following:

1. Overall structure including flow and grammar
2. Erased list of functions and instead added links to the libraries/documentations
3. Added explanation for `scarb test` 
4. Minor code updates to `PizzaFactory` and its testing contracts

Thank you so much for the feedbacks! Let me know if there's more needed!

2024-05-10 08:35 UTC, MaksymilianDemitraszek commented on src/ch17-02-testing-smart-contracts.md
> +In this section, we will give a brief overview of how to test Cairo smart contracts using Native Test Runner and Starknet Foundry.
In my opinion this is kinda misleading. Snfoundry is a superset of the native test runner. You can write both types of tests in foundry.

2024-05-10 08:39 UTC, MaksymilianDemitraszek commented on src/ch17-02-testing-smart-contracts.md
> +In this section, we will give a brief overview of how to test Cairo smart contracts using Native Test Runner and Starknet Foundry.
The only real advantage of using the native test runner is that is is pre-installed with `scarb`. Though this will probably change soon https://github.com/foundry-rs/starknet-foundry/issues/1982 . You will be able to choose which test runner you prefer to be installed with scarb.

2024-05-10 23:27 UTC, FriendlyLifeguard commented on src/ch17-02-testing-smart-contracts.md
> +In this section, we will give a brief overview of how to test Cairo smart contracts using Native Test Runner and Starknet Foundry.
That makes sense. I will change things regarding the opening summary. 

Then, to summarize:

"Starknet Foundry is a superset of native test runner which allows you to test in both runners. In the near future, Scarb will give the user an option to install their test runner of choice ." 

Also, can I say, if a developer is already familiar with ethereum foundry then it's easier to transition to starknet foundry therefore an advantage compared to native test runner?

2024-05-11 08:33 UTC, piotmag769 commented on src/ch17-02-testing-smart-contracts.md
> +In this section, we will give a brief overview of how to test Cairo smart contracts using Native Test Runner and Starknet Foundry.
I think @MaksymilianDemitraszek meant the paragraph below, which suggest that cairo-test is better for simple testing. It would be an equivalent of saying that `unittest` is better than `pytest` for testing simple python code.

2024-05-11 08:38 UTC, piotmag769 commented on src/ch17-02-testing-smart-contracts.md
> +In this section, we will give a brief overview of how to test Cairo smart contracts using Native Test Runner and Starknet Foundry.
>familiar with ethereum foundry then it's easier to transition to starknet foundry

I wouldn't say that it is always the case. It may help for understanding some features like cheatcodes, but some design choices are different between snforge and ethereum forge.

2024-05-13 08:09 UTC, enitrat commented
After thinking about it a bit more, I believe that we will take another approach: we will succintly introduce the native runner but keep the focus on using snfoundry when it comes to smart contract testing in the Cairo Book, for a few reasons:
1. The native runner is already introduced in the first section of the book when it comes tu pure Cairo
2. The overhead of using snfoundry compared to the native runner is small, and thus it should not be a factor of decision of which runner to use
3. Starknet foundry is constantly shipping new features (profiling, forking, fuzzing, etc), and transitioning between both runners is quite cumbersome

Thank you for the PR @FriendlyLifeguard ! It's great overall, I will take it from here to refactor some stuff :)

2024-05-13 21:36 UTC, enitrat commented
@MaksymilianDemitraszek @piotmag769 can you give a second look?

2024-05-13 21:38 UTC, merged