Add quiz for dictionaries chapter
cairo-book/cairo-book pull request #755
Opened 2024-05-02 13:52 UTC by Symmaque

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cairo-book/cairo-book/755)

2024-05-03 15:48 UTC, enitrat commented on quizzes/ch03-02-dictionaries.toml
> +    let mut balances: Felt252Dict<i64> = Default::default();
I'd rather use a Span as an example rather than an integer (as there's no real reason why i64 wouldn't be supported, it technically could as it fits in 1 single felt)

2024-05-03 15:58 UTC, TAdev0 requested changes
Overall, looks good! nevertheless, all quizzes are related to the `get` method to retrieve values from a dict at some point. It also introduced types not supported natively which is nice.

Could you add 1 or 2 more ,  for example one about squashing  and one about entry/finalize?

2024-05-03 15:58 UTC, TAdev0 commented on quizzes/ch03-02-dictionaries.toml
> +use core::dict::Felt252DictTrait;
> `use core::dict::Felt252DictTrait;`

This import can be removed

2024-05-03 15:58 UTC, TAdev0 commented on quizzes/ch03-02-dictionaries.toml
> +The code compiles and runs without panicking because the 'get' method returns 0 for a missing key.
for keys whose associated value is not initialized

2024-05-03 15:58 UTC, TAdev0 commented on quizzes/ch03-02-dictionaries.toml
> +use core::dict::Felt252DictTrait;
remove this import

2024-05-03 15:58 UTC, TAdev0 commented on quizzes/ch03-02-dictionaries.toml
> +The value type of this dictionary is `u64`, which is an unsigned integer. So the variable `alex_balance` is a unsigned integer that can't be negative.
The type of elements contained in this dictionary

2024-05-03 15:58 UTC, TAdev0 commented on quizzes/ch03-02-dictionaries.toml
> +use core::dict::Felt252DictTrait;
remove import

2024-05-03 15:58 UTC, TAdev0 commented on quizzes/ch03-02-dictionaries.toml
> +The value type of this dictionary is `i64`, which is not natively supported by the `Felt252Dict`. The code will not compile.
can you add precision about the need for the type to implement `zero_default` method of `Felt252DictValue<T>` trait, and the usage of `Nullable<T>` in such cases?

2024-05-08 11:24 UTC, enitrat commented on quizzes/ch03-02-dictionaries.toml
> +The value type of this dictionary is `i64`, which is not natively supported by the `Felt252Dict`. The code will not compile.
no required in the context here, the full answer is already in the chapter's content

2024-05-13 19:44 UTC, enitrat approved these changes

2024-05-13 19:44 UTC, merged