randomness dice_game_vrf
cairo-book/cairo-book pull request #778
Opened 2024-05-15 02:57 UTC by okhaimie-dev

2024-05-15 09:50 UTC, TAdev0 reviewed
@okhaimie-dev  looks good overall!

2024-05-15 09:50 UTC, TAdev0 commented on listings/ch16-building-advanced-starknet-smart-contracts/listing_06_dice_game_vrf/src/lib.cairo
> +            let user_guess: u8 = self.user_guesses.read(caller).into();
you can remove `into()`, you're casting u8 to u8 here, its superfluous

2024-05-15 09:50 UTC, TAdev0 commented on src/ch16-05-02-randomness.md
> +Since all blockchains are fundamentally deterministic and most are public ledgers, generating truly unpredictatable randomness on-chain presents a challenge. This randomness is crucial for fair outco
> offers

offer

2024-05-15 09:50 UTC, TAdev0 commented on src/ch16-05-02-randomness.md
> +Listing {{#ref dice_game_vrf}} shows an example of a simple dice game that uses Pragma VRF to generate random number:
> to generate random number

to generate a  random number

2024-05-15 09:50 UTC, TAdev0 commented on src/ch16-05-02-randomness.md
> +The contract above let's the contract owner call the `request_randomness_from_pragma` function to generate a random number stored in the `last_random_number` variable storage. The number generated is
> let's

lets

2024-05-15 09:50 UTC, TAdev0 commented on src/ch16-05-02-randomness.md
> +The contract above let's the contract owner call the `request_randomness_from_pragma` function to generate a random number stored in the `last_random_number` variable storage. The number generated is
> and compared to the guess of the caller in the `user_guesses` storage

and compared to the guess of the caller stored in the `user_guesses` mapping

2024-05-15 09:50 UTC, TAdev0 commented on src/ch16-05-02-randomness.md
> +The contract above let's the contract owner call the `request_randomness_from_pragma` function to generate a random number stored in the `last_random_number` variable storage. The number generated is
i think you can remove "by the `process_game_winners` function." , or say it differently maybe

2024-05-15 09:50 UTC, TAdev0 commented on src/ch16-05-02-randomness.md
> +#### NB: After Contract is Deployed
> After Contract is Deployed

After a Contract with  Pragma VRF Functionalities is Deployed ?

2024-05-15 12:28 UTC, TAdev0 submitted a review, later dismissed
@enitrat  LGTM overall. maybe a few improvements in the description of the game

waiting for your final review

2024-05-15 12:43 UTC, okhaimie-dev commented
Awesome! I am on standby for the rest of the day / available to implement @enitrat feedback

2024-05-15 19:59 UTC, enitrat requested changes
seeing errors when running `mdbook serve`: can you check?

```shell
Error: Reference to label 'standalone_interface' not found. In chapter: Contract Functions. In line: Listing {{#ref standalone_interface}} and listing {{#ref standalone}} show a rewrite of the `INameRegistry` interface that doesn't contain the `store_name` function, which is implemented as a standalone public function:
Error: Reference to label 'pragma_vrf_interface' not found. In chapter: Randomness. In line: Listing {{#ref pragma_vrf_interface}} shows a contract interfaces for Pragma VRF and a simple dice game:
```

Great work! Much better than the previous version as it's straight to the point and very clear on the fallback mechanism and how to request randomness

2024-05-15 19:59 UTC, enitrat commented on src/ch16-05-02-randomness.md
> +
It would be nice to have an introductory 3-4 liner about how a dice game works (first owner opens round, then players guess numbers, then the game is closed and the owner requests for randomness, and players can check if they have the right answers ?)

2024-05-15 21:01 UTC, okhaimie-dev commented on src/ch16-05-02-randomness.md
> +
Yes, this is correct. I'll make the intro in a bit

2024-05-16 03:40 UTC, okhaimie-dev commented on listings/ch16-building-advanced-starknet-smart-contracts/listing_06_dice_game_vrf/src/lib.cairo
> +pub trait IPragmaVRF<TContractState> {
It is an interface for entry points in the contract. More like a group of all the functions related to Pragma interaction in the contract.

Here is the line where I imported the Pragma dependency
```
use pragma_lib::abi::{IRandomnessDispatcher, IRandomnessDispatcherTrait};
```

2024-05-16 03:46 UTC, okhaimie-dev commented on src/ch16-05-02-randomness.md
> +#### `receive_randomn_words` Inputs
I took the entire function out, I felt this explanation is just a slight variation of an explanation I made a few lines above this

2024-05-16 03:51 UTC, okhaimie-dev commented
```sh
Error: Reference to label 'standalone_interface' not found. In chapter: Contract Functions. In line: Listing {{#ref standalone_interface}} and listing {{#ref standalone}} show a rewrite of the `INameRegistry` interface that doesn't contain the `store_name` function, which is implemented as a standalone public function:
Error: Reference to label 'pragma_vrf_interface' not found. In chapter: Randomness. In line: Listing {{#ref pragma_vrf_interface}} shows a contract interfaces for Pragma VRF and a simple dice game:
```

I couldn't recreate this issue on my local host, but the first error seems to be related to a different chapter, and the second one should be fixed with the section I got rid of

cc: @enitrat

2024-05-16 03:52 UTC, okhaimie-dev commented on src/ch16-05-02-randomness.md
> +
My changes turned out to be about 8 lines

2024-05-17 14:18 UTC, TAdev0 requested changes

2024-05-17 14:18 UTC, TAdev0 commented on src/ch16-05-02-randomness.md
> +This dice game contract allows players to guess a number between 1 & 6 during an active game window. The contract owner then has the ability to toggle the game window to disable new guesses from play
> variable storage

storage variable

2024-05-17 14:26 UTC, TAdev0 commented
@enitrat  just addressed the first error in a PR:
```
Error: Reference to label 'standalone_interface' not found. In chapter: Contract Functions. In line: Listing {{#ref standalone_interface}} and listing {{#ref standalone}} show a rewrite of the `INameRegistry` interface that doesn't contain the `store_name` function, which is implemented as a standalone public function:
```

2024-05-17 17:28 UTC, TAdev0 approved these changes

2024-05-17 18:04 UTC, merged