Unrecoverable errors with panic Chapter 9.1
cairo-book/cairo-book pull request #787
Opened 2024-05-15 22:24 UTC by addegbenga

2024-05-17 16:30 UTC, enitrat requested changes

2024-05-17 16:30 UTC, enitrat commented on quizzes/ch09-01-unrecoverable-errors-with-panic.toml
> +Which panic handling mechanism is generally preferred in Cairo?
Not true, i would delete this question

2024-05-17 16:30 UTC, enitrat commented on quizzes/ch09-01-unrecoverable-errors-with-panic.toml
> +What happens if you try to compile a function declared as `nopanic` that calls a function that may panic in Cairo?
Instead of asking an abstract question, write a concrete program representing this situation, ask whether it compiles, and if yes what the output is (see other quiz)

2024-05-17 16:30 UTC, enitrat commented on quizzes/ch09-01-unrecoverable-errors-with-panic.toml
> +What is the purpose of the panic_with attribute in Cairo?
```suggestion
What is the purpose of the `panic_with` attribute?
```
format

2024-05-17 16:30 UTC, enitrat commented on quizzes/ch09-01-unrecoverable-errors-with-panic.toml
> +answer.answer = "To create a wrapper function that panics on specific conditions"
```suggestion
answer.answer = "To create a wrapper function that panics if the result is `None` or `Err`"
```

2024-05-17 16:30 UTC, enitrat commented on quizzes/ch09-01-unrecoverable-errors-with-panic.toml
> +  "To create a wrapper function that panics on specific conditions",
mistake here?

2024-05-17 16:30 UTC, enitrat commented on quizzes/ch09-01-unrecoverable-errors-with-panic.toml
> +  "To catch errors and provide a resolution",
I think it's the same as the first distraction

2024-05-17 16:30 UTC, enitrat commented on quizzes/ch09-01-unrecoverable-errors-with-panic.toml
> +The panic_with attribute in Cairo is used to mark a function that returns an Option or Result. It creates a wrapper function for the annotated function that panics if the function returns None or Err
```suggestion
If your function is marked with `#[panic_with]` and returns `Result::Err` or `Option::None`, it will cause a runtime panic.
```

2024-05-17 16:30 UTC, enitrat commented on quizzes/ch09-01-unrecoverable-errors-with-panic.toml
> +"""
missing line at end of file

2024-05-17 16:30 UTC, enitrat commented on quizzes/ch09-01-unrecoverable-errors-with-panic.toml
> +Based on the provided code blocks, which code block will cause an inadvertent panic in Cairo?
Good start, I think it would be more interesting to ask the other way around:

Which of the following functions will NOT cause a runtime panic?

1. a function with a panic!("...")
2. a function with a loop on an array that accesses an index out of bounds
3. a function with a loop on an array that uses `array.get` to handle the result gracefully

2024-05-23 12:23 UTC, addegbenga commented
Sorry for the delays.
I just pushed a new pr addressing your comments kindly review @enitrat

2024-05-23 12:47 UTC, enitrat requested changes

2024-05-23 12:47 UTC, enitrat commented on quizzes/ch09-01-unrecoverable-errors-with-panic.toml
> +Based on the provided code blocks, Which of the following functions will NOT cause a runtime panic?
```suggestion
Based on the provided code blocks, which of the following functions will NOT cause a runtime panic?
```

2024-05-23 12:47 UTC, enitrat commented on quizzes/ch09-01-unrecoverable-errors-with-panic.toml
> +Will this program compiles when you run it? if yes what will be the output.
this should be a question of "Tracing" type, see what was done in other quizzes

2024-05-23 12:47 UTC, enitrat commented on quizzes/ch09-01-unrecoverable-errors-with-panic.toml
> +  "You can use the `panic_with` notation to indicate that a function will never panic",
This answer is not formatted like the other ones

2024-05-23 17:01 UTC, enitrat commented on quizzes/ch09-01-unrecoverable-errors-with-panic.toml
> +Will this program compiles when you run it? if yes what will be the output.
you also need to adapt the prompt!

2024-05-23 17:01 UTC, enitrat commented on quizzes/ch09-01-unrecoverable-errors-with-panic.toml
> +  "You can use the `#[panic_with]` notation to indicate that a function will never panic",
This answer is not formatted like the others. It is also repetitive with the question.

2024-05-23 22:59 UTC, enitrat commented on quizzes/ch09-01-unrecoverable-errors-with-panic.toml
> +  "You can use the `#[panic_with]` notation to indicate that a function will never panic",
well you can keep the format "To ..." but you have to be consistent

2024-05-23 23:06 UTC, addegbenga commented on quizzes/ch09-01-unrecoverable-errors-with-panic.toml
> +  "You can use the `#[panic_with]` notation to indicate that a function will never panic",
Oh okay i understand now.
Thanks

2024-05-25 13:06 UTC, enitrat commented on quizzes/ch09-01-unrecoverable-errors-with-panic.toml
> +Will this program compiles when you run it? if yes what will be the output.
```suggestion

```

2024-05-25 13:06 UTC, enitrat approved these changes

2024-05-25 13:19 UTC, enitrat approved these changes

2024-05-25 13:19 UTC, merged