feat: add quiz for chapter09-01
cairo-book/cairo-book pull request #793
Opened 2024-05-17 11:41 UTC by Ejembiii

2024-05-17 17:41 UTC, enitrat requested changes

2024-05-17 17:41 UTC, enitrat commented on quizzes/ch09-01-unrecoverable-errors-with-panic.toml
> +In Cairo, the panic function can be triggered:
check the syntax of the question, there are issues with your phrasing

2024-05-17 17:41 UTC, enitrat commented on quizzes/ch09-01-unrecoverable-errors-with-panic.toml
> +[[questions]]
Delete the two last questions, they're useless

2024-05-18 10:59 UTC, enitrat requested changes

2024-05-18 10:59 UTC, enitrat commented on quizzes/ch09-01-unrecoverable-errors-with-panic.toml
> +2. A statement.
"A statement" is not a well formed sentence in the context of the question. Pay attention to the quality!

2024-05-18 10:59 UTC, enitrat commented on quizzes/ch09-01-unrecoverable-errors-with-panic.toml
> +What does the ```panic_with``` attribute used for in Cairo?"""
the sentence is not written in good english, neither are the answers

2024-05-22 22:27 UTC, Ejembiii commented
@enitrat I've made the changes you requested

2024-05-25 13:05 UTC, enitrat submitted a review, later dismissed

2024-05-25 13:10 UTC, enitrat approved these changes

2024-05-25 13:10 UTC, merged