fix integration test section of the docs
cairo-book/cairo-book pull request #802
Opened 2024-05-21 06:47 UTC by mubarak23

- Change the folder structure of the code that show how integration test is done by 
moving test folder into the root of the project, where both SRC and TESTS are in the same tree,
- Make the changes to reflect in the md file
- Runs test to make to sure everything works

2024-05-21 16:22 UTC, enitrat requested changes
Still a lot of content missing - no changes in the markdown files?

2024-05-21 16:22 UTC, enitrat commented on src/ch10-02-test-organization.md
> +│   └── tests.cairo
no longer a `test.cairo` file here

2024-05-21 16:22 UTC, enitrat commented on src/ch10-02-test-organization.md
> +├── Cargo.lock
Cargo? 
restore the previous structure with the correct package name (using the `tree -L 2` command at the root)

2024-05-21 16:22 UTC, enitrat commented on listings/ch10-testing-cairo-programs/no_listing_09_integration_test/src/lib.cairo
> +pub fn it_adds_two(a: u8, b: u8) -> u8 {
why pub?

2024-06-10 16:06 UTC, TAdev0 commented
@mubarak23  are you still working on this?

2024-06-10 16:47 UTC, enitrat commented
Closing as no activity

2024-06-10 16:47 UTC, closed without merging