feat: init pragma price feed ch
cairo-book/cairo-book pull request #831
Opened 2024-06-05 02:44 UTC by okhaimie-dev

https://github.com/cairo-book/cairo-book/issues/798

2024-06-05 02:52 UTC, okhaimie-dev commented
@TAdev0 still a WIP. Also, I believe it will be helpful to make changes to the chapter on randomness to help with more context here.

2024-06-10 11:08 UTC, TAdev0 commented
@okhaimie-dev  is this ready for review?

2024-06-12 01:43 UTC, okhaimie-dev commented
> @okhaimie-dev is this ready for review?

I will switch it to ready for review within 24hrs. I will like to go over it one more time

2024-06-13 01:01 UTC, TAdev0 requested changes
@okhaimie-dev  overall looks good, but can you again describe a bit more the contract / your example?

Also left a comment for your calculation for `eth_needed`

2024-06-13 10:26 UTC, okhaimie-dev commented on listings/ch16-building-advanced-starknet-smart-contracts/listing_08_price_feed/src/lib.cairo
> +            let eth_needed = product_price * (10 * 8) / eth_price.into();
I intended to do 10 ** 8. I decided to just change it to * 100000000 for simplicity

the value returned from Pragma feed is in 8 decimal place
https://docs.pragma.build/Resources/Cairo%201/data-feeds/supported-assets#spot

so I needed to make that calculation so both `product_price` and `eth_price` have the same decimal

2024-06-13 10:27 UTC, okhaimie-dev commented
going to bed now it is 5 am here, but I have one more minor correction and it should be good for re-review

2024-06-13 10:29 UTC, okhaimie-dev commented
almost ready for re-review.

2024-06-22 12:48 UTC, TAdev0 requested changes

2024-06-22 12:48 UTC, TAdev0 commented on src/ch16-05-01-price-feeds.md
> +Price feeds enabled by an oracle serve as a bridge between real-world data feed and the blockchain. It provides real time pricing data that is aggregated from multiple trusted external sources ( e.g.
i think "They provide" would be more consistent witht the first sentence which is plurial with "price feeds"

2024-06-22 12:48 UTC, TAdev0 commented on src/ch16-05-01-price-feeds.md
> +The `get_asset_price` function is responsible for retrieving the price of the asset specified in the `asset_id` argument from Pragma Oracle. Inside the function, an instance of the `IPragmaDispatcher
> Finally, the function returns a `u128` the price property of `output`, which is the requested asset price.

what does this mean?

2024-06-22 12:48 UTC, TAdev0 commented on listings/ch16-building-advanced-starknet-smart-contracts/listing_08_price_feed/src/lib.cairo
> +                        0x0237726d12d3c7581156e141c1b132f2db9acf788296a0e6e4e9d0ef27d092a2
why did you change this address?

2024-06-22 12:53 UTC, TAdev0 commented on listings/ch16-building-advanced-starknet-smart-contracts/listing_08_price_feed/src/lib.cairo
> +            let caller_balance = eth_dispatcher.balance_of(caller_address);
do we really need this check? 

the `transfer_from` function will do this check in the `_update` private function in OZ contracts

2024-06-22 12:57 UTC, TAdev0 commented
Closes #798

2024-06-22 13:50 UTC, okhaimie-dev commented on listings/ch16-building-advanced-starknet-smart-contracts/listing_08_price_feed/src/lib.cairo
> +                        0x0237726d12d3c7581156e141c1b132f2db9acf788296a0e6e4e9d0ef27d092a2
initial one was a mainnet address

2024-06-22 13:54 UTC, okhaimie-dev commented on listings/ch16-building-advanced-starknet-smart-contracts/listing_08_price_feed/src/lib.cairo
> +            let caller_balance = eth_dispatcher.balance_of(caller_address);
you are correct, the check is already in the `update` function on OZ erc20 token contract

2024-06-22 20:08 UTC, TAdev0 submitted a review, later dismissed

2024-06-23 20:15 UTC, enitrat reviewed
excellent :)

2024-06-23 20:15 UTC, enitrat commented on src/ch16-05-01-price-feeds.md
> +The `get_asset_price` function is responsible for retrieving the price of the asset specified in the `asset_id` argument from Pragma Oracle. Inside the function, an instance of the `IPragmaDispatcher
```suggestion
The `get_asset_price` function is responsible for retrieving the price of the asset specified by the `asset_id` argument from Pragma Oracle. The `get_data_median` method is called from the `IPragmaDispatcher` instance by passing the `DataType::SpotEntry(asset_id)` as an argument and its output is assigned to a variable named `output` of type `PragmaPricesResponse`. Finally, the function returns the price of the requested asset as a `u128`.
```

2024-06-23 20:15 UTC, enitrat commented on src/ch16-05-01-price-feeds.md
> +The code above is an example implementation of price feed using the Pragma oracle. The contract imports necessary modules and interfaces, including the `IPragmaABIDispatcher` for interacting with the
```suggestion
The code above is an example implementation of an applications consuming a price feed from the Pragma oracle. The contract imports necessary modules and interfaces, including the `IPragmaABIDispatcher` for interacting with the Pragma oracle contract and the `ERC20ABIDispatcher` for interacting with the ETH ERC20 token contract.
```

2024-06-23 20:15 UTC, enitrat commented on src/ch16-05-01-price-feeds.md
> +The contract has a `const` that stores the token pair ID of `ETH/USD`, and a `Storage` struct that holds two fields `pragma_contract` and `product_price_in_usd`, then the constructor function initial
```suggestion
The contract has a `const` that stores the token pair ID of `ETH/USD`, and a `Storage` struct that holds two fields `pragma_contract` and `product_price_in_usd`. The constructor function initializes the `pragma_contract` address and sets the `product_price_in_usd` to 100.
```

2024-06-23 20:15 UTC, enitrat commented on listings/ch16-building-advanced-starknet-smart-contracts/listing_08_price_feed/src/lib.cairo
> +            let eth_needed = product_price * 100000000 / eth_price;
what is `100000000`?

2024-06-24 11:01 UTC, okhaimie-dev commented on listings/ch16-building-advanced-starknet-smart-contracts/listing_08_price_feed/src/lib.cairo
> +            let eth_needed = product_price * 100000000 / eth_price;
`100000000` puts `product_price` and `eth_price` returned from Pragma Oracle in the same decimal place. = ETH/USD price returned from the price feed has 8 decimals while `product_price` does not, so I had to carry out a conversion.

https://docs.pragma.build/Resources/Cairo%201/data-feeds/supported-assets#spot

2024-06-24 11:09 UTC, TAdev0 approved these changes

2024-06-24 13:55 UTC, enitrat commented on listings/ch16-building-advanced-starknet-smart-contracts/listing_08_price_feed/src/lib.cairo
> +            let eth_needed = product_price * 100000000 / eth_price;
I think it's nice to have a small explanation about the usage of decimals!

2024-06-24 13:56 UTC, enitrat commented on listings/ch16-building-advanced-starknet-smart-contracts/listing_08_price_feed/src/lib.cairo
> +            let eth_needed = product_price * 100000000 / eth_price;
also: make it a named constant variable instead of a value

2024-06-24 21:07 UTC, TAdev0 requested changes

2024-06-24 21:07 UTC, TAdev0 commented on src/ch16-05-01-price-feeds.md
> +> Note: Pragma returns the value of different token pairs using the decimal factor of 6 or 8. You can convert the value to the required decimal factor by dividing the value by 10^decimal_factor.
You should format nicely 10^... 

Check the Data Type chapter md file you ll see how to use latex in md files

2024-06-24 22:49 UTC, okhaimie-dev commented on src/ch16-05-01-price-feeds.md
> +> Note: Pragma returns the value of different token pairs using the decimal factor of 6 or 8. You can convert the value to the required decimal factor by dividing the value by 10^decimal_factor.
done

2024-06-24 23:33 UTC, TAdev0 approved these changes

2024-06-25 08:04 UTC, merged