Add information about `///` and `//!` comments and their purpose
cairo-book/cairo-book pull request #833
Opened 2024-06-07 09:45 UTC by misicnenad

Closes #830

2024-06-07 09:52 UTC, enitrat commented on src/ch02-04-comments.md
> +### Contract-element Documentation Comments
Prefer this terminology: https://github.com/cairo-book/cairo-book/issues/830#issuecomment-2147675351

we don't want to mention _contracts_, but _modules_. Contract-element are simply _items_. We're not in the context of Starknet here, but only pure Cairo (so, no such thing as a _contract method_ or an _event_)

2024-06-07 09:52 UTC, enitrat commented on src/ch02-04-comments.md
> +Contract documentation provides an overview of the entire contract, including its purpose and examples of use. These comments are meant to be placed at the top of the file and are prefixed with `//!`
same, _module_

2024-06-07 09:54 UTC, misicnenad commented on src/ch02-04-comments.md
> +### Contract-element Documentation Comments
> We're not in the context of Starknet here, but only pure Cairo

Ah yes, we're still in chapter 2. Thanks!

2024-06-07 11:24 UTC, TAdev0 requested changes
@misicnenad  left a few comments !

2024-06-07 11:24 UTC, TAdev0 commented on listings/ch02-common-programming-concepts/no_listing_37_item_doc_comments/src/lib.cairo
> +/// ```rust
i think you can remove `rust` here?

2024-06-07 11:24 UTC, TAdev0 commented on listings/ch02-common-programming-concepts/no_listing_37_item_doc_comments/src/lib.cairo
> +/// Returns the sum of `arg1` and `arg2`.
> Returns the sum of `arg1` and `arg2`.

`add` function returns the sum of `arg1` and `arg2`.

2024-06-07 11:24 UTC, TAdev0 commented on listings/ch02-common-programming-concepts/no_listing_38_mod_doc_comments/src/lib.cairo
> +//! }
missing ``` at the end of the example

2024-06-07 11:24 UTC, TAdev0 commented on src/ch02-04-comments.md
> +```rust
> rust

rust,noplayground

2024-06-07 11:24 UTC, TAdev0 commented on src/ch02-04-comments.md
> +Item-level documentation comments refer to specific items such as methods, implementations, etc. These comments provide a detailed description of the item, examples of usage, and any conditions that
> Some implementations may also include

Such comments may also include separate sections,  for example parameters and return value descriptions in the case of method implementation.

I dont know if its better, just a suggestion

2024-06-07 11:24 UTC, TAdev0 commented on src/ch02-04-comments.md
> +```rust
noplayground as well

2024-06-07 11:24 UTC, TAdev0 commented on src/ch02-04-comments.md
> +Module documentation comments provide an overview of the entire module, including its purpose and examples of use. These comments are meant to be placed at the top of the file and are prefixed with `
> at the top of the file 

One file could contain multiple modules, not sure its accurate

2024-06-07 11:55 UTC, enitrat commented on listings/ch02-common-programming-concepts/no_listing_37_item_doc_comments/src/lib.cairo
> +/// Returns the sum of `arg1` and `arg2`.
not sure what you meant here @TAdev0

2024-06-07 11:57 UTC, enitrat commented
for reference: https://blog.guillaume-gomez.fr/articles/2020-03-12+Guide+on+how+to+write+documentation+for+a+Rust+crate

2024-06-07 15:00 UTC, TAdev0 commented on listings/ch02-common-programming-concepts/no_listing_37_item_doc_comments/src/lib.cairo
> +/// Returns the sum of `arg1` and `arg2`.
I don't known, it's a sentence with a endpoint that starts with "Returns" , but anyway doesn't matter

2024-06-07 15:29 UTC, enitrat commented on listings/ch02-common-programming-concepts/no_listing_37_item_doc_comments/src/lib.cairo
> +/// Returns the sum of `arg1` and `arg2`.
yeah that's the convention for code documentation

2024-06-07 15:37 UTC, TAdev0 commented on listings/ch02-common-programming-concepts/no_listing_37_item_doc_comments/src/lib.cairo
> +/// Returns the sum of `arg1` and `arg2`.
oh ok i didn't know thanks!

2024-06-07 15:45 UTC, enitrat commented on listings/ch02-common-programming-concepts/no_listing_37_item_doc_comments/src/lib.cairo
> +/// Returns the sum of `arg1` and `arg2`.
https://blog.guillaume-gomez.fr/articles/2020-03-12+Guide+on+how+to+write+documentation+for+a+Rust+crate

2024-06-07 16:34 UTC, misicnenad commented on src/ch02-04-comments.md
> +Item-level documentation comments refer to specific items such as methods, implementations, etc. These comments provide a detailed description of the item, examples of usage, and any conditions that
How about the following (bolded the changed parts)?

> Item-level documentation comments refer to specific items such as methods, implementations, **traits**, etc. **They are prefixed with three slashes (`///`)**. These comments provide a detailed description of the item, examples of usage, and any conditions that might cause a panic. **In case of methods and functions** _[editor note: these are different, right? [Methods](https://book.cairo-lang.org/ch05-03-method-syntax.html) and [functions](https://book.cairo-lang.org/ch02-03-functions.html)]_, **the comments** may also include separate sections for parameter and return value descriptions.

2024-06-07 16:36 UTC, misicnenad commented on src/ch02-04-comments.md
> +Module documentation comments provide an overview of the entire module, including its purpose and examples of use. These comments are meant to be placed at the top of the file and are prefixed with `
How about this (bolded the changed parts)?

> Module documentation comments provide an overview of the entire module, including its purpose and examples of use. These comments are meant to be placed **above the module they're describing** and are prefixed with `//!`. This type of documentation gives a broad understanding of what the module does and how it can be used.

2024-06-10 09:18 UTC, enitrat commented on listings/ch02-common-programming-concepts/no_listing_38_mod_doc_comments/src/lib.cairo
> +//! mod MyOtherModule {
```suggestion
//! mod my_other_module {
```

2024-06-10 09:18 UTC, enitrat commented on listings/ch02-common-programming-concepts/no_listing_38_mod_doc_comments/src/lib.cairo
> +//!   use path::to::MyModule;
```suggestion
//!   use path::to::my_module;
```

2024-06-10 09:18 UTC, enitrat commented on listings/ch02-common-programming-concepts/no_listing_38_mod_doc_comments/src/lib.cairo
> +//!     MyModule.my_selector();
```suggestion
//!     my_module::bar();
```

2024-06-10 09:18 UTC, enitrat commented on listings/ch02-common-programming-concepts/no_listing_38_mod_doc_comments/src/lib.cairo
> +mod MyModule { // rest of implementation...
```suggestion
mod my_module { // rest of implementation...
```

2024-06-10 09:18 UTC, enitrat commented on src/ch02-04-comments.md
> +Item-level documentation comments refer to specific items such as methods, implementations, etc. These comments provide a detailed description of the item, examples of usage, and any conditions that
I would remove mentions of _methods_ and simply mention functions. otherwise, looks good

2024-06-10 09:18 UTC, enitrat commented on src/ch02-04-comments.md
> +Module documentation comments provide an overview of the entire module, including its purpose and examples of use. These comments are meant to be placed at the top of the file and are prefixed with `
good

2024-06-10 11:17 UTC, TAdev0 requested changes

2024-06-10 11:17 UTC, TAdev0 commented on src/ch02-04-comments.md
> +```rust,noplayground
all others should be noplayground

2024-06-10 11:52 UTC, TAdev0 commented on src/ch02-04-comments.md
> +```rust,noplayground
i think we by default make runnable all files with a main function, but doesnt matter yeah

2024-06-10 11:53 UTC, TAdev0 approved these changes

2024-06-10 11:56 UTC, misicnenad commented on src/ch02-04-comments.md
> +```rust,noplayground
Oh ok, will keep that in mind going forward.

2024-06-10 16:33 UTC, merged