update integration tests
cairo-book/cairo-book pull request #836
Opened 2024-06-11 14:45 UTC by Symmaque

2024-06-11 16:37 UTC, enitrat commented on listings/ch10-testing-cairo-programs/no_listing_09_integration_test/Scarb.toml
> +edition = "2024_06"
```suggestion
version = "0.1.0"
edition = "2023_11"
```



it's not the current date :laughing:

2024-06-22 23:30 UTC, Symmaque commented
> @Symmaque any update on this?

Trying to figure out why the CI doesn't work

2024-06-24 18:46 UTC, TAdev0 requested changes

2024-06-24 18:46 UTC, TAdev0 commented on src/ch10-02-test-organization.md
> +You need to add `pub` otherwise it'll be impossible to import the function in the test files.
> You need to add `pub` otherwise it'll be impossible to import the function in the test files.

We need to add the `pub` keyword to the `it_adds_two` function, otherwise it will not be possible to import it in the test files.

2024-06-24 18:46 UTC, TAdev0 commented on src/ch10-02-test-organization.md
> +Then, we need to write the integration test in the tests/integration*tests.cairo* file:
why `integration*tests.cairo*` ? should be `integration_tests.cairo` no?

2024-06-24 22:30 UTC, enitrat commented on src/ch10-02-test-organization.md
> +Then, we need to write the integration test in the tests/integration*tests.cairo* file:
I think formatter modified this automatically

2024-06-25 13:52 UTC, TAdev0 approved these changes

2024-06-25 16:00 UTC, enitrat requested changes
needs more changes

2024-06-27 08:57 UTC, enitrat commented
@TAdev0 can you proofread locally (`mdbook serve` and read from start to bottom, make sure everything makes sense)?

it should be good now.

2024-06-27 09:10 UTC, TAdev0 commented
Sure

2024-06-30 08:39 UTC, TAdev0 requested changes

2024-06-30 08:39 UTC, TAdev0 commented on src/ch10-02-test-organization.md
> +There’s debate within the testing community about whether or not private functions should be tested directly, and other languages make it difficult or impossible to test private functions. Regardless
one  ` to remove

2024-06-30 08:39 UTC, TAdev0 commented on listings/ch10-testing-cairo-programs/no_listing_11_test_private_function/src/lib.cairo
> +    #[test]
missing space before #[test]

2024-06-30 08:39 UTC, TAdev0 commented on src/ch10-02-test-organization.md
> +Note that the `internal_adder` function is not marked as `pub`. Tests are just Cairo code, and the tests module is just another module. As we discussed in the ["Paths for Referring to an Item in the
> we bring the `tests` module’s parent’s

we bring the `tests` module’s parent ?

2024-06-30 08:39 UTC, TAdev0 commented on src/ch10-02-test-organization.md
> +The first displayed section for the integration tests.
> The first displayed section for the integration tests.

The first displayed section is for the integration tests.

2024-06-30 08:39 UTC, TAdev0 commented on src/ch10-02-test-organization.md
> +Each integration test file has its own section, so if we add more files in the tests directory, there will be more integration test sections.
> tests

_tests_

2024-06-30 08:39 UTC, TAdev0 commented on src/ch10-02-test-organization.md
> +As you add more integration tests, you might want to make more files in the tests directory to help organize them; for example, you can group the test functions by the functionality they’re testing.
> tests directory

_tests_ directory

2024-06-30 08:48 UTC, TAdev0 commented on src/ch10-02-test-organization.md
> +There’s debate within the testing community about whether or not private functions should be tested directly, and other languages make it difficult or impossible to test private functions. Regardless
```suggestion
There’s debate within the testing community about whether or not private functions should be tested directly, and other languages make it difficult or impossible to test private functions. Regardless of which testing ideology you adhere to, Cairo's privacy rules do allow you to test private functions. Consider the code below with the private function `internal_adder`.
```

2024-06-30 08:48 UTC, TAdev0 commented on src/ch10-02-test-organization.md
> +Note that the `internal_adder` function is not marked as `pub`. Tests are just Cairo code, and the tests module is just another module. As we discussed in the ["Paths for Referring to an Item in the
```suggestion
Note that the `internal_adder` function is not marked as `pub`. Tests are just Cairo code, and the tests module is just another module. As we discussed in the ["Paths for Referring to an Item in the Module Tree"](ch07-03-paths-for-referring-to-an-item-in-the-module-tree.md) section, items in child modules can use the items in their ancestor modules. In this test, we bring the `tests` module’s parent `internal_adder` into scope with `use super::internal_adder;` and then the test can call `internal_adder`. If you don’t think private functions should be tested, there’s nothing in Cairo that will compel you to do so.
```

2024-06-30 08:48 UTC, TAdev0 commented on src/ch10-02-test-organization.md
> +The first displayed section for the integration tests.
```suggestion
The first displayed section is for the integration tests.
```

2024-06-30 08:48 UTC, TAdev0 commented on src/ch10-02-test-organization.md
> +Each integration test file has its own section, so if we add more files in the tests directory, there will be more integration test sections.
```suggestion
Each integration test file has its own section, so if we add more files in the _tests_ directory, there will be more integration test sections.
```

2024-06-30 08:48 UTC, TAdev0 commented on src/ch10-02-test-organization.md
> +As you add more integration tests, you might want to make more files in the tests directory to help organize them; for example, you can group the test functions by the functionality they’re testing.
```suggestion
As you add more integration tests, you might want to make more files in the _tests_ directory to help organize them; for example, you can group the test functions by the functionality they’re testing. As mentioned earlier, each file in the tests directory is compiled as its own separate crate, which is useful for creating separate scopes to more closely imitate the way end users will be using your crate. However, this means files in the tests directory don’t share the same behavior as files in _src_ do, as you learned in Chapter 7 regarding how to separate code into modules and files.
```

2024-06-30 11:57 UTC, enitrat commented on listings/ch10-testing-cairo-programs/no_listing_11_test_private_function/src/lib.cairo
> +    #[test]
```suggestion
    use super::internal_adder;
    
    #[test]
```

2024-06-30 17:48 UTC, merged