Feat: Add Deref Coercion
cairo-book/cairo-book pull request #897
Opened 2024-07-28 16:52 UTC by blocksorcerer

Closes #890

2024-07-30 18:24 UTC, enitrat commented
Lots of CI errors due to `no_listing_09_deref_coercion_example`, please check

2024-07-30 18:41 UTC, enitrat commented on src/ch11-09-deref-coercion.md
> +This mechanism is enabled by implementing the `Deref` trait, which allows implicit conversion (or coercion) of references to a different type, providing direct access to the underlying data. Addition
Careful about terminology: How could you rephrase this to avoid using the term `mutable reference` (and more generally `reference`) ?

2024-07-30 18:41 UTC, enitrat commented on src/ch11-09-deref-coercion.md
> +The `Deref` and `DerefMut` traits are used to override the behavior of the dereference operator `*`. When implemented for a type, they allow an instance of that type to automatically convert to its t
This is factually not true: Deref and DerefMut have no impact on the `*` operator (at least, yet)

2024-07-30 18:41 UTC, enitrat commented on src/ch11-09-deref-coercion.md
> +## Deref and DerefMut Coercion in Action
The example provided is a good start, but it can be further improved to display a stronger use case combined with generic types.

For example, this could be defining our own "wrapper type" like the Box<T> type, that would simply wrap any data of type T `MyBox<T>`.

By implementing a generic implementation of the Deref<MyBox<T>> type, we can demonstrate how we can easily abstract the complexity of any generic wrapper type by implementing this Deref Trait - and that's mostly how it's being used in the core library (e.g. for `Nullable`, `Box`, `StorageNode`, etc...)

for reference, this is how it's presented in the Rust Book: https://doc.rust-lang.org/book/ch15-02-deref.html?highlight=deref#defining-our-own-smart-pointer

2024-08-04 17:41 UTC, blocksorcerer commented on src/ch11-09-deref-coercion.md
> +This mechanism is enabled by implementing the `Deref` trait, which allows implicit conversion (or coercion) of references to a different type, providing direct access to the underlying data. Addition
How about something like following:-

In Cairo, deref coercion simplifies the way we interact with nested or wrapped data structures by allowing an instance of one type to behave like an instance of another type. This mechanism is enabled by implementing the `Deref` trait, which allows implicit conversion (or coercion) to a different type, providing direct access to the underlying data. Additionally, the `DerefMut` trait allows similar coercion, enabling direct modification of the target data. For now, only member access via deref is supported, i.e. implementations with functions whose self argument is of the original type will not be applicable when holding an instance of the coerced type.

2024-08-04 17:41 UTC, blocksorcerer commented on src/ch11-09-deref-coercion.md
> +The `Deref` and `DerefMut` traits are used to override the behavior of the dereference operator `*`. When implemented for a type, they allow an instance of that type to automatically convert to its t
Thanks for letting me know, I've changed this.

2024-08-04 17:41 UTC, blocksorcerer commented on src/ch11-09-deref-coercion.md
> +## Deref and DerefMut Coercion in Action
Can't access this `DerefMut` trait. Getting trait not exists error! 
Also I've changed the example to show a generic wrapper type.

2024-08-04 20:27 UTC, enitrat commented on src/ch11-09-deref-coercion.md
> +This mechanism is enabled by implementing the `Deref` trait, which allows implicit conversion (or coercion) of references to a different type, providing direct access to the underlying data. Addition
looks good

2024-08-06 13:08 UTC, blocksorcerer commented on src/ch11-09-deref-coercion.md
> +## Deref and DerefMut Coercion in Action
@enitrat any suggestions on this one?? Getting `error: Trait not found.` for DerefMut

2024-08-06 13:57 UTC, enitrat commented on src/ch11-09-deref-coercion.md
> +## Deref and DerefMut Coercion in Action
did you import it ?

2024-08-06 14:13 UTC, blocksorcerer commented on src/ch11-09-deref-coercion.md
> +## Deref and DerefMut Coercion in Action
I haven't... Import needed? Deref is working fine that's why!

2024-08-07 08:04 UTC, enitrat commented
so actually DerefMut is not like Rust's - its usage is only for cases where you want deref to work only for a mut variable

2024-08-08 15:42 UTC, blocksorcerer commented on src/ch11-09-deref-coercion.md
> +The `Deref` and `DerefMut` traits are used to override the behavior of the dereference operator `*`. When implemented for a type, they allow an instance of that type to automatically convert to its t
Please review d76aaf7

2024-08-08 15:43 UTC, blocksorcerer commented on src/ch11-09-deref-coercion.md
> +This mechanism is enabled by implementing the `Deref` trait, which allows implicit conversion (or coercion) of references to a different type, providing direct access to the underlying data. Addition
Fixed in d76aaf7

2024-08-08 21:12 UTC, enitrat requested changes
It's getting better!

Some restructuring still required, and all the part about `DerefMut` does not explain what it actually does.

2024-08-08 21:12 UTC, enitrat commented on listings/ch11-advanced-features/no_listing_09_deref_coercion_example/src/lib.cairo
> +}
remove all these functions, you can simply inline stuff in main

2024-08-08 21:12 UTC, enitrat commented on listings/ch11-advanced-features/no_listing_09_deref_coercion_example/src/lib.cairo
> +}
```suggestion
fn main() {
    let wrapped_profile = Wrapper { 
        value: UserProfile { 
            username: 'john_doe', 
            email: 'john@example.com', 
            age: 30 
        } 
    };

    // Access fields directly via deref coercion
    println!("Username: {}", wrapped_profile.username);
    println!("Current age: {}", wrapped_profile.age);
}
```

2024-08-08 21:12 UTC, enitrat commented on src/ch11-09-deref-coercion.md
> +### The Deref Trait
```suggestion
### Deref in Action
```

Move the example of using `Deref` (and not DerefMut) here

2024-08-08 21:12 UTC, enitrat commented on src/ch11-09-deref-coercion.md
> +### The DerefMut Trait
```suggestion
### Restricting Deref Coercion with `DerefMut`
```

2024-08-08 21:12 UTC, enitrat commented on src/ch11-09-deref-coercion.md
> +The `DerefMut` trait works similarly but is used for mutable access:
update with the proper definition as per my previous comment

2024-08-08 21:12 UTC, enitrat commented on src/ch11-09-deref-coercion.md
> +
Here you must explicitly illustrate what's the difference between Deref and DerefMut. `Deref` will work for non-mut AND mut variables, while DerefMut will only work with non-mut variables.

In practice DerefMut probably doesn't have a lot of use cases. Thus you should illustrate that if you try to  use deref-coercion, having implemented DerefMut, on a non-mut variable, compilation fails, see following example

```rust
impl DerefMutUserProfile of core::ops::DerefMut<Wrapper<UserProfile>> {
    type Target = UserProfile;
    fn deref_mut(ref self: Wrapper<UserProfile>) -> Self::Target {
        self.value
    }
}

fn main() {
    let wrapped_profile = Wrapper {
        value: UserProfile { username: 'john_doe', email: 'john@example.com', age: 30 }
    };
    // Access fields directly via deref coercion
    println!("Username: {}", wrapped_profile.username);
    println!("Current age: {}", wrapped_profile.age);
}
```

2024-08-08 21:12 UTC, enitrat commented on src/ch11-09-deref-coercion.md
> +By using the `Deref` and `DerefMut` traits, we can create a generic wrapper type like `Wrapper<T>` that allows seamless access to the underlying data. This pattern is common in core libraries for abs
See comments above regarding re-structuration of this example

2024-08-12 19:08 UTC, blocksorcerer commented on src/ch11-09-deref-coercion.md
> +Let’s consider a generic wrapper type, similar to a smart pointer, that can wrap any data of type `T`. By implementing the `Deref` and `DerefMut` traits generically, we can abstract away the complexi
changed in b73a359

2024-08-12 19:09 UTC, blocksorcerer commented on src/ch11-09-deref-coercion.md
> +The `Wrapper` struct wraps a single value of type `T`. Normally, accessing this value would require going through `Wrapper.value`.
changed in b73a359

2024-08-12 19:09 UTC, blocksorcerer commented on listings/ch11-advanced-features/no_listing_09_deref_coercion_example/src/lib.cairo
> +}
Implemented in b73a359

2024-08-12 19:09 UTC, blocksorcerer commented on src/ch11-09-deref-coercion.md
> +
Please check b73a359

2024-08-20 16:50 UTC, enitrat submitted a review, later dismissed

2024-08-20 17:33 UTC, merged